/*\n  # Fix Job Status Enum Casting\n\n  ## Summary\n  Fixes the type casting issue in the update_job_completion_status function.\n  The status column uses the unified_status enum type, not text.\n\n  ## Changes\n  - Properly cast text status values to unified_status enum type\n  - Ensures status updates work correctly with the database schema\n*/\n\n-- Drop and recreate the function with proper enum casting\nDROP TRIGGER IF EXISTS trigger_update_job_completion ON job_schedules;
\nDROP FUNCTION IF EXISTS update_job_completion_status();
\n\nCREATE OR REPLACE FUNCTION update_job_completion_status()\nRETURNS trigger AS $$\nDECLARE\n  first_schedule_datetime timestamptz;
\n  last_schedule_datetime timestamptz;
\n  current_status unified_status;
\n  new_status unified_status;
\nBEGIN\n  -- Get the first scheduled datetime for this job\n  SELECT \n    CASE \n      WHEN scheduled_time_start IS NOT NULL THEN\n        (scheduled_date || ' ' || scheduled_time_start)::timestamptz\n      ELSE\n        (scheduled_date || ' 00:00:00')::timestamptz\n    END INTO first_schedule_datetime\n  FROM job_schedules\n  WHERE lead_id = COALESCE(NEW.lead_id, OLD.lead_id)\n  ORDER BY scheduled_date ASC, scheduled_time_start ASC NULLS FIRST\n  LIMIT 1;
\n\n  -- Get the last scheduled datetime for this job\n  SELECT \n    CASE \n      WHEN scheduled_time_end IS NOT NULL THEN\n        (scheduled_date || ' ' || scheduled_time_end)::timestamptz\n      ELSE\n        (scheduled_date || ' 23:59:59')::timestamptz\n    END INTO last_schedule_datetime\n  FROM job_schedules\n  WHERE lead_id = COALESCE(NEW.lead_id, OLD.lead_id)\n  ORDER BY scheduled_date DESC, scheduled_time_end DESC NULLS LAST\n  LIMIT 1;
\n\n  -- Get current job status\n  SELECT status INTO current_status\n  FROM leads\n  WHERE id = COALESCE(NEW.lead_id, OLD.lead_id);
\n\n  -- Determine new status based on schedule\n  IF first_schedule_datetime IS NULL THEN\n    -- No schedules exist, don't change status\n    RETURN COALESCE(NEW, OLD);
\n  ELSIF now() > last_schedule_datetime THEN\n    -- Current time is after the last scheduled datetime\n    new_status := 'completed'::unified_status;
\n  ELSIF now() >= first_schedule_datetime AND now() <= last_schedule_datetime THEN\n    -- Current time is within the scheduled range (including all of today if it's a scheduled day)\n    new_status := 'in_progress'::unified_status;
\n  ELSIF now() < first_schedule_datetime THEN\n    -- Current time is before the first scheduled datetime\n    new_status := 'scheduled'::unified_status;
\n  END IF;
\n\n  -- Update status if it needs to change\n  -- Allow updating from 'completed' back to 'in_progress' or 'scheduled' if schedule changed\n  -- But never override manually set final statuses like 'won', 'lost', 'invoiced', 'paid'\n  IF new_status IS NOT NULL \n     AND new_status != current_status \n     AND current_status NOT IN ('won', 'lost', 'invoiced', 'paid') THEN\n    UPDATE leads\n    SET status = new_status, updated_at = now()\n    WHERE id = COALESCE(NEW.lead_id, OLD.lead_id);
\n  END IF;
\n\n  RETURN COALESCE(NEW, OLD);
\nEND;
\n$$ LANGUAGE plpgsql SECURITY DEFINER;
\n\n-- Recreate trigger\nCREATE TRIGGER trigger_update_job_completion\n  AFTER INSERT OR UPDATE OR DELETE ON job_schedules\n  FOR EACH ROW\n  EXECUTE FUNCTION update_job_completion_status();
\n;
