/*\n  # Fix Security Issues: Indexes, RLS Performance, and Function Search Paths\n\n  1. Missing Foreign Key Indexes\n    - Add index on `estimates.recurring_job_id`\n    - Add index on `job_checklist_items.account_id`\n    - Add index on `sms_notification_log.user_id`\n\n  2. RLS Policy Performance\n    - Replace `auth.uid()` with `(select auth.uid())` in policies on:\n      - `estimate_line_items_original` (2 policies)\n      - `job_line_items` (4 policies)\n      - `financial_exports` (3 policies)\n      - `mock_crew_profiles` (4 policies)\n      - `job_assignments` (1 policy: insert)\n      - `estimate_versions` (4 policies)\n      - `account_members` (3 policies: insert, update, delete)\n\n  3. Function Search Path Fixes\n    - Set `search_path = ''` on 6 functions with mutable search paths\n\n  4. Drop Unused Indexes\n    - Remove 35 indexes that have never been used\n*/\n\n-- ============================================================\n-- 1. Add missing foreign key indexes\n-- ============================================================\n\nCREATE INDEX IF NOT EXISTS idx_estimates_recurring_job_id\n  ON public.estimates (recurring_job_id);
\n\nCREATE INDEX IF NOT EXISTS idx_job_checklist_items_account_id\n  ON public.job_checklist_items (account_id);
\n\nCREATE INDEX IF NOT EXISTS idx_sms_notification_log_user_id_v2\n  ON public.sms_notification_log (user_id);
\n\n-- ============================================================\n-- 2. Fix RLS policies to use (select auth.uid())\n-- ============================================================\n\n-- estimate_line_items_original\nDROP POLICY IF EXISTS "Users can view original line items for their account" ON public.estimate_line_items_original;
\nCREATE POLICY "Users can view original line items for their account"\n  ON public.estimate_line_items_original FOR SELECT TO authenticated\n  USING (EXISTS (\n    SELECT 1 FROM account_members\n    WHERE account_members.account_id = estimate_line_items_original.account_id\n    AND account_members.user_id = (select auth.uid())\n    AND account_members.is_active = true\n  ));
\n\nDROP POLICY IF EXISTS "Users can insert original line items for their account" ON public.estimate_line_items_original;
\nCREATE POLICY "Users can insert original line items for their account"\n  ON public.estimate_line_items_original FOR INSERT TO authenticated\n  WITH CHECK (EXISTS (\n    SELECT 1 FROM account_members\n    WHERE account_members.account_id = estimate_line_items_original.account_id\n    AND account_members.user_id = (select auth.uid())\n    AND account_members.is_active = true\n  ));
\n\n-- job_line_items\nDROP POLICY IF EXISTS "Users can view job line items in their account" ON public.job_line_items;
\nCREATE POLICY "Users can view job line items in their account"\n  ON public.job_line_items FOR SELECT TO authenticated\n  USING (account_id IN (\n    SELECT account_members.account_id FROM account_members\n    WHERE account_members.user_id = (select auth.uid())\n    AND account_members.is_active = true\n  ));
\n\nDROP POLICY IF EXISTS "Users can insert job line items in their account" ON public.job_line_items;
\nCREATE POLICY "Users can insert job line items in their account"\n  ON public.job_line_items FOR INSERT TO authenticated\n  WITH CHECK (account_id IN (\n    SELECT account_members.account_id FROM account_members\n    WHERE account_members.user_id = (select auth.uid())\n    AND account_members.is_active = true\n  ));
\n\nDROP POLICY IF EXISTS "Users can update job line items in their account" ON public.job_line_items;
\nCREATE POLICY "Users can update job line items in their account"\n  ON public.job_line_items FOR UPDATE TO authenticated\n  USING (account_id IN (\n    SELECT account_members.account_id FROM account_members\n    WHERE account_members.user_id = (select auth.uid())\n    AND account_members.is_active = true\n  ))\n  WITH CHECK (account_id IN (\n    SELECT account_members.account_id FROM account_members\n    WHERE account_members.user_id = (select auth.uid())\n    AND account_members.is_active = true\n  ));
\n\nDROP POLICY IF EXISTS "Users can delete job line items in their account" ON public.job_line_items;
\nCREATE POLICY "Users can delete job line items in their account"\n  ON public.job_line_items FOR DELETE TO authenticated\n  USING (account_id IN (\n    SELECT account_members.account_id FROM account_members\n    WHERE account_members.user_id = (select auth.uid())\n    AND account_members.is_active = true\n  ));
\n\n-- financial_exports\nDROP POLICY IF EXISTS "Account members can view financial exports" ON public.financial_exports;
\nCREATE POLICY "Account members can view financial exports"\n  ON public.financial_exports FOR SELECT TO authenticated\n  USING (EXISTS (\n    SELECT 1 FROM account_members\n    WHERE account_members.account_id = financial_exports.account_id\n    AND account_members.user_id = (select auth.uid())\n  ));
\n\nDROP POLICY IF EXISTS "Account members can create financial exports" ON public.financial_exports;
\nCREATE POLICY "Account members can create financial exports"\n  ON public.financial_exports FOR INSERT TO authenticated\n  WITH CHECK (\n    EXISTS (\n      SELECT 1 FROM account_members\n      WHERE account_members.account_id = financial_exports.account_id\n      AND account_members.user_id = (select auth.uid())\n    )\n    AND created_by = (select auth.uid())\n  );
\n\nDROP POLICY IF EXISTS "Export creators can delete their own exports" ON public.financial_exports;
\nCREATE POLICY "Export creators can delete their own exports"\n  ON public.financial_exports FOR DELETE TO authenticated\n  USING (created_by = (select auth.uid()));
\n\n-- mock_crew_profiles\nDROP POLICY IF EXISTS "Account members can view mock crew profiles" ON public.mock_crew_profiles;
\nCREATE POLICY "Account members can view mock crew profiles"\n  ON public.mock_crew_profiles FOR SELECT TO authenticated\n  USING (account_id IN (\n    SELECT am.account_id FROM account_members am\n    WHERE am.user_id = (select auth.uid())\n    AND am.is_active = true\n  ));
\n\nDROP POLICY IF EXISTS "Managers can create mock crew profiles" ON public.mock_crew_profiles;
\nCREATE POLICY "Managers can create mock crew profiles"\n  ON public.mock_crew_profiles FOR INSERT TO authenticated\n  WITH CHECK (is_user_account_manager(account_id, (select auth.uid())));
\n\nDROP POLICY IF EXISTS "Managers can update mock crew profiles" ON public.mock_crew_profiles;
\nCREATE POLICY "Managers can update mock crew profiles"\n  ON public.mock_crew_profiles FOR UPDATE TO authenticated\n  USING (is_user_account_manager(account_id, (select auth.uid())))\n  WITH CHECK (is_user_account_manager(account_id, (select auth.uid())));
\n\nDROP POLICY IF EXISTS "Managers can delete mock crew profiles" ON public.mock_crew_profiles;
\nCREATE POLICY "Managers can delete mock crew profiles"\n  ON public.mock_crew_profiles FOR DELETE TO authenticated\n  USING (is_user_account_manager(account_id, (select auth.uid())));
\n\n-- job_assignments (insert policy)\nDROP POLICY IF EXISTS "Managers can create job assignments" ON public.job_assignments;
\nCREATE POLICY "Managers can create job assignments"\n  ON public.job_assignments FOR INSERT TO authenticated\n  WITH CHECK (\n    is_user_account_manager(account_id, (select auth.uid()))\n    AND ((lead_id IS NULL) OR is_lead_in_account(lead_id, account_id))\n    AND ((job_schedule_id IS NULL) OR is_schedule_in_account(job_schedule_id, account_id))\n    AND (\n      (\n        (user_id IS NOT NULL) AND (mock_crew_profile_id IS NULL)\n        AND is_user_in_account(user_id, account_id)\n        AND ((job_schedule_id IS NULL) OR (NOT check_assignment_overlap(user_id, job_schedule_id, account_id)))\n      )\n      OR (\n        (user_id IS NULL) AND (mock_crew_profile_id IS NOT NULL)\n        AND is_mock_profile_in_account(mock_crew_profile_id, account_id)\n        AND ((job_schedule_id IS NULL) OR (NOT check_mock_assignment_overlap(mock_crew_profile_id, job_schedule_id, account_id)))\n      )\n    )\n  );
\n\n-- estimate_versions\nDROP POLICY IF EXISTS "Account members can view estimate versions" ON public.estimate_versions;
\nCREATE POLICY "Account members can view estimate versions"\n  ON public.estimate_versions FOR SELECT TO authenticated\n  USING (EXISTS (\n    SELECT 1 FROM account_members am\n    WHERE am.account_id = estimate_versions.account_id\n    AND am.user_id = (select auth.uid())\n    AND am.is_active = true\n  ));
\n\nDROP POLICY IF EXISTS "Account members can insert estimate versions" ON public.estimate_versions;
\nCREATE POLICY "Account members can insert estimate versions"\n  ON public.estimate_versions FOR INSERT TO authenticated\n  WITH CHECK (EXISTS (\n    SELECT 1 FROM account_members am\n    WHERE am.account_id = estimate_versions.account_id\n    AND am.user_id = (select auth.uid())\n    AND am.is_active = true\n  ));
\n\nDROP POLICY IF EXISTS "Account members can update estimate versions" ON public.estimate_versions;
\nCREATE POLICY "Account members can update estimate versions"\n  ON public.estimate_versions FOR UPDATE TO authenticated\n  USING (EXISTS (\n    SELECT 1 FROM account_members am\n    WHERE am.account_id = estimate_versions.account_id\n    AND am.user_id = (select auth.uid())\n    AND am.is_active = true\n  ))\n  WITH CHECK (EXISTS (\n    SELECT 1 FROM account_members am\n    WHERE am.account_id = estimate_versions.account_id\n    AND am.user_id = (select auth.uid())\n    AND am.is_active = true\n  ));
\n\nDROP POLICY IF EXISTS "Account members can delete estimate versions" ON public.estimate_versions;
\nCREATE POLICY "Account members can delete estimate versions"\n  ON public.estimate_versions FOR DELETE TO authenticated\n  USING (EXISTS (\n    SELECT 1 FROM account_members am\n    WHERE am.account_id = estimate_versions.account_id\n    AND am.user_id = (select auth.uid())\n    AND am.is_active = true\n  ));
\n\n-- account_members (insert, update, delete)\nDROP POLICY IF EXISTS "Managers can invite members" ON public.account_members;
\nCREATE POLICY "Managers can invite members"\n  ON public.account_members FOR INSERT TO authenticated\n  WITH CHECK (is_account_admin(account_id, (select auth.uid())));
\n\nDROP POLICY IF EXISTS "Managers can update members" ON public.account_members;
\nCREATE POLICY "Managers can update members"\n  ON public.account_members FOR UPDATE TO authenticated\n  USING (is_account_admin(account_id, (select auth.uid())))\n  WITH CHECK (is_account_admin(account_id, (select auth.uid())));
\n\nDROP POLICY IF EXISTS "Managers can remove members" ON public.account_members;
\nCREATE POLICY "Managers can remove members"\n  ON public.account_members FOR DELETE TO authenticated\n  USING (is_account_admin(account_id, (select auth.uid())));
\n\n-- ============================================================\n-- 3. Fix function search paths\n-- ============================================================\n\nCREATE OR REPLACE FUNCTION public.is_user_account_manager(p_account_id uuid, p_user_id uuid)\nRETURNS boolean\nLANGUAGE sql\nSTABLE\nSECURITY DEFINER\nSET search_path = ''\nAS $$\nSELECT EXISTS (\n  SELECT 1\n  FROM public.account_members\n  WHERE account_id = p_account_id\n  AND user_id = p_user_id\n  AND is_active = true\n  AND role IN ('owner', 'admin', 'crew_lead', 'sales')\n);
\n$$;
\n\nCREATE OR REPLACE FUNCTION public.set_estimate_versions_updated_at()\nRETURNS trigger\nLANGUAGE plpgsql\nVOLATILE\nSET search_path = ''\nAS $$\nBEGIN\n  NEW.updated_at := now();
\n  RETURN NEW;
\nEND;
\n$$;
\n\nCREATE OR REPLACE FUNCTION public.extract_mentioned_users(note_text text)\nRETURNS uuid[]\nLANGUAGE plpgsql\nIMMUTABLE\nSET search_path = ''\nAS $$\nDECLARE\n  user_ids uuid[];
\nBEGIN\n  SELECT array_agg(DISTINCT m[2]::uuid)\n  INTO user_ids\n  FROM regexp_matches(note_text, '@\\[([^\\]]+)\\]\\(([a-f0-9-]+)\\)', 'g') AS m\n  WHERE m[2] ~ '^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$';
\n\n  RETURN COALESCE(user_ids, ARRAY[]::uuid[]);
\nEND;
\n$$;
\n\nCREATE OR REPLACE FUNCTION public.is_mock_profile_in_account(p_mock_profile_id uuid, p_account_id uuid)\nRETURNS boolean\nLANGUAGE sql\nSTABLE\nSECURITY DEFINER\nSET search_path = ''\nAS $$\n  SELECT EXISTS (\n    SELECT 1\n    FROM public.mock_crew_profiles mcp\n    WHERE mcp.id = p_mock_profile_id\n    AND mcp.account_id = p_account_id\n  );
\n$$;
\n\nCREATE OR REPLACE FUNCTION public.check_assignment_overlap(p_user_id uuid, p_schedule_id uuid, p_account_id uuid)\nRETURNS boolean\nLANGUAGE sql\nSTABLE\nSECURITY DEFINER\nSET search_path = ''\nAS $$\n  SELECT CASE\n    WHEN p_user_id IS NULL THEN false\n    ELSE EXISTS (\n      SELECT 1\n      FROM public.job_assignments ja\n      JOIN public.job_schedules js1 ON ja.job_schedule_id = js1.id\n      JOIN public.job_schedules js2 ON js2.id = p_schedule_id\n      WHERE ja.user_id = p_user_id\n      AND ja.account_id = p_account_id\n      AND js1.scheduled_date = js2.scheduled_date\n      AND (\n        (js1.scheduled_time_start IS NULL OR js2.scheduled_time_start IS NULL)\n        OR (\n          js1.scheduled_time_start < js2.scheduled_time_end\n          AND js1.scheduled_time_end > js2.scheduled_time_start\n        )\n      )\n    )\n  END;
\n$$;
\n\nCREATE OR REPLACE FUNCTION public.check_mock_assignment_overlap(p_mock_profile_id uuid, p_schedule_id uuid, p_account_id uuid)\nRETURNS boolean\nLANGUAGE sql\nSTABLE\nSECURITY DEFINER\nSET search_path = ''\nAS $$\n  SELECT CASE\n    WHEN p_mock_profile_id IS NULL THEN false\n    ELSE EXISTS (\n      SELECT 1\n      FROM public.job_assignments ja\n      JOIN public.job_schedules js1 ON ja.job_schedule_id = js1.id\n      JOIN public.job_schedules js2 ON js2.id = p_schedule_id\n      WHERE ja.mock_crew_profile_id = p_mock_profile_id\n      AND ja.account_id = p_account_id\n      AND js1.scheduled_date = js2.scheduled_date\n      AND (\n        (js1.scheduled_time_start IS NULL OR js2.scheduled_time_start IS NULL)\n        OR (\n          js1.scheduled_time_start < js2.scheduled_time_end\n          AND js1.scheduled_time_end > js2.scheduled_time_start\n        )\n      )\n    )\n  END;
\n$$;
\n\n-- ============================================================\n-- 4. Drop unused indexes\n-- ============================================================\n\nDROP INDEX IF EXISTS idx_recurring_jobs_customer_id;
\nDROP INDEX IF EXISTS idx_stripe_connect_accounts_account_id;
\nDROP INDEX IF EXISTS idx_supply_order_items_account_id;
\nDROP INDEX IF EXISTS idx_supply_order_items_material_item_id;
\nDROP INDEX IF EXISTS idx_supply_order_items_supply_order_id;
\nDROP INDEX IF EXISTS idx_supply_orders_material_list_id;
\nDROP INDEX IF EXISTS idx_webhook_events_invoice_id;
\nDROP INDEX IF EXISTS idx_webhook_events_payment_id;
\nDROP INDEX IF EXISTS idx_leads_new_status;
\nDROP INDEX IF EXISTS idx_estimate_line_items_original_account_id;
\nDROP INDEX IF EXISTS idx_estimate_versions_account_id;
\nDROP INDEX IF EXISTS idx_mock_crew_profiles_account_id;
\nDROP INDEX IF EXISTS idx_account_members_invited_by;
\nDROP INDEX IF EXISTS idx_api_keys_account_id;
\nDROP INDEX IF EXISTS idx_customers_account_id;
\nDROP INDEX IF EXISTS idx_customers_lead_id;
\nDROP INDEX IF EXISTS idx_days_off_created_by;
\nDROP INDEX IF EXISTS idx_email_digest_log_account_id;
\nDROP INDEX IF EXISTS idx_email_digest_log_user_id;
\nDROP INDEX IF EXISTS idx_estimate_change_orders_account_id;
\nDROP INDEX IF EXISTS idx_estimate_change_orders_changed_by;
\nDROP INDEX IF EXISTS idx_estimate_line_items_account_id;
\nDROP INDEX IF EXISTS idx_job_assignments_assigned_by;
\nDROP INDEX IF EXISTS idx_interactions_account_id;
\nDROP INDEX IF EXISTS idx_invoice_line_items_account_id;
\nDROP INDEX IF EXISTS idx_invoice_line_items_invoice_id;
\nDROP INDEX IF EXISTS idx_job_schedules_created_by;
\nDROP INDEX IF EXISTS idx_lead_photos_account_id;
\nDROP INDEX IF EXISTS idx_lead_photos_uploaded_by;
\nDROP INDEX IF EXISTS idx_lead_qualifications_account_id;
\nDROP INDEX IF EXISTS idx_material_items_account_id;
\nDROP INDEX IF EXISTS idx_material_items_material_list_id;
\nDROP INDEX IF EXISTS idx_payments_invoice_id;
\nDROP INDEX IF EXISTS idx_quick_estimates_account_id;
\nDROP INDEX IF EXISTS idx_recurring_jobs_created_by;
\n;
