/*\n  # Enforce One-to-One Relationship Between Jobs and Estimates\n  \n  ## Overview\n  Establishes a one-to-one relationship between jobs (leads) and estimates:\n  - Each job must have exactly one estimate\n  - Each estimate must be linked to exactly one job\n  - Estimates are automatically created when jobs are created\n  \n  ## Changes\n  1. Rename `lead_id` to `job_id` for clarity (since jobs are stored in leads table)\n  2. Make `job_id` required (NOT NULL)\n  3. Add unique constraint to ensure one estimate per job\n  4. Create trigger to auto-create estimate when job is created\n  5. Make `account_id` required and add foreign key\n  \n  ## Data Migration\n  - Delete any orphaned estimates (estimates without a job)\n  - For jobs without estimates, a draft estimate will be created automatically\n  \n  ## Security\n  - RLS policies remain unchanged\n  - Estimates inherit account_id from their associated job\n*/\n\n-- First, let's see if there are any estimates without a job\n-- If there are, we'll need to decide what to do with them\n-- For now, we'll delete them since they're orphaned\nDO $$\nBEGIN\n  DELETE FROM public.estimates WHERE lead_id IS NULL;
\n  RAISE NOTICE 'Deleted orphaned estimates without a job';
\nEND $$;
\n\n-- Rename lead_id to job_id for clarity (even though it references leads table)\nALTER TABLE public.estimates \n  RENAME COLUMN lead_id TO job_id;
\n\n-- Make job_id required\nALTER TABLE public.estimates \n  ALTER COLUMN job_id SET NOT NULL;
\n\n-- Add unique constraint to enforce one estimate per job\nALTER TABLE public.estimates \n  DROP CONSTRAINT IF EXISTS estimates_job_id_unique;
\n\nALTER TABLE public.estimates \n  ADD CONSTRAINT estimates_job_id_unique UNIQUE (job_id);
\n\n-- Make account_id required and ensure it has a foreign key\nALTER TABLE public.estimates \n  ALTER COLUMN account_id SET NOT NULL;
\n\n-- Add foreign key for account_id if it doesn't exist\nDO $$\nBEGIN\n  IF NOT EXISTS (\n    SELECT 1 FROM information_schema.table_constraints \n    WHERE constraint_name = 'estimates_account_id_fkey' \n    AND table_name = 'estimates'\n  ) THEN\n    ALTER TABLE public.estimates \n      ADD CONSTRAINT estimates_account_id_fkey \n      FOREIGN KEY (account_id) REFERENCES public.accounts(id) ON DELETE CASCADE;
\n  END IF;
\nEND $$;
\n\n-- Create a function to automatically create an estimate when a job is created\nCREATE OR REPLACE FUNCTION public.auto_create_estimate_for_job()\nRETURNS TRIGGER\nLANGUAGE plpgsql\nSECURITY DEFINER\nSET search_path = public\nAS $$\nBEGIN\n  -- Only create estimate for actual jobs (not leads)\n  IF NEW.status IN ('scheduled', 'in_progress', 'completed', 'won', 'invoiced', 'paid') \n     AND NEW.approval_status = 'approved' THEN\n    \n    -- Check if estimate already exists for this job\n    IF NOT EXISTS (SELECT 1 FROM public.estimates WHERE job_id = NEW.id) THEN\n      -- Create a draft estimate linked to the job\n      INSERT INTO public.estimates (\n        customer_id,\n        job_id,\n        account_id,\n        subtotal,\n        tax_rate,\n        tax,\n        discount,\n        total,\n        status,\n        created_by,\n        notes\n      ) VALUES (\n        NEW.customer_id,\n        NEW.id,\n        NEW.account_id,\n        0,\n        0.08,\n        0,\n        0,\n        0,\n        'draft',\n        NEW.created_by,\n        'Auto-generated estimate for ' || NEW.name\n      );
\n      \n      RAISE NOTICE 'Auto-created estimate for job %', NEW.id;
\n    END IF;
\n  END IF;
\n  \n  RETURN NEW;
\nEND;
\n$$;
\n\n-- Create trigger to auto-create estimate when job is created\nDROP TRIGGER IF EXISTS trigger_auto_create_estimate ON public.leads;
\n\nCREATE TRIGGER trigger_auto_create_estimate\n  AFTER INSERT ON public.leads\n  FOR EACH ROW\n  EXECUTE FUNCTION public.auto_create_estimate_for_job();
\n\n-- Also create estimates for existing jobs that don't have one\nDO $$\nDECLARE\n  job_record RECORD;
\nBEGIN\n  FOR job_record IN \n    SELECT l.id, l.name, l.customer_id, l.account_id, l.created_by\n    FROM public.leads l\n    LEFT JOIN public.estimates e ON e.job_id = l.id\n    WHERE l.status IN ('scheduled', 'in_progress', 'completed', 'won', 'invoiced', 'paid')\n      AND l.approval_status = 'approved'\n      AND e.id IS NULL\n  LOOP\n    INSERT INTO public.estimates (\n      customer_id,\n      job_id,\n      account_id,\n      subtotal,\n      tax_rate,\n      tax,\n      discount,\n      total,\n      status,\n      created_by,\n      notes\n    ) VALUES (\n      job_record.customer_id,\n      job_record.id,\n      job_record.account_id,\n      0,\n      0.08,\n      0,\n      0,\n      0,\n      'draft',\n      job_record.created_by,\n      'Auto-generated estimate for ' || job_record.name\n    );
\n    \n    RAISE NOTICE 'Created estimate for existing job %', job_record.id;
\n  END LOOP;
\nEND $$;
\n;
