/*\n  # Fix Account Members and RLS Access Issues\n  \n  ## Summary\n  Fixes issues where users cannot create or view leads due to missing or incorrect\n  account_members entries and overly restrictive RLS policies.\n  \n  ## Changes\n  \n  1. **Ensure All Users Have Account Members Entries**\n     - Finds users with profiles but no account_members entry\n     - Creates account_members entries for them with 'sales' role by default\n     - Associates them with their first account (or creates one if needed)\n  \n  2. **RLS Policy Improvements**\n     - No policy changes needed, just data fixes\n  \n  ## Security\n  - Maintains proper access control through account_members\n  - All users are associated with an account\n  - Default role is 'sales' which has appropriate permissions\n*/\n\n-- Step 1: Find users with profiles but no account_members entry and fix them\nDO $$\nDECLARE\n  user_record RECORD;
\n  v_account_id uuid;
\nBEGIN\n  -- Loop through users who have profiles but no account_members entry\n  FOR user_record IN \n    SELECT p.user_id, p.email, p.full_name\n    FROM profiles p\n    WHERE NOT EXISTS (\n      SELECT 1 FROM account_members am\n      WHERE am.user_id = p.user_id\n    )\n  LOOP\n    RAISE NOTICE 'Found user without account: % (%)', user_record.full_name, user_record.email;
\n    \n    -- Check if there's an account created by this user\n    SELECT id INTO v_account_id\n    FROM accounts\n    ORDER BY created_at ASC\n    LIMIT 1;
\n    \n    -- If no accounts exist at all, create one\n    IF v_account_id IS NULL THEN\n      INSERT INTO accounts (company_name, company_email)\n      VALUES (\n        COALESCE(user_record.full_name, user_record.email, 'My Company'),\n        user_record.email\n      )\n      RETURNING id INTO v_account_id;
\n      \n      RAISE NOTICE 'Created new account: %', v_account_id;
\n    END IF;
\n    \n    -- Create account_members entry\n    INSERT INTO account_members (account_id, user_id, role, is_active)\n    VALUES (v_account_id, user_record.user_id, 'sales', true);
\n    \n    RAISE NOTICE 'Added user % to account % with role sales', user_record.email, v_account_id;
\n  END LOOP;
\nEND $$;
\n\n-- Step 2: Update any leads that don't have an account_id\nUPDATE leads\nSET account_id = (\n  SELECT am.account_id\n  FROM account_members am\n  WHERE am.user_id = leads.created_by\n    AND am.is_active = true\n  ORDER BY am.created_at ASC\n  LIMIT 1\n)\nWHERE account_id IS NULL;
\n\n-- Step 3: Verify no orphaned data remains\nDO $$\nDECLARE\n  orphaned_leads_count integer;
\n  orphaned_users_count integer;
\nBEGIN\n  -- Check for leads without account_id\n  SELECT COUNT(*) INTO orphaned_leads_count\n  FROM leads\n  WHERE account_id IS NULL;
\n  \n  IF orphaned_leads_count > 0 THEN\n    RAISE WARNING 'Found % leads without account_id', orphaned_leads_count;
\n  END IF;
\n  \n  -- Check for users without account_members\n  SELECT COUNT(*) INTO orphaned_users_count\n  FROM profiles p\n  WHERE NOT EXISTS (\n    SELECT 1 FROM account_members am\n    WHERE am.user_id = p.user_id\n  );
\n  \n  IF orphaned_users_count > 0 THEN\n    RAISE WARNING 'Found % users without account_members entries', orphaned_users_count;
\n  ELSE\n    RAISE NOTICE 'All users have account_members entries';
\n  END IF;
\nEND $$;
\n;
