/*\n  # Fix security issues: indexes, policies, and view\n\n  1. New Indexes (missing FK coverage)\n    - `estimates.recurring_job_id` - covers `estimates_recurring_job_id_fkey`\n    - `job_checklist_items.account_id` - covers `job_checklist_items_account_id_fkey`\n    - `sms_notification_log.user_id` - covers `sms_notification_log_user_id_fkey`\n\n  2. Dropped Unused Indexes\n    - 35 indexes across multiple tables that have never been used,\n      reducing write overhead and storage waste\n\n  3. Policy Changes\n    - Consolidated two permissive SELECT policies on `account_members`\n      into a single policy to avoid ambiguous multi-policy evaluation.\n      Combined logic: user can view their own membership OR members\n      in accounts they belong to.\n\n  4. View Changes\n    - Recreated `account_members_with_profiles` with `security_invoker = true`\n      so that RLS on the underlying tables is respected when querying\n      through the view, instead of bypassing RLS as the view owner.\n*/\n\n-- 1. Add missing FK indexes\nCREATE INDEX IF NOT EXISTS idx_estimates_recurring_job_id\n  ON public.estimates (recurring_job_id);
\n\nCREATE INDEX IF NOT EXISTS idx_job_checklist_items_account_id\n  ON public.job_checklist_items (account_id);
\n\nCREATE INDEX IF NOT EXISTS idx_sms_notification_log_user_id\n  ON public.sms_notification_log (user_id);
\n\n-- 2. Drop unused indexes\nDROP INDEX IF EXISTS public.idx_stripe_connect_accounts_account_id;
\nDROP INDEX IF EXISTS public.idx_supply_order_items_account_id;
\nDROP INDEX IF EXISTS public.idx_supply_order_items_material_item_id;
\nDROP INDEX IF EXISTS public.idx_supply_order_items_supply_order_id;
\nDROP INDEX IF EXISTS public.idx_supply_orders_material_list_id;
\nDROP INDEX IF EXISTS public.idx_webhook_events_invoice_id;
\nDROP INDEX IF EXISTS public.idx_webhook_events_payment_id;
\nDROP INDEX IF EXISTS public.idx_estimate_change_orders_changed_by;
\nDROP INDEX IF EXISTS public.idx_estimate_line_items_account_id;
\nDROP INDEX IF EXISTS public.idx_estimate_line_items_original_line_item_id;
\nDROP INDEX IF EXISTS public.idx_estimates_created_by;
\nDROP INDEX IF EXISTS public.idx_account_members_invited_by;
\nDROP INDEX IF EXISTS public.idx_api_keys_account_id;
\nDROP INDEX IF EXISTS public.idx_customers_account_id;
\nDROP INDEX IF EXISTS public.idx_customers_lead_id;
\nDROP INDEX IF EXISTS public.idx_days_off_created_by;
\nDROP INDEX IF EXISTS public.idx_email_digest_log_account_id;
\nDROP INDEX IF EXISTS public.idx_email_digest_log_user_id;
\nDROP INDEX IF EXISTS public.idx_estimate_change_orders_account_id;
\nDROP INDEX IF EXISTS public.idx_interactions_account_id;
\nDROP INDEX IF EXISTS public.idx_invoice_line_items_account_id;
\nDROP INDEX IF EXISTS public.idx_invoice_line_items_invoice_id;
\nDROP INDEX IF EXISTS public.idx_job_assignments_account_id;
\nDROP INDEX IF EXISTS public.idx_job_assignments_assigned_by;
\nDROP INDEX IF EXISTS public.idx_job_schedules_created_by;
\nDROP INDEX IF EXISTS public.idx_lead_photos_account_id;
\nDROP INDEX IF EXISTS public.idx_lead_photos_uploaded_by;
\nDROP INDEX IF EXISTS public.idx_lead_qualifications_account_id;
\nDROP INDEX IF EXISTS public.idx_leads_customer_id;
\nDROP INDEX IF EXISTS public.idx_material_items_account_id;
\nDROP INDEX IF EXISTS public.idx_material_items_material_list_id;
\nDROP INDEX IF EXISTS public.idx_payments_invoice_id;
\nDROP INDEX IF EXISTS public.idx_pricing_rules_account_id;
\nDROP INDEX IF EXISTS public.idx_quick_estimates_account_id;
\nDROP INDEX IF EXISTS public.idx_recurring_jobs_created_by;
\nDROP INDEX IF EXISTS public.idx_recurring_jobs_customer_id;
\n\n-- 3. Consolidate multiple permissive SELECT policies on account_members\nDROP POLICY IF EXISTS "Users can view members in their accounts" ON public.account_members;
\nDROP POLICY IF EXISTS "Users can view their own membership" ON public.account_members;
\n\nCREATE POLICY "Users can view own or account memberships"\n  ON public.account_members\n  FOR SELECT\n  TO authenticated\n  USING (\n    auth.uid() = user_id\n    OR is_account_member(account_id, auth.uid())\n  );
\n\n-- 4. Recreate view with security_invoker to respect RLS\nDROP VIEW IF EXISTS public.account_members_with_profiles;
\n\nCREATE VIEW public.account_members_with_profiles\n  WITH (security_invoker = true)\nAS\n  SELECT\n    am.id,\n    am.account_id,\n    am.user_id,\n    am.role,\n    am.invited_by,\n    am.invited_at,\n    am.joined_at,\n    am.is_active,\n    p.full_name,\n    p.email,\n    p.phone,\n    p.avatar_url\n  FROM public.account_members am\n  LEFT JOIN public.profiles p ON am.user_id = p.user_id;
\n;
