/*\n  # Add Multi-User Account Support\n  \n  ## Overview\n  This migration transforms the database from single-user to multi-user account architecture.\n  Users can now belong to multiple accounts with different roles, and all resources are\n  scoped to accounts instead of individual users.\n  \n  ## New Tables\n  \n  ### accounts\n  Stores company/organization information:\n  - `id` (uuid, primary key)\n  - `company_name` (text, required) - Business name\n  - `company_email` (text) - Primary business email\n  - `company_phone` (text) - Business phone number\n  - `company_address` (text) - Physical address\n  - `billing_email` (text) - Email for billing\n  - `website` (text) - Company website\n  - `logo_url` (text) - URL to company logo\n  - `settings` (jsonb) - Account-level settings\n  - `created_at`, `updated_at` (timestamptz)\n  \n  ### account_members\n  Links users to accounts with roles (many-to-many):\n  - `id` (uuid, primary key)\n  - `account_id` (uuid, FK to accounts) - The account\n  - `user_id` (uuid, FK to auth.users) - The user\n  - `role` (app_role enum) - User's role in this account\n  - `invited_by` (uuid, FK to auth.users) - Who invited them\n  - `invited_at` (timestamptz) - When invited\n  - `joined_at` (timestamptz) - When they joined\n  - `is_active` (boolean) - Whether membership is active\n  - `created_at`, `updated_at` (timestamptz)\n  \n  ## Modified Tables\n  \n  All resource tables now have `account_id`:\n  - leads\n  - customers\n  - estimates\n  - invoices\n  - payments\n  - material_lists\n  - supply_orders\n  - quick_estimates\n  - pricing_rules\n  - api_keys\n  - stripe_connect_accounts\n  - lead_source_connections\n  \n  ## Data Migration\n  \n  For existing data:\n  1. Create one account per existing user\n  2. Add that user as owner of their account\n  3. Link all their resources to their account\n  \n  ## Security\n  \n  - Enable RLS on new tables\n  - Update all RLS policies to check account membership\n  - Users can only access data from accounts they belong to\n  \n  ## Notes\n  \n  - Maintains backward compatibility by auto-creating accounts for existing users\n  - The `created_by` fields remain for audit purposes\n  - Users can switch between accounts in the frontend\n*/\n\n-- Create accounts table\nCREATE TABLE IF NOT EXISTS public.accounts (\n  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),\n  company_name text NOT NULL,\n  company_email text,\n  company_phone text,\n  company_address text,\n  billing_email text,\n  website text,\n  logo_url text,\n  settings jsonb DEFAULT '{}'::jsonb,\n  created_at timestamptz DEFAULT now() NOT NULL,\n  updated_at timestamptz DEFAULT now() NOT NULL\n);
\n\n-- Create account_members table\nCREATE TABLE IF NOT EXISTS public.account_members (\n  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),\n  account_id uuid NOT NULL REFERENCES public.accounts(id) ON DELETE CASCADE,\n  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,\n  role public.app_role NOT NULL DEFAULT 'admin',\n  invited_by uuid REFERENCES auth.users(id),\n  invited_at timestamptz DEFAULT now(),\n  joined_at timestamptz DEFAULT now(),\n  is_active boolean DEFAULT true NOT NULL,\n  created_at timestamptz DEFAULT now() NOT NULL,\n  updated_at timestamptz DEFAULT now() NOT NULL,\n  UNIQUE(account_id, user_id)\n);
\n\n-- Add indexes for performance\nCREATE INDEX IF NOT EXISTS idx_account_members_account_id ON public.account_members(account_id);
\nCREATE INDEX IF NOT EXISTS idx_account_members_user_id ON public.account_members(user_id);
\nCREATE INDEX IF NOT EXISTS idx_account_members_active ON public.account_members(account_id, user_id) WHERE is_active = true;
\n\n-- Add account_id columns to resource tables\nALTER TABLE public.leads ADD COLUMN IF NOT EXISTS account_id uuid REFERENCES public.accounts(id);
\nALTER TABLE public.customers ADD COLUMN IF NOT EXISTS account_id uuid REFERENCES public.accounts(id);
\nALTER TABLE public.estimates ADD COLUMN IF NOT EXISTS account_id uuid REFERENCES public.accounts(id);
\nALTER TABLE public.invoices ADD COLUMN IF NOT EXISTS account_id uuid REFERENCES public.accounts(id);
\nALTER TABLE public.payments ADD COLUMN IF NOT EXISTS account_id uuid REFERENCES public.accounts(id);
\nALTER TABLE public.material_lists ADD COLUMN IF NOT EXISTS account_id uuid REFERENCES public.accounts(id);
\nALTER TABLE public.supply_orders ADD COLUMN IF NOT EXISTS account_id uuid REFERENCES public.accounts(id);
\nALTER TABLE public.quick_estimates ADD COLUMN IF NOT EXISTS account_id uuid REFERENCES public.accounts(id);
\nALTER TABLE public.pricing_rules ADD COLUMN IF NOT EXISTS account_id uuid REFERENCES public.accounts(id);
\nALTER TABLE public.api_keys ADD COLUMN IF NOT EXISTS account_id uuid REFERENCES public.accounts(id);
\nALTER TABLE public.stripe_connect_accounts ADD COLUMN IF NOT EXISTS account_id uuid REFERENCES public.accounts(id);
\nALTER TABLE public.lead_source_connections ADD COLUMN IF NOT EXISTS account_id uuid REFERENCES public.accounts(id);
\nALTER TABLE public.interactions ADD COLUMN IF NOT EXISTS account_id uuid REFERENCES public.accounts(id);
\nALTER TABLE public.estimate_line_items ADD COLUMN IF NOT EXISTS account_id uuid REFERENCES public.accounts(id);
\nALTER TABLE public.invoice_line_items ADD COLUMN IF NOT EXISTS account_id uuid REFERENCES public.accounts(id);
\nALTER TABLE public.material_items ADD COLUMN IF NOT EXISTS account_id uuid REFERENCES public.accounts(id);
\nALTER TABLE public.supply_order_items ADD COLUMN IF NOT EXISTS account_id uuid REFERENCES public.accounts(id);
\nALTER TABLE public.lead_qualifications ADD COLUMN IF NOT EXISTS account_id uuid REFERENCES public.accounts(id);
\n\n-- Add indexes for account_id lookups\nCREATE INDEX IF NOT EXISTS idx_leads_account_id ON public.leads(account_id);
\nCREATE INDEX IF NOT EXISTS idx_customers_account_id ON public.customers(account_id);
\nCREATE INDEX IF NOT EXISTS idx_estimates_account_id ON public.estimates(account_id);
\nCREATE INDEX IF NOT EXISTS idx_invoices_account_id ON public.invoices(account_id);
\nCREATE INDEX IF NOT EXISTS idx_payments_account_id ON public.payments(account_id);
\nCREATE INDEX IF NOT EXISTS idx_material_lists_account_id ON public.material_lists(account_id);
\nCREATE INDEX IF NOT EXISTS idx_supply_orders_account_id ON public.supply_orders(account_id);
\n\n-- Migrate existing data: Create one account per user and link their data\nDO $$\nDECLARE\n  v_user RECORD;
\n  v_account_id uuid;
\n  v_profile RECORD;
\nBEGIN\n  -- For each user that has created resources\n  FOR v_user IN \n    SELECT DISTINCT u.id, u.email\n    FROM auth.users u\n    WHERE EXISTS (\n      SELECT 1 FROM public.leads WHERE created_by = u.id\n      UNION\n      SELECT 1 FROM public.customers WHERE created_by = u.id\n      UNION\n      SELECT 1 FROM public.estimates WHERE created_by = u.id\n    )\n  LOOP\n    -- Get profile info for company name\n    SELECT * INTO v_profile FROM public.profiles WHERE user_id = v_user.id;
\n    \n    -- Create account for this user\n    INSERT INTO public.accounts (company_name, company_email)\n    VALUES (\n      COALESCE(v_profile.full_name, v_user.email, 'My Company'),\n      v_user.email\n    )\n    RETURNING id INTO v_account_id;
\n    \n    -- Add user as owner of their account\n    INSERT INTO public.account_members (account_id, user_id, role, is_active)\n    VALUES (v_account_id, v_user.id, 'owner', true);
\n    \n    -- Link all their resources to their account\n    UPDATE public.leads SET account_id = v_account_id WHERE created_by = v_user.id AND account_id IS NULL;
\n    UPDATE public.customers SET account_id = v_account_id WHERE created_by = v_user.id AND account_id IS NULL;
\n    UPDATE public.estimates SET account_id = v_account_id WHERE created_by = v_user.id AND account_id IS NULL;
\n    UPDATE public.invoices SET account_id = v_account_id WHERE created_by = v_user.id AND account_id IS NULL;
\n    UPDATE public.payments SET account_id = v_account_id WHERE processed_by = v_user.id AND account_id IS NULL;
\n    UPDATE public.material_lists SET account_id = v_account_id WHERE created_by = v_user.id AND account_id IS NULL;
\n    UPDATE public.supply_orders SET account_id = v_account_id WHERE created_by = v_user.id AND account_id IS NULL;
\n    UPDATE public.quick_estimates SET account_id = v_account_id WHERE created_by = v_user.id AND account_id IS NULL;
\n    UPDATE public.pricing_rules SET account_id = v_account_id WHERE user_id = v_user.id AND account_id IS NULL;
\n    UPDATE public.api_keys SET account_id = v_account_id WHERE user_id = v_user.id AND account_id IS NULL;
\n    UPDATE public.stripe_connect_accounts SET account_id = v_account_id WHERE user_id = v_user.id AND account_id IS NULL;
\n    UPDATE public.lead_source_connections SET account_id = v_account_id WHERE user_id = v_user.id AND account_id IS NULL;
\n    \n    -- Link related records through joins\n    UPDATE public.interactions SET account_id = v_account_id \n    WHERE lead_id IN (SELECT id FROM public.leads WHERE account_id = v_account_id) AND account_id IS NULL;
\n    \n    UPDATE public.estimate_line_items SET account_id = v_account_id \n    WHERE estimate_id IN (SELECT id FROM public.estimates WHERE account_id = v_account_id) AND account_id IS NULL;
\n    \n    UPDATE public.invoice_line_items SET account_id = v_account_id \n    WHERE invoice_id IN (SELECT id FROM public.invoices WHERE account_id = v_account_id) AND account_id IS NULL;
\n    \n    UPDATE public.material_items SET account_id = v_account_id \n    WHERE material_list_id IN (SELECT id FROM public.material_lists WHERE account_id = v_account_id) AND account_id IS NULL;
\n    \n    UPDATE public.supply_order_items SET account_id = v_account_id \n    WHERE supply_order_id IN (SELECT id FROM public.supply_orders WHERE account_id = v_account_id) AND account_id IS NULL;
\n    \n    UPDATE public.lead_qualifications SET account_id = v_account_id \n    WHERE lead_id IN (SELECT id FROM public.leads WHERE account_id = v_account_id) AND account_id IS NULL;
\n  END LOOP;
\nEND $$;
\n\n-- Add updated_at trigger to accounts\nDROP TRIGGER IF EXISTS update_accounts_updated_at ON public.accounts;
\nCREATE TRIGGER update_accounts_updated_at\n  BEFORE UPDATE ON public.accounts\n  FOR EACH ROW\n  EXECUTE FUNCTION public.update_updated_at_column();
\n\n-- Add updated_at trigger to account_members\nDROP TRIGGER IF EXISTS update_account_members_updated_at ON public.account_members;
\nCREATE TRIGGER update_account_members_updated_at\n  BEFORE UPDATE ON public.account_members\n  FOR EACH ROW\n  EXECUTE FUNCTION public.update_updated_at_column();
\n\n-- Enable RLS on new tables\nALTER TABLE public.accounts ENABLE ROW LEVEL SECURITY;
\nALTER TABLE public.account_members ENABLE ROW LEVEL SECURITY;
\n\n-- RLS Policies for accounts table\nCREATE POLICY "Users can view their own accounts"\n  ON public.accounts FOR SELECT\n  TO authenticated\n  USING (\n    EXISTS (\n      SELECT 1 FROM public.account_members\n      WHERE account_members.account_id = accounts.id\n      AND account_members.user_id = auth.uid()\n      AND account_members.is_active = true\n    )\n  );
\n\nCREATE POLICY "Account owners and admins can update accounts"\n  ON public.accounts FOR UPDATE\n  TO authenticated\n  USING (\n    EXISTS (\n      SELECT 1 FROM public.account_members\n      WHERE account_members.account_id = accounts.id\n      AND account_members.user_id = auth.uid()\n      AND account_members.is_active = true\n      AND account_members.role IN ('owner', 'admin')\n    )\n  )\n  WITH CHECK (\n    EXISTS (\n      SELECT 1 FROM public.account_members\n      WHERE account_members.account_id = accounts.id\n      AND account_members.user_id = auth.uid()\n      AND account_members.is_active = true\n      AND account_members.role IN ('owner', 'admin')\n    )\n  );
\n\nCREATE POLICY "Account owners can delete accounts"\n  ON public.accounts FOR DELETE\n  TO authenticated\n  USING (\n    EXISTS (\n      SELECT 1 FROM public.account_members\n      WHERE account_members.account_id = accounts.id\n      AND account_members.user_id = auth.uid()\n      AND account_members.is_active = true\n      AND account_members.role = 'owner'\n    )\n  );
\n\n-- RLS Policies for account_members table\nCREATE POLICY "Users can view members of their accounts"\n  ON public.account_members FOR SELECT\n  TO authenticated\n  USING (\n    EXISTS (\n      SELECT 1 FROM public.account_members AS am\n      WHERE am.account_id = account_members.account_id\n      AND am.user_id = auth.uid()\n      AND am.is_active = true\n    )\n  );
\n\nCREATE POLICY "Account owners and admins can invite members"\n  ON public.account_members FOR INSERT\n  TO authenticated\n  WITH CHECK (\n    EXISTS (\n      SELECT 1 FROM public.account_members AS am\n      WHERE am.account_id = account_members.account_id\n      AND am.user_id = auth.uid()\n      AND am.is_active = true\n      AND am.role IN ('owner', 'admin')\n    )\n  );
\n\nCREATE POLICY "Account owners and admins can update members"\n  ON public.account_members FOR UPDATE\n  TO authenticated\n  USING (\n    EXISTS (\n      SELECT 1 FROM public.account_members AS am\n      WHERE am.account_id = account_members.account_id\n      AND am.user_id = auth.uid()\n      AND am.is_active = true\n      AND am.role IN ('owner', 'admin')\n    )\n  )\n  WITH CHECK (\n    EXISTS (\n      SELECT 1 FROM public.account_members AS am\n      WHERE am.account_id = account_members.account_id\n      AND am.user_id = auth.uid()\n      AND am.is_active = true\n      AND am.role IN ('owner', 'admin')\n    )\n  );
\n\nCREATE POLICY "Account owners and admins can remove members"\n  ON public.account_members FOR DELETE\n  TO authenticated\n  USING (\n    EXISTS (\n      SELECT 1 FROM public.account_members AS am\n      WHERE am.account_id = account_members.account_id\n      AND am.user_id = auth.uid()\n      AND am.is_active = true\n      AND am.role IN ('owner', 'admin')\n    )\n  );
\n\n-- Helper function to get user's accounts\nCREATE OR REPLACE FUNCTION public.get_user_accounts(user_id_param uuid DEFAULT auth.uid())\nRETURNS TABLE (\n  account_id uuid,\n  company_name text,\n  role public.app_role,\n  is_active boolean\n)\nLANGUAGE sql\nSTABLE\nSECURITY DEFINER\nSET search_path TO 'public'\nAS $$\n  SELECT \n    a.id AS account_id,\n    a.company_name,\n    am.role,\n    am.is_active\n  FROM public.accounts a\n  INNER JOIN public.account_members am ON am.account_id = a.id\n  WHERE am.user_id = user_id_param\n  AND am.is_active = true\n  ORDER BY am.created_at ASC;
\n$$;
\n\n-- Helper function to check if user is member of account\nCREATE OR REPLACE FUNCTION public.is_account_member(\n  account_id_param uuid,\n  user_id_param uuid DEFAULT auth.uid()\n)\nRETURNS boolean\nLANGUAGE sql\nSTABLE\nSECURITY DEFINER\nSET search_path TO 'public'\nAS $$\n  SELECT EXISTS (\n    SELECT 1\n    FROM public.account_members\n    WHERE account_id = account_id_param\n    AND user_id = user_id_param\n    AND is_active = true\n  );
\n$$;
\n\n-- Helper function to get user's role in account\nCREATE OR REPLACE FUNCTION public.get_account_role(\n  account_id_param uuid,\n  user_id_param uuid DEFAULT auth.uid()\n)\nRETURNS public.app_role\nLANGUAGE sql\nSTABLE\nSECURITY DEFINER\nSET search_path TO 'public'\nAS $$\n  SELECT role\n  FROM public.account_members\n  WHERE account_id = account_id_param\n  AND user_id = user_id_param\n  AND is_active = true\n  LIMIT 1;
\n$$;
\n\n-- Update handle_new_user to create account and add user as owner\nCREATE OR REPLACE FUNCTION public.handle_new_user()\nRETURNS trigger\nLANGUAGE plpgsql\nSECURITY DEFINER\nSET search_path TO 'public'\nAS $$\nDECLARE\n  v_account_id uuid;
\nBEGIN\n  -- Create profile\n  INSERT INTO public.profiles (user_id, full_name, email)\n  VALUES (\n    NEW.id,\n    COALESCE(NEW.raw_user_meta_data ->> 'full_name', NEW.raw_user_meta_data ->> 'name'),\n    NEW.email\n  );
\n  \n  -- Create default account for new user\n  INSERT INTO public.accounts (company_name, company_email)\n  VALUES (\n    COALESCE(NEW.raw_user_meta_data ->> 'full_name', NEW.raw_user_meta_data ->> 'name', NEW.email, 'My Company'),\n    NEW.email\n  )\n  RETURNING id INTO v_account_id;
\n  \n  -- Add user as owner of their new account\n  INSERT INTO public.account_members (account_id, user_id, role, is_active)\n  VALUES (v_account_id, NEW.id, 'owner', true);
\n  \n  RETURN NEW;
\nEND;
\n$$;
;
