/*\n  # Update handle_new_user for Company Join\n  \n  ## Overview\n  Updates the handle_new_user function to support both:\n  - Creating a new company (existing behavior)\n  - Joining an existing company via invite code (new behavior)\n  \n  ## Changes\n  \n  When a user signs up:\n  - If they have target_account_id in metadata, skip creating a new account\n  - Otherwise, create a new account with company_name from metadata\n  \n  ## Notes\n  \n  The account_members entry for joining users is created in the frontend\n  signUp function, so we don't duplicate that here.\n*/\n\nCREATE OR REPLACE FUNCTION public.handle_new_user()\nRETURNS trigger\nLANGUAGE plpgsql\nSECURITY DEFINER\nSET search_path TO 'public'\nAS $$\nDECLARE\n  v_account_id uuid;
\n  v_target_account_id text;
\n  v_company_name text;
\nBEGIN\n  -- Create profile\n  INSERT INTO public.profiles (user_id, full_name, email)\n  VALUES (\n    NEW.id,\n    COALESCE(NEW.raw_user_meta_data ->> 'full_name', NEW.raw_user_meta_data ->> 'name'),\n    NEW.email\n  );
\n  \n  -- Check if user is joining an existing account\n  v_target_account_id := NEW.raw_user_meta_data ->> 'target_account_id';
\n  \n  -- Only create a new account if user is not joining an existing one\n  IF v_target_account_id IS NULL THEN\n    -- Get company name from metadata or use default\n    v_company_name := COALESCE(\n      NEW.raw_user_meta_data ->> 'company_name',\n      NEW.raw_user_meta_data ->> 'full_name',\n      NEW.raw_user_meta_data ->> 'name',\n      NEW.email,\n      'My Company'\n    );
\n    \n    -- Create default account for new user\n    INSERT INTO public.accounts (company_name, company_email)\n    VALUES (v_company_name, NEW.email)\n    RETURNING id INTO v_account_id;
\n    \n    -- Add user as owner of their new account\n    INSERT INTO public.account_members (account_id, user_id, role, is_active)\n    VALUES (v_account_id, NEW.id, 'owner', true);
\n  END IF;
\n  \n  RETURN NEW;
\nEND;
\n$$;
;
