/*\n  # Fix estimate job completion requirements\n\n  1. Changes\n    - Update `try_convert_lead_to_job` function to check if all checklist items\n      are completed before auto-converting an estimate visit job to a regular job\n    - For estimate visit jobs (is_estimate_visit=true, status='job'), require:\n      - Accepted estimate AND\n      - At least one before photo AND  \n      - All checklist items completed\n    - This ensures the confirmation modal flow is respected\n\n  2. Important Notes\n    - Regular leads (not estimate visit jobs) are unaffected\n    - The frontend modal still provides the final confirmation\n    - This prevents premature conversion when photos are uploaded\n*/\n\nCREATE OR REPLACE FUNCTION try_convert_lead_to_job(p_lead_id uuid)\nRETURNS void\nLANGUAGE plpgsql\nSECURITY DEFINER\nSET search_path = public\nAS $$\nDECLARE\n  _lead record;
\n  _has_accepted_estimate boolean;
\n  _has_before_photos boolean;
\n  _all_checklist_complete boolean;
\n  _new_job_id uuid;
\nBEGIN\n  SELECT * INTO _lead FROM leads WHERE id = p_lead_id;
\n\n  IF _lead IS NULL THEN\n    RETURN;
\n  END IF;
\n\n  SELECT EXISTS (\n    SELECT 1 FROM estimates WHERE job_id = p_lead_id AND status = 'accepted'\n  ) INTO _has_accepted_estimate;
\n\n  SELECT EXISTS (\n    SELECT 1 FROM lead_photos WHERE lead_id = p_lead_id AND photo_type = 'before'\n  ) INTO _has_before_photos;
\n\n  IF NOT (_has_accepted_estimate AND _has_before_photos) THEN\n    RETURN;
\n  END IF;
\n\n  -- For estimate visit jobs, also check that all checklist items are complete\n  IF _lead.is_estimate_visit = true AND _lead.status = 'job' THEN\n    -- Check if all checklist items are completed\n    SELECT CASE \n      WHEN count(*) = 0 THEN false\n      WHEN count(*) FILTER (WHERE is_completed = false) > 0 THEN false\n      ELSE true\n    END INTO _all_checklist_complete\n    FROM job_checklist_items\n    WHERE job_id = p_lead_id;
\n\n    -- Only proceed if all checklist items are complete\n    IF NOT _all_checklist_complete THEN\n      RETURN;
\n    END IF;
\n\n    -- Create new regular job from estimate visit\n    INSERT INTO leads (\n      name, status, service_type, address, city, state,\n      customer_id, account_id, created_by,\n      approval_status, is_estimate_visit, estimate_job_id,\n      estimated_value, phone, email, source\n    )\n    VALUES (\n      REPLACE(_lead.name, ', Estimate', ''),\n      'job',\n      _lead.service_type,\n      _lead.address,\n      _lead.city,\n      _lead.state,\n      _lead.customer_id,\n      _lead.account_id,\n      _lead.created_by,\n      'pending',\n      false,\n      p_lead_id,\n      _lead.estimated_value,\n      _lead.phone,\n      _lead.email,\n      _lead.source\n    )\n    RETURNING id INTO _new_job_id;
\n\n    UPDATE estimates SET job_id = _new_job_id WHERE job_id = p_lead_id;
\n\n    UPDATE lead_photos SET lead_id = _new_job_id WHERE lead_id = p_lead_id;
\n\n    UPDATE leads SET approval_status = 'approved' WHERE id = _new_job_id;
\n\n    UPDATE job_schedules\n    SET is_completed = true, completed_at = now()\n    WHERE lead_id = p_lead_id;
\n\n    UPDATE leads SET status = 'completed' WHERE id = p_lead_id;
\n\n    INSERT INTO interactions (lead_id, type, direction, summary)\n    VALUES (\n      _new_job_id,\n      'status_change',\n      'na',\n      'Job created from completed estimate visit'\n    );
\n\n    RETURN;
\n  END IF;
\n\n  -- Regular lead conversion (non-estimate visit)\n  IF _lead.status IN ('job', 'paid', 'completed') THEN\n    RETURN;
\n  END IF;
\n\n  UPDATE leads SET status = 'job' WHERE id = p_lead_id;
\n\n  IF _lead.estimate_job_id IS NOT NULL THEN\n    UPDATE leads SET status = 'paid' WHERE id = _lead.estimate_job_id;
\n  END IF;
\n\n  INSERT INTO interactions (lead_id, type, direction, summary)\n  VALUES (\n    p_lead_id,\n    'status_change',\n    'na',\n    'Converted to job (estimate approved + photos uploaded)'\n  );
\nEND;
\n$$;
;
