/*\n  # Make notifications user-specific based on user settings\n\n  1. Schema Changes\n    - Add `user_id` (uuid, nullable, FK to auth.users) column to `notifications` table\n    - Backfill existing notifications by assigning them to the account owner\n\n  2. New Functions\n    - `create_user_notifications` - helper that loops over active account members,\n      checks each user's notification_preferences for the relevant alert key,\n      and inserts a notification only for users who have that alert enabled\n\n  3. Updated Trigger Functions\n    - `notify_new_lead` - now creates per-user notifications (alert key: new_leads)\n    - `notify_lead_status_change` - now creates per-user notifications (alert key: lead_updates)\n    - `notify_payment_received` - now creates per-user notifications (alert key: payments)\n    - `notify_job_scheduled` - now creates per-user notifications (alert key: schedule_changes)\n    - `notify_estimate_approved` - now creates per-user notifications (alert key: payments)\n\n  4. Security Changes\n    - Drop old account-scoped RLS policies (SELECT, UPDATE, DELETE)\n    - Add new user-scoped RLS policies so each user only sees their own notifications\n\n  5. Indexes\n    - `idx_notifications_user_id` on user_id\n    - `idx_notifications_user_created` on (user_id, created_at DESC)\n\n  6. Notes\n    - Previously, one notification was created per account and all members saw it\n    - Now, notifications are created per-user, respecting each user's alert preferences\n    - Users who have disabled an alert type in their settings will not receive those notifications\n    - Existing notifications are assigned to the account owner for backwards compatibility\n*/\n\n-- 1. Add user_id column\nDO $$\nBEGIN\n  IF NOT EXISTS (\n    SELECT 1 FROM information_schema.columns\n    WHERE table_name = 'notifications' AND column_name = 'user_id'\n  ) THEN\n    ALTER TABLE notifications ADD COLUMN user_id uuid REFERENCES auth.users(id);
\n  END IF;
\nEND $$;
\n\n-- 2. Backfill existing notifications to account owner\nUPDATE notifications n\nSET user_id = (\n  SELECT am.user_id\n  FROM account_members am\n  WHERE am.account_id = n.account_id\n  AND am.is_active = true\n  AND am.role = 'owner'\n  LIMIT 1\n)\nWHERE n.user_id IS NULL;
\n\n-- 3. Indexes\nCREATE INDEX IF NOT EXISTS idx_notifications_user_id ON notifications(user_id);
\nCREATE INDEX IF NOT EXISTS idx_notifications_user_created ON notifications(user_id, created_at DESC);
\n\n-- 4. Drop old account-scoped RLS policies\nDROP POLICY IF EXISTS "Account members can view notifications" ON notifications;
\nDROP POLICY IF EXISTS "Account members can update notifications" ON notifications;
\nDROP POLICY IF EXISTS "Account members can delete notifications" ON notifications;
\n\n-- 5. New user-scoped RLS policies\nCREATE POLICY "Users can view own notifications"\n  ON notifications FOR SELECT\n  TO authenticated\n  USING (user_id = auth.uid());
\n\nCREATE POLICY "Users can update own notifications"\n  ON notifications FOR UPDATE\n  TO authenticated\n  USING (user_id = auth.uid())\n  WITH CHECK (user_id = auth.uid());
\n\nCREATE POLICY "Users can delete own notifications"\n  ON notifications FOR DELETE\n  TO authenticated\n  USING (user_id = auth.uid());
\n\n-- 6. Helper function: create per-user notifications based on preferences\nCREATE OR REPLACE FUNCTION create_user_notifications(\n  p_account_id uuid,\n  p_title text,\n  p_body text,\n  p_event_type text,\n  p_alert_key text,\n  p_reference_id uuid,\n  p_reference_type text\n) RETURNS void\nLANGUAGE plpgsql\nSECURITY DEFINER\nSET search_path = public\nAS $$\nDECLARE\n  _member RECORD;
\n  _prefs jsonb;
\n  _alert_enabled boolean;
\nBEGIN\n  FOR _member IN\n    SELECT am.user_id, p.notification_preferences\n    FROM account_members am\n    LEFT JOIN profiles p ON p.user_id = am.user_id\n    WHERE am.account_id = p_account_id\n    AND am.is_active = true\n  LOOP\n    _prefs := _member.notification_preferences;
\n    _alert_enabled := true;
\n\n    IF _prefs IS NOT NULL\n       AND _prefs->'alerts' IS NOT NULL\n       AND _prefs->'alerts'->p_alert_key IS NOT NULL THEN\n      _alert_enabled := (_prefs->'alerts'->>p_alert_key)::boolean;
\n    END IF;
\n\n    IF _alert_enabled THEN\n      INSERT INTO notifications (account_id, user_id, title, body, event_type, reference_id, reference_type)\n      VALUES (p_account_id, _member.user_id, p_title, p_body, p_event_type, p_reference_id, p_reference_type);
\n    END IF;
\n  END LOOP;
\nEND;
\n$$;
\n\n-- 7. Update trigger functions to use per-user notifications\n\nCREATE OR REPLACE FUNCTION notify_new_lead()\nRETURNS trigger\nLANGUAGE plpgsql\nSECURITY DEFINER\nSET search_path = public\nAS $$\nBEGIN\n  PERFORM create_user_notifications(\n    NEW.account_id,\n    'New Lead',\n    'New lead from ' || COALESCE(NEW.name, 'Unknown') || COALESCE(' - ' || NEW.service_type, ''),\n    'new_lead',\n    'new_leads',\n    NEW.id,\n    'lead'\n  );
\n  RETURN NEW;
\nEND;
\n$$;
\n\nCREATE OR REPLACE FUNCTION notify_lead_status_change()\nRETURNS trigger\nLANGUAGE plpgsql\nSECURITY DEFINER\nSET search_path = public\nAS $$\nBEGIN\n  IF OLD.status IS NOT DISTINCT FROM NEW.status THEN\n    RETURN NEW;
\n  END IF;
\n\n  PERFORM create_user_notifications(\n    NEW.account_id,\n    'Lead Status Updated',\n    COALESCE(NEW.name, 'Lead') || ' moved to ' || NEW.status::text,\n    'lead_status_change',\n    'lead_updates',\n    NEW.id,\n    'lead'\n  );
\n  RETURN NEW;
\nEND;
\n$$;
\n\nCREATE OR REPLACE FUNCTION notify_payment_received()\nRETURNS trigger\nLANGUAGE plpgsql\nSECURITY DEFINER\nSET search_path = public\nAS $$\nDECLARE\n  _customer_name text;
\nBEGIN\n  SELECT name INTO _customer_name FROM customers WHERE id = NEW.customer_id;
\n\n  PERFORM create_user_notifications(\n    NEW.account_id,\n    'Payment Received',\n    '$' || COALESCE(NEW.amount::text, '0') || ' from ' || COALESCE(_customer_name, 'customer'),\n    'payment_received',\n    'payments',\n    NEW.id,\n    'payment'\n  );
\n  RETURN NEW;
\nEND;
\n$$;
\n\nCREATE OR REPLACE FUNCTION notify_job_scheduled()\nRETURNS trigger\nLANGUAGE plpgsql\nSECURITY DEFINER\nSET search_path = public\nAS $$\nDECLARE\n  _lead_name text;
\nBEGIN\n  SELECT name INTO _lead_name FROM leads WHERE id = NEW.lead_id;
\n\n  PERFORM create_user_notifications(\n    NEW.account_id,\n    'Job Scheduled',\n    COALESCE(_lead_name, 'Job') || ' scheduled for ' || NEW.scheduled_date::text,\n    'schedule_change',\n    'schedule_changes',\n    NEW.lead_id,\n    'job_schedule'\n  );
\n  RETURN NEW;
\nEND;
\n$$;
\n\nCREATE OR REPLACE FUNCTION notify_estimate_approved()\nRETURNS trigger\nLANGUAGE plpgsql\nSECURITY DEFINER\nSET search_path = public\nAS $$\nDECLARE\n  _customer_name text;
\nBEGIN\n  IF NEW.status::text != 'accepted' OR OLD.status::text = 'accepted' THEN\n    RETURN NEW;
\n  END IF;
\n\n  SELECT c.name INTO _customer_name FROM customers c WHERE c.id = NEW.customer_id;
\n\n  PERFORM create_user_notifications(\n    NEW.account_id,\n    'Estimate Approved',\n    COALESCE(_customer_name, 'Customer') || ' approved estimate for $' || COALESCE(NEW.total::text, '0'),\n    'estimate_approved',\n    'payments',\n    NEW.id,\n    'estimate'\n  );
\n  RETURN NEW;
\nEND;
\n$$;
\n;
