/*\n  # Fix security and performance issues\n\n  1. New Indexes (40 unindexed foreign keys)\n    - `account_members.invited_by`\n    - `api_keys.account_id`\n    - `customers.account_id`, `customers.lead_id`\n    - `days_off.created_by`\n    - `email_digest_log.account_id`, `email_digest_log.user_id`\n    - `estimate_change_orders.account_id`, `estimate_change_orders.changed_by`\n    - `estimate_email_notifications_log.account_id`\n    - `estimate_line_items.account_id`\n    - `estimate_line_items_original.account_id`\n    - `estimate_versions.account_id`\n    - `interactions.account_id`\n    - `invoice_line_items.account_id`, `invoice_line_items.invoice_id`\n    - `job_assignments.assigned_by`\n    - `job_schedules.created_by`\n    - `lead_photos.account_id`, `lead_photos.uploaded_by`, `lead_photos.uploaded_by` (profiles fkey)\n    - `lead_qualifications.account_id`\n    - `line_item_templates.created_by`\n    - `material_items.account_id`, `material_items.material_list_id`\n    - `message_automation_delivery_log.account_id`, `message_automation_delivery_log.lead_id`\n    - `message_automation_events.job_schedule_id`, `message_automation_events.lead_id`\n    - `payments.invoice_id`\n    - `quick_estimates.account_id`\n    - `recurring_jobs.created_by`, `recurring_jobs.customer_id`\n    - `stripe_connect_accounts.account_id`\n    - `supply_order_items.account_id`, `supply_order_items.material_item_id`, `supply_order_items.supply_order_id`\n    - `supply_orders.material_list_id`\n    - `webhook_events.invoice_id`, `webhook_events.payment_id`\n\n  2. RLS Policy Fixes (7 policies across 4 tables)\n    - Replace `auth.uid()` with `(select auth.uid())` for single-evaluation per query\n    - Tables: line_item_templates, message_automation_events, message_automation_delivery_log, estimate_email_notifications_log\n\n  3. Dropped Unused Indexes (5)\n    - `idx_message_automation_events_account`\n    - `idx_message_automation_delivery_log_event`\n    - `idx_estimates_recurring_job_id`\n    - `idx_job_checklist_items_account_id`\n    - `idx_sms_notification_log_user_id_v2`\n\n  4. Function Fixes (2 functions, 3 overloads)\n    - `compute_job_message_scheduled_for` - set immutable search_path\n    - `render_job_message_template` (2 overloads) - set immutable search_path\n*/\n\n-- ============================================================\n-- 1. Add missing foreign key indexes\n-- ============================================================\n\nCREATE INDEX IF NOT EXISTS idx_account_members_invited_by ON public.account_members (invited_by);
\nCREATE INDEX IF NOT EXISTS idx_api_keys_account_id ON public.api_keys (account_id);
\nCREATE INDEX IF NOT EXISTS idx_customers_account_id ON public.customers (account_id);
\nCREATE INDEX IF NOT EXISTS idx_customers_lead_id ON public.customers (lead_id);
\nCREATE INDEX IF NOT EXISTS idx_days_off_created_by ON public.days_off (created_by);
\nCREATE INDEX IF NOT EXISTS idx_email_digest_log_account_id ON public.email_digest_log (account_id);
\nCREATE INDEX IF NOT EXISTS idx_email_digest_log_user_id ON public.email_digest_log (user_id);
\nCREATE INDEX IF NOT EXISTS idx_estimate_change_orders_account_id ON public.estimate_change_orders (account_id);
\nCREATE INDEX IF NOT EXISTS idx_estimate_change_orders_changed_by ON public.estimate_change_orders (changed_by);
\nCREATE INDEX IF NOT EXISTS idx_estimate_email_notifications_log_account_id ON public.estimate_email_notifications_log (account_id);
\nCREATE INDEX IF NOT EXISTS idx_estimate_line_items_account_id ON public.estimate_line_items (account_id);
\nCREATE INDEX IF NOT EXISTS idx_estimate_line_items_original_account_id ON public.estimate_line_items_original (account_id);
\nCREATE INDEX IF NOT EXISTS idx_estimate_versions_account_id ON public.estimate_versions (account_id);
\nCREATE INDEX IF NOT EXISTS idx_interactions_account_id ON public.interactions (account_id);
\nCREATE INDEX IF NOT EXISTS idx_invoice_line_items_account_id ON public.invoice_line_items (account_id);
\nCREATE INDEX IF NOT EXISTS idx_invoice_line_items_invoice_id ON public.invoice_line_items (invoice_id);
\nCREATE INDEX IF NOT EXISTS idx_job_assignments_assigned_by ON public.job_assignments (assigned_by);
\nCREATE INDEX IF NOT EXISTS idx_job_schedules_created_by ON public.job_schedules (created_by);
\nCREATE INDEX IF NOT EXISTS idx_lead_photos_account_id ON public.lead_photos (account_id);
\nCREATE INDEX IF NOT EXISTS idx_lead_photos_uploaded_by ON public.lead_photos (uploaded_by);
\nCREATE INDEX IF NOT EXISTS idx_lead_qualifications_account_id ON public.lead_qualifications (account_id);
\nCREATE INDEX IF NOT EXISTS idx_line_item_templates_created_by ON public.line_item_templates (created_by);
\nCREATE INDEX IF NOT EXISTS idx_material_items_account_id ON public.material_items (account_id);
\nCREATE INDEX IF NOT EXISTS idx_material_items_material_list_id ON public.material_items (material_list_id);
\nCREATE INDEX IF NOT EXISTS idx_message_automation_delivery_log_account_id ON public.message_automation_delivery_log (account_id);
\nCREATE INDEX IF NOT EXISTS idx_message_automation_delivery_log_lead_id ON public.message_automation_delivery_log (lead_id);
\nCREATE INDEX IF NOT EXISTS idx_message_automation_events_job_schedule_id ON public.message_automation_events (job_schedule_id);
\nCREATE INDEX IF NOT EXISTS idx_message_automation_events_lead_id ON public.message_automation_events (lead_id);
\nCREATE INDEX IF NOT EXISTS idx_payments_invoice_id ON public.payments (invoice_id);
\nCREATE INDEX IF NOT EXISTS idx_quick_estimates_account_id ON public.quick_estimates (account_id);
\nCREATE INDEX IF NOT EXISTS idx_recurring_jobs_created_by ON public.recurring_jobs (created_by);
\nCREATE INDEX IF NOT EXISTS idx_recurring_jobs_customer_id ON public.recurring_jobs (customer_id);
\nCREATE INDEX IF NOT EXISTS idx_stripe_connect_accounts_account_id ON public.stripe_connect_accounts (account_id);
\nCREATE INDEX IF NOT EXISTS idx_supply_order_items_account_id ON public.supply_order_items (account_id);
\nCREATE INDEX IF NOT EXISTS idx_supply_order_items_material_item_id ON public.supply_order_items (material_item_id);
\nCREATE INDEX IF NOT EXISTS idx_supply_order_items_supply_order_id ON public.supply_order_items (supply_order_id);
\nCREATE INDEX IF NOT EXISTS idx_supply_orders_material_list_id ON public.supply_orders (material_list_id);
\nCREATE INDEX IF NOT EXISTS idx_webhook_events_invoice_id ON public.webhook_events (invoice_id);
\nCREATE INDEX IF NOT EXISTS idx_webhook_events_payment_id ON public.webhook_events (payment_id);
\n\n-- ============================================================\n-- 2. Fix RLS policies to use (select auth.uid())\n-- ============================================================\n\n-- line_item_templates: 4 policies\nDROP POLICY IF EXISTS "Users can view line item templates in their account" ON public.line_item_templates;
\nCREATE POLICY "Users can view line item templates in their account"\n  ON public.line_item_templates FOR SELECT TO authenticated\n  USING (EXISTS (\n    SELECT 1 FROM public.account_members\n    WHERE account_members.account_id = line_item_templates.account_id\n      AND account_members.user_id = (select auth.uid())\n      AND account_members.is_active = true\n  ));
\n\nDROP POLICY IF EXISTS "Users can insert line item templates in their account" ON public.line_item_templates;
\nCREATE POLICY "Users can insert line item templates in their account"\n  ON public.line_item_templates FOR INSERT TO authenticated\n  WITH CHECK (EXISTS (\n    SELECT 1 FROM public.account_members\n    WHERE account_members.account_id = line_item_templates.account_id\n      AND account_members.user_id = (select auth.uid())\n      AND account_members.is_active = true\n  ));
\n\nDROP POLICY IF EXISTS "Users can update line item templates in their account" ON public.line_item_templates;
\nCREATE POLICY "Users can update line item templates in their account"\n  ON public.line_item_templates FOR UPDATE TO authenticated\n  USING (EXISTS (\n    SELECT 1 FROM public.account_members\n    WHERE account_members.account_id = line_item_templates.account_id\n      AND account_members.user_id = (select auth.uid())\n      AND account_members.is_active = true\n  ))\n  WITH CHECK (EXISTS (\n    SELECT 1 FROM public.account_members\n    WHERE account_members.account_id = line_item_templates.account_id\n      AND account_members.user_id = (select auth.uid())\n      AND account_members.is_active = true\n  ));
\n\nDROP POLICY IF EXISTS "Users can delete line item templates in their account" ON public.line_item_templates;
\nCREATE POLICY "Users can delete line item templates in their account"\n  ON public.line_item_templates FOR DELETE TO authenticated\n  USING (EXISTS (\n    SELECT 1 FROM public.account_members\n    WHERE account_members.account_id = line_item_templates.account_id\n      AND account_members.user_id = (select auth.uid())\n      AND account_members.is_active = true\n  ));
\n\n-- message_automation_events: 1 policy\nDROP POLICY IF EXISTS "Account members can view message automation events" ON public.message_automation_events;
\nCREATE POLICY "Account members can view message automation events"\n  ON public.message_automation_events FOR SELECT TO authenticated\n  USING (EXISTS (\n    SELECT 1 FROM public.account_members am\n    WHERE am.account_id = message_automation_events.account_id\n      AND am.user_id = (select auth.uid())\n      AND am.is_active = true\n  ));
\n\n-- message_automation_delivery_log: 1 policy\nDROP POLICY IF EXISTS "Account members can view message automation delivery logs" ON public.message_automation_delivery_log;
\nCREATE POLICY "Account members can view message automation delivery logs"\n  ON public.message_automation_delivery_log FOR SELECT TO authenticated\n  USING (EXISTS (\n    SELECT 1 FROM public.account_members am\n    WHERE am.account_id = message_automation_delivery_log.account_id\n      AND am.user_id = (select auth.uid())\n      AND am.is_active = true\n  ));
\n\n-- estimate_email_notifications_log: 1 policy\nDROP POLICY IF EXISTS "Account members can view estimate email notifications" ON public.estimate_email_notifications_log;
\nCREATE POLICY "Account members can view estimate email notifications"\n  ON public.estimate_email_notifications_log FOR SELECT TO authenticated\n  USING (EXISTS (\n    SELECT 1 FROM public.account_members am\n    WHERE am.account_id = estimate_email_notifications_log.account_id\n      AND am.user_id = (select auth.uid())\n      AND am.is_active = true\n  ));
\n\n-- ============================================================\n-- 3. Drop unused indexes\n-- ============================================================\n\nDROP INDEX IF EXISTS public.idx_message_automation_events_account;
\nDROP INDEX IF EXISTS public.idx_message_automation_delivery_log_event;
\nDROP INDEX IF EXISTS public.idx_estimates_recurring_job_id;
\nDROP INDEX IF EXISTS public.idx_job_checklist_items_account_id;
\nDROP INDEX IF EXISTS public.idx_sms_notification_log_user_id_v2;
\n\n-- ============================================================\n-- 4. Fix functions with mutable search_path\n-- ============================================================\n\nCREATE OR REPLACE FUNCTION public.compute_job_message_scheduled_for(trigger_type text, offset_minutes integer, base_ts timestamptz)\nRETURNS timestamptz\nLANGUAGE plpgsql\nSET search_path = ''\nAS $function$\nDECLARE\n  now_ts timestamptz := now();
\n  effective_base timestamptz := COALESCE(base_ts, now());
\n  scheduled_ts timestamptz;
\nBEGIN\n  IF trigger_type = 'before_schedule_start' THEN\n    scheduled_ts := effective_base - make_interval(mins => GREATEST(offset_minutes, 0));
\n  ELSIF trigger_type = 'after_schedule_start' THEN\n    scheduled_ts := effective_base + make_interval(mins => GREATEST(offset_minutes, 0));
\n  ELSE\n    scheduled_ts := now_ts;
\n  END IF;
\n\n  IF scheduled_ts < now_ts THEN\n    RETURN now_ts;
\n  END IF;
\n\n  RETURN scheduled_ts;
\nEND;
\n$function$;
\n\nCREATE OR REPLACE FUNCTION public.render_job_message_template(template_text text, lead_name text, service_type text, lead_status text, lead_id uuid, scheduled_date_text text, scheduled_time_text text)\nRETURNS text\nLANGUAGE sql\nIMMUTABLE\nSET search_path = ''\nAS $function$\n  SELECT trim(\n    replace(\n      replace(\n        replace(\n          replace(\n            replace(\n              replace(\n                replace(\n                  replace(\n                    replace(COALESCE(template_text, ''), '{{job_name}}', COALESCE(lead_name, '')),\n                    '{{client_name}}',\n                    COALESCE(lead_name, '')\n                  ),\n                  '{{first_name}}',\n                  NULLIF(split_part(COALESCE(lead_name, ''), ' ', 1), '')\n                ),\n                '{{service_type}}',\n                COALESCE(service_type, '')\n              ),\n              '{{job_status}}',\n              COALESCE(lead_status, '')\n            ),\n            '{{lead_id}}',\n            COALESCE(lead_id::text, '')\n          ),\n          '{{scheduled_date}}',\n          COALESCE(scheduled_date_text, '')\n        ),\n        '{{scheduled_time}}',\n        COALESCE(scheduled_time_text, '')\n      ),\n      '{{scheduled_datetime}}',\n      trim(concat_ws(' ', COALESCE(scheduled_date_text, ''), COALESCE(scheduled_time_text, '')))\n    )\n  );
\n$function$;
\n\nCREATE OR REPLACE FUNCTION public.render_job_message_template(template_text text, lead_name text, service_type text, lead_status public.unified_status, lead_id uuid, scheduled_date_text text, scheduled_time_text text)\nRETURNS text\nLANGUAGE sql\nIMMUTABLE\nSET search_path = ''\nAS $function$\n  SELECT public.render_job_message_template(\n    template_text,\n    lead_name,\n    service_type,\n    lead_status::text,\n    lead_id,\n    scheduled_date_text,\n    scheduled_time_text\n  );
\n$function$;
\n;
