/*\n  # Fix RLS Performance Caching Issue\n\n  1. Problem\n    - Session-level caching doesn't work properly with connection pooling\n    - May cause cross-user data leakage or cache misses\n    \n  2. Solution\n    - Remove session-level caching from get_user_roles()\n    - Keep the optimized has_role() function\n    - PostgreSQL will handle query optimization naturally\n    \n  3. Changes\n    - Simplify get_user_roles() to just fetch roles without caching\n    - Maintain security while ensuring proper functionality\n*/\n\n-- Simplify get_user_roles to remove problematic session caching\nCREATE OR REPLACE FUNCTION get_user_roles()\nRETURNS TEXT[] AS $$\nDECLARE\n  roles TEXT[];
\nBEGIN\n  -- Fetch roles for current user\n  SELECT ARRAY_AGG(role::TEXT)\n  INTO roles\n  FROM user_roles\n  WHERE user_id = auth.uid();
\n\n  RETURN COALESCE(roles, ARRAY[]::TEXT[]);
\nEND;
\n$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;
\n\n-- Keep the optimized has_role function\nCREATE OR REPLACE FUNCTION has_role(_user_id UUID, _role app_role)\nRETURNS BOOLEAN AS $$\nBEGIN\n  -- For current user, use the roles array (PostgreSQL will cache this within the query)\n  IF _user_id = auth.uid() THEN\n    RETURN _role::TEXT = ANY(get_user_roles());
\n  END IF;
\n  \n  -- For other users, do direct lookup\n  RETURN EXISTS (\n    SELECT 1\n    FROM user_roles\n    WHERE user_id = _user_id\n      AND role = _role\n  );
\nEND;
\n$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;
\n;
