/*\n  # Fix function search paths and add affiliates RLS policies\n\n  1. Security fixes\n    - Set immutable `search_path` on `generate_affiliate_referral_code` to prevent search path manipulation\n    - Set immutable `search_path` on `prevent_direct_billing_field_updates` to prevent search path manipulation\n    - Add RLS policies on `affiliates` table so it is not locked out with no access\n\n  2. New policies on `affiliates`\n    - SELECT: service_role only (admin access via server)\n    - INSERT: service_role only\n    - UPDATE: service_role only\n    - DELETE: service_role only\n\n  Note: The affiliates table is an internal/admin table managed by server-side\n  flows, so all policies restrict access to service_role.\n*/\n\nCREATE OR REPLACE FUNCTION public.generate_affiliate_referral_code()\n RETURNS text\n LANGUAGE plpgsql\n SET search_path = ''\nAS $function$\nDECLARE\n  v_code text;
\nBEGIN\n  v_code := 'AFF' || upper(substr(md5(random()::text || clock_timestamp()::text), 1, 9));
\n  RETURN v_code;
\nEND;
\n$function$;
\n\nCREATE OR REPLACE FUNCTION public.prevent_direct_billing_field_updates()\n RETURNS trigger\n LANGUAGE plpgsql\n SET search_path = ''\nAS $function$\nDECLARE\n  jwt_role text := current_setting('request.jwt.claim.role', true);
\nBEGIN\n  IF jwt_role IS DISTINCT FROM 'service_role'\n     AND (\n       NEW.pricing_plan IS DISTINCT FROM OLD.pricing_plan\n       OR NEW.pricing_tier IS DISTINCT FROM OLD.pricing_tier\n       OR NEW.stripe_customer_id IS DISTINCT FROM OLD.stripe_customer_id\n       OR NEW.stripe_subscription_id IS DISTINCT FROM OLD.stripe_subscription_id\n       OR NEW.stripe_subscription_status IS DISTINCT FROM OLD.stripe_subscription_status\n       OR NEW.premium_setup_fee_paid IS DISTINCT FROM OLD.premium_setup_fee_paid\n     ) THEN\n    RAISE EXCEPTION 'Billing fields can only be changed by server billing flows';
\n  END IF;
\n\n  RETURN NEW;
\nEND;
\n$function$;
\n\nDO $$\nBEGIN\n  IF NOT EXISTS (\n    SELECT 1 FROM pg_policies\n    WHERE schemaname = 'public' AND tablename = 'affiliates' AND policyname = 'Service role can select affiliates'\n  ) THEN\n    CREATE POLICY "Service role can select affiliates"\n      ON public.affiliates FOR SELECT\n      TO service_role\n      USING (true);
\n  END IF;
\n\n  IF NOT EXISTS (\n    SELECT 1 FROM pg_policies\n    WHERE schemaname = 'public' AND tablename = 'affiliates' AND policyname = 'Service role can insert affiliates'\n  ) THEN\n    CREATE POLICY "Service role can insert affiliates"\n      ON public.affiliates FOR INSERT\n      TO service_role\n      WITH CHECK (true);
\n  END IF;
\n\n  IF NOT EXISTS (\n    SELECT 1 FROM pg_policies\n    WHERE schemaname = 'public' AND tablename = 'affiliates' AND policyname = 'Service role can update affiliates'\n  ) THEN\n    CREATE POLICY "Service role can update affiliates"\n      ON public.affiliates FOR UPDATE\n      TO service_role\n      USING (true)\n      WITH CHECK (true);
\n  END IF;
\n\n  IF NOT EXISTS (\n    SELECT 1 FROM pg_policies\n    WHERE schemaname = 'public' AND tablename = 'affiliates' AND policyname = 'Service role can delete affiliates'\n  ) THEN\n    CREATE POLICY "Service role can delete affiliates"\n      ON public.affiliates FOR DELETE\n      TO service_role\n      USING (true);
\n  END IF;
\nEND $$;
\n;
