/*\n  # Add SMS notification triggers via pg_net\n\n  1. Functions\n    - `notify_sms_new_lead()` - fires on INSERT to leads table\n    - `notify_sms_lead_update()` - fires on UPDATE to leads.status column\n    - `notify_sms_payment()` - fires on INSERT to payments table\n    - `notify_sms_schedule_change()` - fires on INSERT or UPDATE to job_schedules table\n\n  2. Triggers\n    - `trigger_sms_new_lead` on leads INSERT\n    - `trigger_sms_lead_update` on leads UPDATE of status\n    - `trigger_sms_payment` on payments INSERT\n    - `trigger_sms_schedule_change` on job_schedules INSERT or UPDATE\n\n  3. Notes\n    - Uses pg_net to make async HTTP calls to the send-sms edge function\n    - Each trigger passes event_type, account_id, and relevant data\n    - The edge function handles preference checking and actual SMS delivery\n*/\n\nCREATE OR REPLACE FUNCTION notify_sms_new_lead()\nRETURNS trigger\nLANGUAGE plpgsql\nSECURITY DEFINER\nAS $$\nDECLARE\n  _supabase_url text := current_setting('app.settings.supabase_url', true);
\n  _service_key text := current_setting('app.settings.service_role_key', true);
\nBEGIN\n  IF _supabase_url IS NULL OR _supabase_url = '' THEN\n    _supabase_url := (SELECT decrypted_secret FROM vault.decrypted_secrets WHERE name = 'supabase_url' LIMIT 1);
\n  END IF;
\n  IF _service_key IS NULL OR _service_key = '' THEN\n    _service_key := (SELECT decrypted_secret FROM vault.decrypted_secrets WHERE name = 'service_role_key' LIMIT 1);
\n  END IF;
\n\n  IF _supabase_url IS NOT NULL AND _service_key IS NOT NULL THEN\n    PERFORM extensions.http_post(\n      _supabase_url || '/functions/v1/send-sms',\n      json_build_object(\n        'event_type', 'new_leads',\n        'account_id', NEW.account_id::text,\n        'data', json_build_object(\n          'lead_id', NEW.id::text,\n          'name', COALESCE(NEW.name, 'Unknown'),\n          'phone', COALESCE(NEW.phone, ''),\n          'email', COALESCE(NEW.email, ''),\n          'service_type', COALESCE(NEW.service_type, ''),\n          'source', COALESCE(NEW.source, '')\n        )\n      )::text,\n      'application/json',\n      ARRAY[\n        extensions.http_header('Authorization', 'Bearer ' || _service_key),\n        extensions.http_header('Content-Type', 'application/json')\n      ]\n    );
\n  END IF;
\n\n  RETURN NEW;
\nEND;
\n$$;
\n\nCREATE OR REPLACE FUNCTION notify_sms_lead_update()\nRETURNS trigger\nLANGUAGE plpgsql\nSECURITY DEFINER\nAS $$\nDECLARE\n  _supabase_url text := current_setting('app.settings.supabase_url', true);
\n  _service_key text := current_setting('app.settings.service_role_key', true);
\nBEGIN\n  IF OLD.status IS NOT DISTINCT FROM NEW.status THEN\n    RETURN NEW;
\n  END IF;
\n\n  IF _supabase_url IS NULL OR _supabase_url = '' THEN\n    _supabase_url := (SELECT decrypted_secret FROM vault.decrypted_secrets WHERE name = 'supabase_url' LIMIT 1);
\n  END IF;
\n  IF _service_key IS NULL OR _service_key = '' THEN\n    _service_key := (SELECT decrypted_secret FROM vault.decrypted_secrets WHERE name = 'service_role_key' LIMIT 1);
\n  END IF;
\n\n  IF _supabase_url IS NOT NULL AND _service_key IS NOT NULL THEN\n    PERFORM extensions.http_post(\n      _supabase_url || '/functions/v1/send-sms',\n      json_build_object(\n        'event_type', 'lead_updates',\n        'account_id', NEW.account_id::text,\n        'data', json_build_object(\n          'lead_id', NEW.id::text,\n          'name', COALESCE(NEW.name, 'Unknown'),\n          'status', NEW.status::text,\n          'old_status', OLD.status::text\n        )\n      )::text,\n      'application/json',\n      ARRAY[\n        extensions.http_header('Authorization', 'Bearer ' || _service_key),\n        extensions.http_header('Content-Type', 'application/json')\n      ]\n    );
\n  END IF;
\n\n  RETURN NEW;
\nEND;
\n$$;
\n\nCREATE OR REPLACE FUNCTION notify_sms_payment()\nRETURNS trigger\nLANGUAGE plpgsql\nSECURITY DEFINER\nAS $$\nDECLARE\n  _supabase_url text := current_setting('app.settings.supabase_url', true);
\n  _service_key text := current_setting('app.settings.service_role_key', true);
\n  _customer_name text;
\nBEGIN\n  SELECT name INTO _customer_name FROM customers WHERE id = NEW.customer_id;
\n\n  IF _supabase_url IS NULL OR _supabase_url = '' THEN\n    _supabase_url := (SELECT decrypted_secret FROM vault.decrypted_secrets WHERE name = 'supabase_url' LIMIT 1);
\n  END IF;
\n  IF _service_key IS NULL OR _service_key = '' THEN\n    _service_key := (SELECT decrypted_secret FROM vault.decrypted_secrets WHERE name = 'service_role_key' LIMIT 1);
\n  END IF;
\n\n  IF _supabase_url IS NOT NULL AND _service_key IS NOT NULL THEN\n    PERFORM extensions.http_post(\n      _supabase_url || '/functions/v1/send-sms',\n      json_build_object(\n        'event_type', 'payments',\n        'account_id', NEW.account_id::text,\n        'data', json_build_object(\n          'payment_id', NEW.id::text,\n          'amount', NEW.amount::text,\n          'customer_name', COALESCE(_customer_name, 'Unknown'),\n          'method', NEW.method::text,\n          'status', NEW.status::text\n        )\n      )::text,\n      'application/json',\n      ARRAY[\n        extensions.http_header('Authorization', 'Bearer ' || _service_key),\n        extensions.http_header('Content-Type', 'application/json')\n      ]\n    );
\n  END IF;
\n\n  RETURN NEW;
\nEND;
\n$$;
\n\nCREATE OR REPLACE FUNCTION notify_sms_schedule_change()\nRETURNS trigger\nLANGUAGE plpgsql\nSECURITY DEFINER\nAS $$\nDECLARE\n  _supabase_url text := current_setting('app.settings.supabase_url', true);
\n  _service_key text := current_setting('app.settings.service_role_key', true);
\n  _lead_name text;
\nBEGIN\n  SELECT name INTO _lead_name FROM leads WHERE id = NEW.lead_id;
\n\n  IF _supabase_url IS NULL OR _supabase_url = '' THEN\n    _supabase_url := (SELECT decrypted_secret FROM vault.decrypted_secrets WHERE name = 'supabase_url' LIMIT 1);
\n  END IF;
\n  IF _service_key IS NULL OR _service_key = '' THEN\n    _service_key := (SELECT decrypted_secret FROM vault.decrypted_secrets WHERE name = 'service_role_key' LIMIT 1);
\n  END IF;
\n\n  IF _supabase_url IS NOT NULL AND _service_key IS NOT NULL THEN\n    PERFORM extensions.http_post(\n      _supabase_url || '/functions/v1/send-sms',\n      json_build_object(\n        'event_type', 'schedule_changes',\n        'account_id', NEW.account_id::text,\n        'data', json_build_object(\n          'schedule_id', NEW.id::text,\n          'lead_id', NEW.lead_id::text,\n          'lead_name', COALESCE(_lead_name, 'Job'),\n          'scheduled_date', NEW.scheduled_date::text,\n          'scheduled_time_start', COALESCE(NEW.scheduled_time_start::text, ''),\n          'scheduled_time_end', COALESCE(NEW.scheduled_time_end::text, '')\n        )\n      )::text,\n      'application/json',\n      ARRAY[\n        extensions.http_header('Authorization', 'Bearer ' || _service_key),\n        extensions.http_header('Content-Type', 'application/json')\n      ]\n    );
\n  END IF;
\n\n  RETURN NEW;
\nEND;
\n$$;
\n\nDROP TRIGGER IF EXISTS trigger_sms_new_lead ON leads;
\nCREATE TRIGGER trigger_sms_new_lead\n  AFTER INSERT ON leads\n  FOR EACH ROW\n  EXECUTE FUNCTION notify_sms_new_lead();
\n\nDROP TRIGGER IF EXISTS trigger_sms_lead_update ON leads;
\nCREATE TRIGGER trigger_sms_lead_update\n  AFTER UPDATE ON leads\n  FOR EACH ROW\n  EXECUTE FUNCTION notify_sms_lead_update();
\n\nDROP TRIGGER IF EXISTS trigger_sms_payment ON payments;
\nCREATE TRIGGER trigger_sms_payment\n  AFTER INSERT ON payments\n  FOR EACH ROW\n  EXECUTE FUNCTION notify_sms_payment();
\n\nDROP TRIGGER IF EXISTS trigger_sms_schedule_change ON job_schedules;
\nCREATE TRIGGER trigger_sms_schedule_change\n  AFTER INSERT OR UPDATE ON job_schedules\n  FOR EACH ROW\n  EXECUTE FUNCTION notify_sms_schedule_change();
\n;
