/*\n  # Update Existing Table Policies to Use Security Definer Functions\n  \n  ## Overview\n  Replace all RLS policies that query account_members directly with calls\n  to the new security definer functions. This eliminates circular dependencies.\n  \n  ## Changes\n  \n  ### Tables Updated\n  - leads\n  - customers\n  - estimates\n  - invoices\n  - payments\n  - material_lists\n  - supply_orders\n  - estimate_line_items\n  - invoice_line_items\n  - material_items\n  - supply_order_items\n  - interactions\n  - lead_qualifications\n  - quick_estimates\n  \n  ### Pattern\n  OLD: WHERE EXISTS (SELECT 1 FROM account_members WHERE ...)\n  NEW: WHERE get_user_account_id(auth.uid()) IS NOT NULL\n  \n  ## Security\n  - All policies now use security definer functions that safely bypass RLS\n  - Users can only access data for their account\n  - No circular dependencies\n*/\n\n-- ============================================================================\n-- LEADS TABLE\n-- ============================================================================\n\nDROP POLICY IF EXISTS "Users can view leads in their account" ON public.leads;
\nDROP POLICY IF EXISTS "Users can create leads in their account" ON public.leads;
\nDROP POLICY IF EXISTS "Users can update leads in their account" ON public.leads;
\nDROP POLICY IF EXISTS "Users can delete leads in their account" ON public.leads;
\n\nCREATE POLICY "Users can view leads in their account"\n  ON public.leads FOR SELECT\n  TO authenticated\n  USING (\n    account_id = get_user_account_id(auth.uid())\n  );
\n\nCREATE POLICY "Users can create leads in their account"\n  ON public.leads FOR INSERT\n  TO authenticated\n  WITH CHECK (\n    account_id = get_user_account_id(auth.uid())\n  );
\n\nCREATE POLICY "Users can update leads in their account"\n  ON public.leads FOR UPDATE\n  TO authenticated\n  USING (\n    account_id = get_user_account_id(auth.uid())\n  )\n  WITH CHECK (\n    account_id = get_user_account_id(auth.uid())\n  );
\n\nCREATE POLICY "Users can delete leads in their account"\n  ON public.leads FOR DELETE\n  TO authenticated\n  USING (\n    account_id = get_user_account_id(auth.uid())\n  );
\n\n-- ============================================================================\n-- CUSTOMERS TABLE\n-- ============================================================================\n\nDROP POLICY IF EXISTS "Users can view customers in their account" ON public.customers;
\nDROP POLICY IF EXISTS "Users can create customers in their account" ON public.customers;
\nDROP POLICY IF EXISTS "Users can update customers in their account" ON public.customers;
\nDROP POLICY IF EXISTS "Users can delete customers in their account" ON public.customers;
\n\nCREATE POLICY "Users can view customers in their account"\n  ON public.customers FOR SELECT\n  TO authenticated\n  USING (\n    account_id = get_user_account_id(auth.uid())\n  );
\n\nCREATE POLICY "Users can create customers in their account"\n  ON public.customers FOR INSERT\n  TO authenticated\n  WITH CHECK (\n    account_id = get_user_account_id(auth.uid())\n  );
\n\nCREATE POLICY "Users can update customers in their account"\n  ON public.customers FOR UPDATE\n  TO authenticated\n  USING (\n    account_id = get_user_account_id(auth.uid())\n  )\n  WITH CHECK (\n    account_id = get_user_account_id(auth.uid())\n  );
\n\nCREATE POLICY "Users can delete customers in their account"\n  ON public.customers FOR DELETE\n  TO authenticated\n  USING (\n    account_id = get_user_account_id(auth.uid())\n  );
\n\n-- ============================================================================\n-- ESTIMATES TABLE\n-- ============================================================================\n\nDROP POLICY IF EXISTS "Users can view estimates in their account" ON public.estimates;
\nDROP POLICY IF EXISTS "Users can create estimates in their account" ON public.estimates;
\nDROP POLICY IF EXISTS "Users can update estimates in their account" ON public.estimates;
\nDROP POLICY IF EXISTS "Users can delete estimates in their account" ON public.estimates;
\n\nCREATE POLICY "Users can view estimates in their account"\n  ON public.estimates FOR SELECT\n  TO authenticated\n  USING (\n    account_id = get_user_account_id(auth.uid())\n  );
\n\nCREATE POLICY "Users can create estimates in their account"\n  ON public.estimates FOR INSERT\n  TO authenticated\n  WITH CHECK (\n    account_id = get_user_account_id(auth.uid())\n  );
\n\nCREATE POLICY "Users can update estimates in their account"\n  ON public.estimates FOR UPDATE\n  TO authenticated\n  USING (\n    account_id = get_user_account_id(auth.uid())\n  )\n  WITH CHECK (\n    account_id = get_user_account_id(auth.uid())\n  );
\n\nCREATE POLICY "Users can delete estimates in their account"\n  ON public.estimates FOR DELETE\n  TO authenticated\n  USING (\n    account_id = get_user_account_id(auth.uid())\n  );
\n\n-- ============================================================================\n-- INVOICES TABLE\n-- ============================================================================\n\nDROP POLICY IF EXISTS "Users can view invoices in their account" ON public.invoices;
\nDROP POLICY IF EXISTS "Users can create invoices in their account" ON public.invoices;
\nDROP POLICY IF EXISTS "Users can update invoices in their account" ON public.invoices;
\nDROP POLICY IF EXISTS "Users can delete invoices in their account" ON public.invoices;
\n\nCREATE POLICY "Users can view invoices in their account"\n  ON public.invoices FOR SELECT\n  TO authenticated\n  USING (\n    account_id = get_user_account_id(auth.uid())\n  );
\n\nCREATE POLICY "Users can create invoices in their account"\n  ON public.invoices FOR INSERT\n  TO authenticated\n  WITH CHECK (\n    account_id = get_user_account_id(auth.uid())\n  );
\n\nCREATE POLICY "Users can update invoices in their account"\n  ON public.invoices FOR UPDATE\n  TO authenticated\n  USING (\n    account_id = get_user_account_id(auth.uid())\n  )\n  WITH CHECK (\n    account_id = get_user_account_id(auth.uid())\n  );
\n\nCREATE POLICY "Users can delete invoices in their account"\n  ON public.invoices FOR DELETE\n  TO authenticated\n  USING (\n    account_id = get_user_account_id(auth.uid())\n  );
\n\n-- ============================================================================\n-- PAYMENTS TABLE\n-- ============================================================================\n\nDROP POLICY IF EXISTS "Users can view payments in their account" ON public.payments;
\nDROP POLICY IF EXISTS "Users can create payments in their account" ON public.payments;
\nDROP POLICY IF EXISTS "Users can update payments in their account" ON public.payments;
\nDROP POLICY IF EXISTS "Users can delete payments in their account" ON public.payments;
\n\nCREATE POLICY "Users can view payments in their account"\n  ON public.payments FOR SELECT\n  TO authenticated\n  USING (\n    account_id = get_user_account_id(auth.uid())\n  );
\n\nCREATE POLICY "Users can create payments in their account"\n  ON public.payments FOR INSERT\n  TO authenticated\n  WITH CHECK (\n    account_id = get_user_account_id(auth.uid())\n  );
\n\nCREATE POLICY "Users can update payments in their account"\n  ON public.payments FOR UPDATE\n  TO authenticated\n  USING (\n    account_id = get_user_account_id(auth.uid())\n  )\n  WITH CHECK (\n    account_id = get_user_account_id(auth.uid())\n  );
\n\nCREATE POLICY "Users can delete payments in their account"\n  ON public.payments FOR DELETE\n  TO authenticated\n  USING (\n    account_id = get_user_account_id(auth.uid())\n  );
\n\n-- ============================================================================\n-- MATERIAL_LISTS TABLE\n-- ============================================================================\n\nDROP POLICY IF EXISTS "Users can view material lists in their account" ON public.material_lists;
\nDROP POLICY IF EXISTS "Users can create material lists in their account" ON public.material_lists;
\nDROP POLICY IF EXISTS "Users can update material lists in their account" ON public.material_lists;
\nDROP POLICY IF EXISTS "Users can delete material lists in their account" ON public.material_lists;
\n\nCREATE POLICY "Users can view material lists in their account"\n  ON public.material_lists FOR SELECT\n  TO authenticated\n  USING (\n    account_id = get_user_account_id(auth.uid())\n  );
\n\nCREATE POLICY "Users can create material lists in their account"\n  ON public.material_lists FOR INSERT\n  TO authenticated\n  WITH CHECK (\n    account_id = get_user_account_id(auth.uid())\n  );
\n\nCREATE POLICY "Users can update material lists in their account"\n  ON public.material_lists FOR UPDATE\n  TO authenticated\n  USING (\n    account_id = get_user_account_id(auth.uid())\n  )\n  WITH CHECK (\n    account_id = get_user_account_id(auth.uid())\n  );
\n\nCREATE POLICY "Users can delete material lists in their account"\n  ON public.material_lists FOR DELETE\n  TO authenticated\n  USING (\n    account_id = get_user_account_id(auth.uid())\n  );
\n\n-- ============================================================================\n-- SUPPLY_ORDERS TABLE\n-- ============================================================================\n\nDROP POLICY IF EXISTS "Users can view supply orders in their account" ON public.supply_orders;
\nDROP POLICY IF EXISTS "Users can create supply orders in their account" ON public.supply_orders;
\nDROP POLICY IF EXISTS "Users can update supply orders in their account" ON public.supply_orders;
\nDROP POLICY IF EXISTS "Users can delete supply orders in their account" ON public.supply_orders;
\n\nCREATE POLICY "Users can view supply orders in their account"\n  ON public.supply_orders FOR SELECT\n  TO authenticated\n  USING (\n    account_id = get_user_account_id(auth.uid())\n  );
\n\nCREATE POLICY "Users can create supply orders in their account"\n  ON public.supply_orders FOR INSERT\n  TO authenticated\n  WITH CHECK (\n    account_id = get_user_account_id(auth.uid())\n  );
\n\nCREATE POLICY "Users can update supply orders in their account"\n  ON public.supply_orders FOR UPDATE\n  TO authenticated\n  USING (\n    account_id = get_user_account_id(auth.uid())\n  )\n  WITH CHECK (\n    account_id = get_user_account_id(auth.uid())\n  );
\n\nCREATE POLICY "Users can delete supply orders in their account"\n  ON public.supply_orders FOR DELETE\n  TO authenticated\n  USING (\n    account_id = get_user_account_id(auth.uid())\n  );
\n\n-- ============================================================================\n-- ESTIMATE_LINE_ITEMS TABLE\n-- ============================================================================\n\nDROP POLICY IF EXISTS "Users can view estimate line items in their account" ON public.estimate_line_items;
\nDROP POLICY IF EXISTS "Users can create estimate line items in their account" ON public.estimate_line_items;
\nDROP POLICY IF EXISTS "Users can update estimate line items in their account" ON public.estimate_line_items;
\nDROP POLICY IF EXISTS "Users can delete estimate line items in their account" ON public.estimate_line_items;
\n\nCREATE POLICY "Users can view estimate line items in their account"\n  ON public.estimate_line_items FOR SELECT\n  TO authenticated\n  USING (\n    account_id = get_user_account_id(auth.uid())\n  );
\n\nCREATE POLICY "Users can create estimate line items in their account"\n  ON public.estimate_line_items FOR INSERT\n  TO authenticated\n  WITH CHECK (\n    account_id = get_user_account_id(auth.uid())\n  );
\n\nCREATE POLICY "Users can update estimate line items in their account"\n  ON public.estimate_line_items FOR UPDATE\n  TO authenticated\n  USING (\n    account_id = get_user_account_id(auth.uid())\n  )\n  WITH CHECK (\n    account_id = get_user_account_id(auth.uid())\n  );
\n\nCREATE POLICY "Users can delete estimate line items in their account"\n  ON public.estimate_line_items FOR DELETE\n  TO authenticated\n  USING (\n    account_id = get_user_account_id(auth.uid())\n  );
\n\n-- ============================================================================\n-- INVOICE_LINE_ITEMS TABLE\n-- ============================================================================\n\nDROP POLICY IF EXISTS "Users can view invoice line items in their account" ON public.invoice_line_items;
\nDROP POLICY IF EXISTS "Users can create invoice line items in their account" ON public.invoice_line_items;
\nDROP POLICY IF EXISTS "Users can update invoice line items in their account" ON public.invoice_line_items;
\nDROP POLICY IF EXISTS "Users can delete invoice line items in their account" ON public.invoice_line_items;
\n\nCREATE POLICY "Users can view invoice line items in their account"\n  ON public.invoice_line_items FOR SELECT\n  TO authenticated\n  USING (\n    account_id = get_user_account_id(auth.uid())\n  );
\n\nCREATE POLICY "Users can create invoice line items in their account"\n  ON public.invoice_line_items FOR INSERT\n  TO authenticated\n  WITH CHECK (\n    account_id = get_user_account_id(auth.uid())\n  );
\n\nCREATE POLICY "Users can update invoice line items in their account"\n  ON public.invoice_line_items FOR UPDATE\n  TO authenticated\n  USING (\n    account_id = get_user_account_id(auth.uid())\n  )\n  WITH CHECK (\n    account_id = get_user_account_id(auth.uid())\n  );
\n\nCREATE POLICY "Users can delete invoice line items in their account"\n  ON public.invoice_line_items FOR DELETE\n  TO authenticated\n  USING (\n    account_id = get_user_account_id(auth.uid())\n  );
\n\n-- ============================================================================\n-- MATERIAL_ITEMS TABLE\n-- ============================================================================\n\nDROP POLICY IF EXISTS "Users can view material items in their account" ON public.material_items;
\nDROP POLICY IF EXISTS "Users can create material items in their account" ON public.material_items;
\nDROP POLICY IF EXISTS "Users can update material items in their account" ON public.material_items;
\nDROP POLICY IF EXISTS "Users can delete material items in their account" ON public.material_items;
\n\nCREATE POLICY "Users can view material items in their account"\n  ON public.material_items FOR SELECT\n  TO authenticated\n  USING (\n    account_id = get_user_account_id(auth.uid())\n  );
\n\nCREATE POLICY "Users can create material items in their account"\n  ON public.material_items FOR INSERT\n  TO authenticated\n  WITH CHECK (\n    account_id = get_user_account_id(auth.uid())\n  );
\n\nCREATE POLICY "Users can update material items in their account"\n  ON public.material_items FOR UPDATE\n  TO authenticated\n  USING (\n    account_id = get_user_account_id(auth.uid())\n  )\n  WITH CHECK (\n    account_id = get_user_account_id(auth.uid())\n  );
\n\nCREATE POLICY "Users can delete material items in their account"\n  ON public.material_items FOR DELETE\n  TO authenticated\n  USING (\n    account_id = get_user_account_id(auth.uid())\n  );
\n\n-- ============================================================================\n-- SUPPLY_ORDER_ITEMS TABLE\n-- ============================================================================\n\nDROP POLICY IF EXISTS "Users can view supply order items in their account" ON public.supply_order_items;
\nDROP POLICY IF EXISTS "Users can create supply order items in their account" ON public.supply_order_items;
\nDROP POLICY IF EXISTS "Users can update supply order items in their account" ON public.supply_order_items;
\nDROP POLICY IF EXISTS "Users can delete supply order items in their account" ON public.supply_order_items;
\n\nCREATE POLICY "Users can view supply order items in their account"\n  ON public.supply_order_items FOR SELECT\n  TO authenticated\n  USING (\n    account_id = get_user_account_id(auth.uid())\n  );
\n\nCREATE POLICY "Users can create supply order items in their account"\n  ON public.supply_order_items FOR INSERT\n  TO authenticated\n  WITH CHECK (\n    account_id = get_user_account_id(auth.uid())\n  );
\n\nCREATE POLICY "Users can update supply order items in their account"\n  ON public.supply_order_items FOR UPDATE\n  TO authenticated\n  USING (\n    account_id = get_user_account_id(auth.uid())\n  )\n  WITH CHECK (\n    account_id = get_user_account_id(auth.uid())\n  );
\n\nCREATE POLICY "Users can delete supply order items in their account"\n  ON public.supply_order_items FOR DELETE\n  TO authenticated\n  USING (\n    account_id = get_user_account_id(auth.uid())\n  );
\n\n-- ============================================================================\n-- INTERACTIONS TABLE\n-- ============================================================================\n\nDROP POLICY IF EXISTS "Users can view interactions in their account" ON public.interactions;
\nDROP POLICY IF EXISTS "Users can create interactions in their account" ON public.interactions;
\nDROP POLICY IF EXISTS "Users can update interactions in their account" ON public.interactions;
\nDROP POLICY IF EXISTS "Users can delete interactions in their account" ON public.interactions;
\n\nCREATE POLICY "Users can view interactions in their account"\n  ON public.interactions FOR SELECT\n  TO authenticated\n  USING (\n    account_id = get_user_account_id(auth.uid())\n  );
\n\nCREATE POLICY "Users can create interactions in their account"\n  ON public.interactions FOR INSERT\n  TO authenticated\n  WITH CHECK (\n    account_id = get_user_account_id(auth.uid())\n  );
\n\nCREATE POLICY "Users can update interactions in their account"\n  ON public.interactions FOR UPDATE\n  TO authenticated\n  USING (\n    account_id = get_user_account_id(auth.uid())\n  )\n  WITH CHECK (\n    account_id = get_user_account_id(auth.uid())\n  );
\n\nCREATE POLICY "Users can delete interactions in their account"\n  ON public.interactions FOR DELETE\n  TO authenticated\n  USING (\n    account_id = get_user_account_id(auth.uid())\n  );
\n\n-- ============================================================================\n-- LEAD_QUALIFICATIONS TABLE\n-- ============================================================================\n\nDROP POLICY IF EXISTS "Users can view lead qualifications in their account" ON public.lead_qualifications;
\nDROP POLICY IF EXISTS "Users can create lead qualifications in their account" ON public.lead_qualifications;
\nDROP POLICY IF EXISTS "Users can update lead qualifications in their account" ON public.lead_qualifications;
\nDROP POLICY IF EXISTS "Users can delete lead qualifications in their account" ON public.lead_qualifications;
\n\nCREATE POLICY "Users can view lead qualifications in their account"\n  ON public.lead_qualifications FOR SELECT\n  TO authenticated\n  USING (\n    account_id = get_user_account_id(auth.uid())\n  );
\n\nCREATE POLICY "Users can create lead qualifications in their account"\n  ON public.lead_qualifications FOR INSERT\n  TO authenticated\n  WITH CHECK (\n    account_id = get_user_account_id(auth.uid())\n  );
\n\nCREATE POLICY "Users can update lead qualifications in their account"\n  ON public.lead_qualifications FOR UPDATE\n  TO authenticated\n  USING (\n    account_id = get_user_account_id(auth.uid())\n  )\n  WITH CHECK (\n    account_id = get_user_account_id(auth.uid())\n  );
\n\nCREATE POLICY "Users can delete lead qualifications in their account"\n  ON public.lead_qualifications FOR DELETE\n  TO authenticated\n  USING (\n    account_id = get_user_account_id(auth.uid())\n  );
\n\n-- ============================================================================\n-- QUICK_ESTIMATES TABLE\n-- ============================================================================\n\nDROP POLICY IF EXISTS "Users can view quick estimates in their account" ON public.quick_estimates;
\nDROP POLICY IF EXISTS "Users can create quick estimates in their account" ON public.quick_estimates;
\nDROP POLICY IF EXISTS "Users can update quick estimates in their account" ON public.quick_estimates;
\nDROP POLICY IF EXISTS "Users can delete quick estimates in their account" ON public.quick_estimates;
\n\nCREATE POLICY "Users can view quick estimates in their account"\n  ON public.quick_estimates FOR SELECT\n  TO authenticated\n  USING (\n    account_id = get_user_account_id(auth.uid())\n  );
\n\nCREATE POLICY "Users can create quick estimates in their account"\n  ON public.quick_estimates FOR INSERT\n  TO authenticated\n  WITH CHECK (\n    account_id = get_user_account_id(auth.uid())\n  );
\n\nCREATE POLICY "Users can update quick estimates in their account"\n  ON public.quick_estimates FOR UPDATE\n  TO authenticated\n  USING (\n    account_id = get_user_account_id(auth.uid())\n  )\n  WITH CHECK (\n    account_id = get_user_account_id(auth.uid())\n  );
\n\nCREATE POLICY "Users can delete quick estimates in their account"\n  ON public.quick_estimates FOR DELETE\n  TO authenticated\n  USING (\n    account_id = get_user_account_id(auth.uid())\n  );
;
