/*\n  # Change estimate scheduling to convert lead into estimate job\n\n  1. Modified Functions\n    - `try_convert_lead_to_job(lead_id uuid)` - Now handles two paths:\n      - Path 1: When the lead IS an estimate job (is_estimate_visit=true, status='job'),\n        creates a NEW regular job record, moves the estimate and photos to it,\n        marks the estimate job's schedules as completed, and sets estimate job status\n        to 'completed'.\n      - Path 2: When the lead is a regular lead (not an estimate job), keeps the\n        existing behavior of updating the lead's status to 'job'.\n\n    - `cleanup_estimate_job_on_lead_delete()` - Updated to only cascade-delete\n      estimate jobs when the deleted record is a lead (not a job). This prevents\n      deleting the estimate job when the derived regular job is deleted.\n\n  2. Important Notes\n    - In the new flow, scheduling an estimate converts the qualified lead itself\n      into an estimate job (instead of creating a separate record).\n    - When the estimate is approved and photos are uploaded, a new regular job\n      is automatically created from the estimate job.\n    - The new regular job's estimate_job_id references the estimate job it came from.\n    - The estimate and photos are moved to the new regular job.\n    - The old non-scheduled path (create estimate without scheduling) still works\n      with the existing Path 2 behavior.\n*/\n\nCREATE OR REPLACE FUNCTION try_convert_lead_to_job(p_lead_id uuid)\nRETURNS void\nLANGUAGE plpgsql\nSECURITY DEFINER\nSET search_path = public\nAS $$\nDECLARE\n  _lead record;
\n  _has_accepted_estimate boolean;
\n  _has_photos boolean;
\n  _new_job_id uuid;
\nBEGIN\n  SELECT * INTO _lead FROM leads WHERE id = p_lead_id;
\n\n  IF _lead IS NULL THEN\n    RETURN;
\n  END IF;
\n\n  SELECT EXISTS (\n    SELECT 1 FROM estimates WHERE job_id = p_lead_id AND status = 'accepted'\n  ) INTO _has_accepted_estimate;
\n\n  SELECT EXISTS (\n    SELECT 1 FROM lead_photos WHERE lead_id = p_lead_id\n  ) INTO _has_photos;
\n\n  IF NOT (_has_accepted_estimate AND _has_photos) THEN\n    RETURN;
\n  END IF;
\n\n  IF _lead.is_estimate_visit = true AND _lead.status = 'job' THEN\n    INSERT INTO leads (\n      name, status, service_type, address, city, state,\n      customer_id, account_id, created_by,\n      approval_status, is_estimate_visit, estimate_job_id,\n      estimated_value, phone, email, source\n    )\n    VALUES (\n      REPLACE(_lead.name, ', Estimate', ''),\n      'job',\n      _lead.service_type,\n      _lead.address,\n      _lead.city,\n      _lead.state,\n      _lead.customer_id,\n      _lead.account_id,\n      _lead.created_by,\n      'pending',\n      false,\n      p_lead_id,\n      _lead.estimated_value,\n      _lead.phone,\n      _lead.email,\n      _lead.source\n    )\n    RETURNING id INTO _new_job_id;
\n\n    UPDATE estimates SET job_id = _new_job_id WHERE job_id = p_lead_id;
\n\n    UPDATE lead_photos SET lead_id = _new_job_id WHERE lead_id = p_lead_id;
\n\n    UPDATE leads SET approval_status = 'approved' WHERE id = _new_job_id;
\n\n    UPDATE job_schedules\n    SET is_completed = true, completed_at = now()\n    WHERE lead_id = p_lead_id;
\n\n    UPDATE leads SET status = 'completed' WHERE id = p_lead_id;
\n\n    INSERT INTO interactions (lead_id, type, direction, summary)\n    VALUES (\n      _new_job_id,\n      'status_change',\n      'na',\n      'Job created from completed estimate visit'\n    );
\n\n    RETURN;
\n  END IF;
\n\n  IF _lead.status IN ('job', 'paid', 'completed') THEN\n    RETURN;
\n  END IF;
\n\n  UPDATE leads SET status = 'job' WHERE id = p_lead_id;
\n\n  IF _lead.estimate_job_id IS NOT NULL THEN\n    UPDATE leads SET status = 'paid' WHERE id = _lead.estimate_job_id;
\n  END IF;
\n\n  INSERT INTO interactions (lead_id, type, direction, summary)\n  VALUES (\n    p_lead_id,\n    'status_change',\n    'na',\n    'Converted to job (estimate approved + photos uploaded)'\n  );
\nEND;
\n$$;
\n\nCREATE OR REPLACE FUNCTION public.cleanup_estimate_job_on_lead_delete()\nRETURNS trigger\nLANGUAGE plpgsql\nSECURITY DEFINER\nSET search_path = public\nAS $function$\nBEGIN\n  IF OLD.estimate_job_id IS NOT NULL\n    AND OLD.status NOT IN ('job', 'paid', 'completed') THEN\n    DELETE FROM public.leads WHERE id = OLD.estimate_job_id;
\n  END IF;
\n  RETURN OLD;
\nEND;
\n$function$;
\n;
