/*\n  # Transfer client_share_token when estimate job converts to regular job\n\n  1. Modified Functions\n    - `try_convert_lead_to_job(lead_id uuid)` - When creating a new regular job\n      from an estimate visit, the client_share_token is now transferred from the\n      estimate job to the new regular job. This ensures clients always see the\n      same portal link regardless of whether the job started as an estimate visit.\n\n  2. Important Notes\n    - The client_share_token has a UNIQUE constraint, so it must be cleared from\n      the estimate job before being set on the new job.\n    - This prevents the issue where estimate jobs and regular jobs had different\n      client portal links.\n*/\n\nCREATE OR REPLACE FUNCTION try_convert_lead_to_job(p_lead_id uuid)\nRETURNS void\nLANGUAGE plpgsql\nSECURITY DEFINER\nSET search_path = public\nAS $$\nDECLARE\n  _lead record;
\n  _has_accepted_estimate boolean;
\n  _has_photos boolean;
\n  _new_job_id uuid;
\nBEGIN\n  SELECT * INTO _lead FROM leads WHERE id = p_lead_id;
\n\n  IF _lead IS NULL THEN\n    RETURN;
\n  END IF;
\n\n  SELECT EXISTS (\n    SELECT 1 FROM estimates WHERE job_id = p_lead_id AND status = 'accepted'\n  ) INTO _has_accepted_estimate;
\n\n  SELECT EXISTS (\n    SELECT 1 FROM lead_photos WHERE lead_id = p_lead_id\n  ) INTO _has_photos;
\n\n  IF NOT (_has_accepted_estimate AND _has_photos) THEN\n    RETURN;
\n  END IF;
\n\n  IF _lead.is_estimate_visit = true AND _lead.status = 'job' THEN\n    INSERT INTO leads (\n      name, status, service_type, address, city, state,\n      customer_id, account_id, created_by,\n      approval_status, is_estimate_visit, estimate_job_id,\n      estimated_value, phone, email, source\n    )\n    VALUES (\n      REPLACE(_lead.name, ', Estimate', ''),\n      'job',\n      _lead.service_type,\n      _lead.address,\n      _lead.city,\n      _lead.state,\n      _lead.customer_id,\n      _lead.account_id,\n      _lead.created_by,\n      'pending',\n      false,\n      p_lead_id,\n      _lead.estimated_value,\n      _lead.phone,\n      _lead.email,\n      _lead.source\n    )\n    RETURNING id INTO _new_job_id;
\n\n    UPDATE estimates SET job_id = _new_job_id WHERE job_id = p_lead_id;
\n\n    UPDATE lead_photos SET lead_id = _new_job_id WHERE lead_id = p_lead_id;
\n\n    UPDATE leads SET approval_status = 'approved' WHERE id = _new_job_id;
\n\n    IF _lead.client_share_token IS NOT NULL THEN\n      UPDATE leads SET client_share_token = NULL WHERE id = p_lead_id;
\n      UPDATE leads SET client_share_token = _lead.client_share_token WHERE id = _new_job_id;
\n    END IF;
\n\n    UPDATE job_schedules\n    SET is_completed = true, completed_at = now()\n    WHERE lead_id = p_lead_id;
\n\n    UPDATE leads SET status = 'completed' WHERE id = p_lead_id;
\n\n    INSERT INTO interactions (lead_id, type, direction, summary)\n    VALUES (\n      _new_job_id,\n      'status_change',\n      'na',\n      'Job created from completed estimate visit'\n    );
\n\n    RETURN;
\n  END IF;
\n\n  IF _lead.status IN ('job', 'paid', 'completed') THEN\n    RETURN;
\n  END IF;
\n\n  UPDATE leads SET status = 'job' WHERE id = p_lead_id;
\n\n  IF _lead.estimate_job_id IS NOT NULL THEN\n    UPDATE leads SET status = 'paid' WHERE id = _lead.estimate_job_id;
\n  END IF;
\n\n  INSERT INTO interactions (lead_id, type, direction, summary)\n  VALUES (\n    p_lead_id,\n    'status_change',\n    'na',\n    'Converted to job (estimate approved + photos uploaded)'\n  );
\nEND;
\n$$;
\n;
