/*\n  # Restrict Crew Member Access to Related Job Data\n\n  1. Problem\n    - Current policies allow all account members to view customers, estimates, lead_photos, and interactions\n    - Crew members should only see data related to jobs they are assigned to\n\n  2. Solution\n    - Update SELECT policies for customers, estimates, lead_photos, and interactions\n    - Only allow crew members to see data for jobs they're assigned to\n    - Allow other roles to see all data in their account\n\n  3. Security\n    - Crew members can only view data related to their assigned jobs\n    - Maintains proper data isolation for different user roles\n*/\n\n-- Restrict customers access\nDROP POLICY IF EXISTS "Account members can view customers" ON customers;
\n\nCREATE POLICY "Account members can view customers"\n  ON customers FOR SELECT\n  TO authenticated\n  USING (\n    -- Managers and sales can see all customers in their account\n    account_id IN (\n      SELECT am.account_id FROM account_members am\n      WHERE am.user_id = auth.uid() \n      AND am.is_active = true\n      AND am.role IN ('owner', 'admin', 'sales', 'crew_lead')\n    )\n    OR\n    -- Crew members can only see customers for their assigned jobs\n    (\n      EXISTS (\n        SELECT 1 FROM account_members am\n        WHERE am.user_id = auth.uid()\n        AND am.is_active = true\n        AND am.role = 'crew_member'\n      )\n      AND id IN (\n        SELECT DISTINCT l.customer_id\n        FROM leads l\n        JOIN job_assignments ja ON ja.lead_id = l.id\n        WHERE ja.user_id = auth.uid()\n        AND l.customer_id IS NOT NULL\n      )\n    )\n  );
\n\n-- Restrict estimates access\nDROP POLICY IF EXISTS "Account members can view estimates" ON estimates;
\n\nCREATE POLICY "Account members can view estimates"\n  ON estimates FOR SELECT\n  TO authenticated\n  USING (\n    -- Managers and sales can see all estimates in their account\n    account_id IN (\n      SELECT am.account_id FROM account_members am\n      WHERE am.user_id = auth.uid() \n      AND am.is_active = true\n      AND am.role IN ('owner', 'admin', 'sales', 'crew_lead')\n    )\n    OR\n    -- Crew members can only see estimates for their assigned jobs (job_id references leads.id)\n    (\n      EXISTS (\n        SELECT 1 FROM account_members am\n        WHERE am.user_id = auth.uid()\n        AND am.is_active = true\n        AND am.role = 'crew_member'\n      )\n      AND job_id IN (\n        SELECT ja.lead_id\n        FROM job_assignments ja\n        WHERE ja.user_id = auth.uid()\n        AND ja.lead_id IS NOT NULL\n      )\n    )\n  );
\n\n-- Restrict lead_photos access\nDROP POLICY IF EXISTS "Account members can view lead photos" ON lead_photos;
\n\nCREATE POLICY "Account members can view lead photos"\n  ON lead_photos FOR SELECT\n  TO authenticated\n  USING (\n    -- Managers and sales can see all photos in their account\n    account_id IN (\n      SELECT am.account_id FROM account_members am\n      WHERE am.user_id = auth.uid() \n      AND am.is_active = true\n      AND am.role IN ('owner', 'admin', 'sales', 'crew_lead')\n    )\n    OR\n    -- Crew members can only see photos for their assigned jobs\n    (\n      EXISTS (\n        SELECT 1 FROM account_members am\n        WHERE am.user_id = auth.uid()\n        AND am.is_active = true\n        AND am.role = 'crew_member'\n      )\n      AND lead_id IN (\n        SELECT ja.lead_id\n        FROM job_assignments ja\n        WHERE ja.user_id = auth.uid()\n        AND ja.lead_id IS NOT NULL\n      )\n    )\n  );
\n\n-- Restrict interactions access\nDROP POLICY IF EXISTS "Account members can view interactions" ON interactions;
\n\nCREATE POLICY "Account members can view interactions"\n  ON interactions FOR SELECT\n  TO authenticated\n  USING (\n    -- Managers and sales can see all interactions in their account\n    account_id IN (\n      SELECT am.account_id FROM account_members am\n      WHERE am.user_id = auth.uid() \n      AND am.is_active = true\n      AND am.role IN ('owner', 'admin', 'sales', 'crew_lead')\n    )\n    OR\n    -- Crew members can only see interactions for their assigned jobs\n    (\n      EXISTS (\n        SELECT 1 FROM account_members am\n        WHERE am.user_id = auth.uid()\n        AND am.is_active = true\n        AND am.role = 'crew_member'\n      )\n      AND lead_id IN (\n        SELECT ja.lead_id\n        FROM job_assignments ja\n        WHERE ja.user_id = auth.uid()\n        AND ja.lead_id IS NOT NULL\n      )\n    )\n  );
;
