/*\n  # Fix mutable search_path on trigger functions\n\n  1. Security Changes\n    - Set explicit `search_path = public` on 9 trigger functions\n    - Prevents search_path injection attacks\n\n  2. Affected Functions\n    - notify_sms_new_lead\n    - notify_sms_payment\n    - notify_sms_schedule_change\n    - notify_sms_lead_update\n    - notify_new_lead\n    - notify_lead_status_change\n    - notify_payment_received\n    - notify_job_scheduled\n    - notify_estimate_approved\n*/\n\nALTER FUNCTION public.notify_sms_new_lead() SET search_path = public;
\nALTER FUNCTION public.notify_sms_payment() SET search_path = public;
\nALTER FUNCTION public.notify_sms_schedule_change() SET search_path = public;
\nALTER FUNCTION public.notify_sms_lead_update() SET search_path = public;
\nALTER FUNCTION public.notify_new_lead() SET search_path = public;
\nALTER FUNCTION public.notify_lead_status_change() SET search_path = public;
\nALTER FUNCTION public.notify_payment_received() SET search_path = public;
\nALTER FUNCTION public.notify_job_scheduled() SET search_path = public;
\nALTER FUNCTION public.notify_estimate_approved() SET search_path = public;
\n;
