/*\n  # Add foreign key indexes, fix RLS performance, and fix function search path\n\n  1. Foreign Key Indexes\n    - Adds covering indexes for 32 unindexed foreign keys across all tables\n    - Improves JOIN and CASCADE performance for these relationships\n\n  2. RLS Policy Performance\n    - Replaces `auth.uid()` with `(select auth.uid())` in policies on:\n      - `email_digest_log` (1 policy)\n      - `lead_photos` (3 policies)\n      - `notifications` (3 policies)\n    - This ensures `auth.uid()` is evaluated once per query instead of per row\n\n  3. Function Fix\n    - Sets `search_path = public` on `notify_sms_job_assignment` to prevent\n      mutable search_path security issue\n\n  4. Notes\n    - All indexes use IF NOT EXISTS to be idempotent\n    - RLS policies are dropped and recreated with the optimized pattern\n    - No data changes are made\n*/\n\n-- ==========================================================\n-- 1. Foreign Key Indexes\n-- ==========================================================\n\nCREATE INDEX IF NOT EXISTS idx_account_members_invited_by ON account_members(invited_by);
\nCREATE INDEX IF NOT EXISTS idx_api_keys_account_id ON api_keys(account_id);
\nCREATE INDEX IF NOT EXISTS idx_customers_account_id ON customers(account_id);
\nCREATE INDEX IF NOT EXISTS idx_customers_lead_id ON customers(lead_id);
\nCREATE INDEX IF NOT EXISTS idx_days_off_created_by ON days_off(created_by);
\nCREATE INDEX IF NOT EXISTS idx_estimate_change_orders_account_id ON estimate_change_orders(account_id);
\nCREATE INDEX IF NOT EXISTS idx_estimate_change_orders_changed_by ON estimate_change_orders(changed_by);
\nCREATE INDEX IF NOT EXISTS idx_estimate_line_items_account_id ON estimate_line_items(account_id);
\nCREATE INDEX IF NOT EXISTS idx_estimate_line_items_original_line_item_id ON estimate_line_items(original_line_item_id);
\nCREATE INDEX IF NOT EXISTS idx_estimates_created_by ON estimates(created_by);
\nCREATE INDEX IF NOT EXISTS idx_interactions_account_id ON interactions(account_id);
\nCREATE INDEX IF NOT EXISTS idx_invoice_line_items_account_id ON invoice_line_items(account_id);
\nCREATE INDEX IF NOT EXISTS idx_invoice_line_items_invoice_id ON invoice_line_items(invoice_id);
\nCREATE INDEX IF NOT EXISTS idx_job_assignments_account_id ON job_assignments(account_id);
\nCREATE INDEX IF NOT EXISTS idx_job_assignments_assigned_by ON job_assignments(assigned_by);
\nCREATE INDEX IF NOT EXISTS idx_job_schedules_created_by ON job_schedules(created_by);
\nCREATE INDEX IF NOT EXISTS idx_lead_photos_uploaded_by ON lead_photos(uploaded_by);
\nCREATE INDEX IF NOT EXISTS idx_lead_qualifications_account_id ON lead_qualifications(account_id);
\nCREATE INDEX IF NOT EXISTS idx_leads_customer_id ON leads(customer_id);
\nCREATE INDEX IF NOT EXISTS idx_leads_estimate_job_id ON leads(estimate_job_id);
\nCREATE INDEX IF NOT EXISTS idx_material_items_account_id ON material_items(account_id);
\nCREATE INDEX IF NOT EXISTS idx_material_items_material_list_id ON material_items(material_list_id);
\nCREATE INDEX IF NOT EXISTS idx_payments_invoice_id ON payments(invoice_id);
\nCREATE INDEX IF NOT EXISTS idx_pricing_rules_account_id ON pricing_rules(account_id);
\nCREATE INDEX IF NOT EXISTS idx_quick_estimates_account_id ON quick_estimates(account_id);
\nCREATE INDEX IF NOT EXISTS idx_stripe_connect_accounts_account_id ON stripe_connect_accounts(account_id);
\nCREATE INDEX IF NOT EXISTS idx_supply_order_items_account_id ON supply_order_items(account_id);
\nCREATE INDEX IF NOT EXISTS idx_supply_order_items_material_item_id ON supply_order_items(material_item_id);
\nCREATE INDEX IF NOT EXISTS idx_supply_order_items_supply_order_id ON supply_order_items(supply_order_id);
\nCREATE INDEX IF NOT EXISTS idx_supply_orders_material_list_id ON supply_orders(material_list_id);
\nCREATE INDEX IF NOT EXISTS idx_webhook_events_invoice_id ON webhook_events(invoice_id);
\nCREATE INDEX IF NOT EXISTS idx_webhook_events_payment_id ON webhook_events(payment_id);
\n\n-- ==========================================================\n-- 2. Fix RLS policies to use (select auth.uid()) pattern\n-- ==========================================================\n\n-- email_digest_log\nDROP POLICY IF EXISTS "Account members can view digest logs" ON email_digest_log;
\nCREATE POLICY "Account members can view digest logs"\n  ON email_digest_log FOR SELECT\n  TO authenticated\n  USING (\n    EXISTS (\n      SELECT 1 FROM account_members\n      WHERE account_members.account_id = email_digest_log.account_id\n      AND account_members.user_id = (select auth.uid())\n    )\n  );
\n\n-- lead_photos\nDROP POLICY IF EXISTS "Account members can view lead photos" ON lead_photos;
\nCREATE POLICY "Account members can view lead photos"\n  ON lead_photos FOR SELECT\n  TO authenticated\n  USING (\n    EXISTS (\n      SELECT 1 FROM account_members\n      WHERE account_members.account_id = lead_photos.account_id\n      AND account_members.user_id = (select auth.uid())\n      AND account_members.is_active = true\n    )\n  );
\n\nDROP POLICY IF EXISTS "Account members can insert lead photos" ON lead_photos;
\nCREATE POLICY "Account members can insert lead photos"\n  ON lead_photos FOR INSERT\n  TO authenticated\n  WITH CHECK (\n    uploaded_by = (select auth.uid())\n    AND EXISTS (\n      SELECT 1 FROM account_members\n      WHERE account_members.account_id = lead_photos.account_id\n      AND account_members.user_id = (select auth.uid())\n      AND account_members.is_active = true\n    )\n  );
\n\nDROP POLICY IF EXISTS "Uploaders can delete own lead photos" ON lead_photos;
\nCREATE POLICY "Uploaders can delete own lead photos"\n  ON lead_photos FOR DELETE\n  TO authenticated\n  USING (uploaded_by = (select auth.uid()));
\n\n-- notifications\nDROP POLICY IF EXISTS "Users can view own notifications" ON notifications;
\nCREATE POLICY "Users can view own notifications"\n  ON notifications FOR SELECT\n  TO authenticated\n  USING (user_id = (select auth.uid()));
\n\nDROP POLICY IF EXISTS "Users can update own notifications" ON notifications;
\nCREATE POLICY "Users can update own notifications"\n  ON notifications FOR UPDATE\n  TO authenticated\n  USING (user_id = (select auth.uid()))\n  WITH CHECK (user_id = (select auth.uid()));
\n\nDROP POLICY IF EXISTS "Users can delete own notifications" ON notifications;
\nCREATE POLICY "Users can delete own notifications"\n  ON notifications FOR DELETE\n  TO authenticated\n  USING (user_id = (select auth.uid()));
\n\n-- ==========================================================\n-- 3. Fix notify_sms_job_assignment search path\n-- ==========================================================\n\nCREATE OR REPLACE FUNCTION notify_sms_job_assignment()\nRETURNS trigger\nLANGUAGE plpgsql\nSECURITY DEFINER\nSET search_path = public\nAS $$\nDECLARE\n  _lead_name text;
\nBEGIN\n  SELECT name INTO _lead_name FROM leads WHERE id = NEW.lead_id;
\n\n  PERFORM net.http_post(\n    url := 'https://knjbakdhjspftwqrzzcl.supabase.co/functions/v1/send-sms',\n    headers := '{"Content-Type": "application/json"}'::jsonb,\n    body := jsonb_build_object(\n      'event_type', 'job_assignments',\n      'account_id', NEW.account_id::text,\n      'data', jsonb_build_object(\n        'lead_id', NEW.lead_id::text,\n        'lead_name', COALESCE(_lead_name, 'Job'),\n        'user_id', NEW.user_id::text,\n        'action', 'assigned'\n      )\n    )\n  );
\n  RETURN NEW;
\nEND;
\n$$;
;
