/*\n  # Fix Remaining Security and Performance Issues\n\n  ## 1. Add Foreign Key Indexes (25)\n    - Re-add indexes for foreign keys that were previously dropped as unused\n    - These are needed for join performance even if not directly queried\n\n  ## 2. Drop Unused Indexes (6)\n    - Remove indexes created in previous migration that are not being used\n\n  ## 3. Fix Duplicate Function Overloads\n    - Drop old get_user_roles() (no args) that lacks search_path\n    - Drop old has_role(uuid, app_role) that lacks search_path\n\n  ## 4. Consolidate Multiple Permissive UPDATE Policies\n    - Merge two UPDATE policies on lead_source_connections into one\n\n  ## 5. Fix Security Definer View\n    - Recreate account_members_with_profiles with SECURITY INVOKER\n*/\n\n-- ============================================================================\n-- 1. Add Missing Foreign Key Indexes\n-- ============================================================================\n\nCREATE INDEX IF NOT EXISTS idx_account_members_invited_by ON account_members(invited_by);
\nCREATE INDEX IF NOT EXISTS idx_api_keys_account_id ON api_keys(account_id);
\nCREATE INDEX IF NOT EXISTS idx_customers_account_id ON customers(account_id);
\nCREATE INDEX IF NOT EXISTS idx_customers_lead_id ON customers(lead_id);
\nCREATE INDEX IF NOT EXISTS idx_estimate_change_orders_account_id ON estimate_change_orders(account_id);
\nCREATE INDEX IF NOT EXISTS idx_estimate_line_items_account_id ON estimate_line_items(account_id);
\nCREATE INDEX IF NOT EXISTS idx_estimates_created_by ON estimates(created_by);
\nCREATE INDEX IF NOT EXISTS idx_interactions_account_id ON interactions(account_id);
\nCREATE INDEX IF NOT EXISTS idx_invoice_line_items_account_id ON invoice_line_items(account_id);
\nCREATE INDEX IF NOT EXISTS idx_invoice_line_items_invoice_id ON invoice_line_items(invoice_id);
\nCREATE INDEX IF NOT EXISTS idx_job_assignments_account_id ON job_assignments(account_id);
\nCREATE INDEX IF NOT EXISTS idx_lead_qualifications_account_id ON lead_qualifications(account_id);
\nCREATE INDEX IF NOT EXISTS idx_leads_customer_id ON leads(customer_id);
\nCREATE INDEX IF NOT EXISTS idx_material_items_account_id ON material_items(account_id);
\nCREATE INDEX IF NOT EXISTS idx_material_items_material_list_id ON material_items(material_list_id);
\nCREATE INDEX IF NOT EXISTS idx_payments_invoice_id ON payments(invoice_id);
\nCREATE INDEX IF NOT EXISTS idx_pricing_rules_account_id ON pricing_rules(account_id);
\nCREATE INDEX IF NOT EXISTS idx_quick_estimates_account_id ON quick_estimates(account_id);
\nCREATE INDEX IF NOT EXISTS idx_stripe_connect_accounts_account_id ON stripe_connect_accounts(account_id);
\nCREATE INDEX IF NOT EXISTS idx_supply_order_items_account_id ON supply_order_items(account_id);
\nCREATE INDEX IF NOT EXISTS idx_supply_order_items_material_item_id ON supply_order_items(material_item_id);
\nCREATE INDEX IF NOT EXISTS idx_supply_order_items_supply_order_id ON supply_order_items(supply_order_id);
\nCREATE INDEX IF NOT EXISTS idx_supply_orders_material_list_id ON supply_orders(material_list_id);
\nCREATE INDEX IF NOT EXISTS idx_webhook_events_invoice_id ON webhook_events(invoice_id);
\nCREATE INDEX IF NOT EXISTS idx_webhook_events_payment_id ON webhook_events(payment_id);
\n\n-- ============================================================================\n-- 2. Drop Unused Indexes\n-- ============================================================================\n\nDROP INDEX IF EXISTS idx_days_off_created_by;
\nDROP INDEX IF EXISTS idx_job_assignments_schedule;
\nDROP INDEX IF EXISTS idx_estimate_change_orders_changed_by;
\nDROP INDEX IF EXISTS idx_estimate_line_items_original_line_item_id;
\nDROP INDEX IF EXISTS idx_job_assignments_assigned_by;
\nDROP INDEX IF EXISTS idx_job_schedules_created_by;
\n\n-- ============================================================================\n-- 3. Drop Old Function Overloads Without search_path\n-- ============================================================================\n\nDROP FUNCTION IF EXISTS get_user_roles() CASCADE;
\nDROP FUNCTION IF EXISTS has_role(uuid, app_role) CASCADE;
\n\n-- ============================================================================\n-- 4. Consolidate Multiple Permissive UPDATE Policies on lead_source_connections\n-- ============================================================================\n\nDROP POLICY IF EXISTS "Account owners and admins can update lead source connections" ON lead_source_connections;
\nDROP POLICY IF EXISTS "Users can update their own connections" ON lead_source_connections;
\n\nCREATE POLICY "Account owners and admins can update lead source connections"\n  ON lead_source_connections FOR UPDATE\n  TO authenticated\n  USING (\n    EXISTS (\n      SELECT 1 FROM account_members\n      WHERE account_members.account_id = lead_source_connections.account_id\n      AND account_members.user_id = (select auth.uid())\n      AND account_members.role IN ('owner', 'admin')\n    )\n  )\n  WITH CHECK (\n    EXISTS (\n      SELECT 1 FROM account_members\n      WHERE account_members.account_id = lead_source_connections.account_id\n      AND account_members.user_id = (select auth.uid())\n      AND account_members.role IN ('owner', 'admin')\n    )\n  );
\n\n-- ============================================================================\n-- 5. Fix Security Definer View\n-- ============================================================================\n\nDROP VIEW IF EXISTS account_members_with_profiles;
\nCREATE VIEW account_members_with_profiles\nWITH (security_invoker = true)\nAS\nSELECT \n  am.account_id,\n  am.user_id,\n  am.role,\n  am.invited_by,\n  am.invited_at,\n  am.joined_at,\n  p.full_name,\n  p.email,\n  p.phone,\n  p.avatar_url\nFROM account_members am\nLEFT JOIN profiles p ON am.user_id = p.id;
;
