/*\n  # Update auto-convert trigger to mark estimate job as paid\n\n  1. Modified Functions\n    - `try_convert_lead_to_job(lead_id uuid)` - now also sets the associated\n      estimate job's status to 'paid' when the original lead is auto-converted\n      to a job\n\n  2. Important Notes\n    - When a lead has an `estimate_job_id`, the estimate job is marked as 'paid'\n      at the same time the lead is converted to 'job'\n    - This ensures the estimate visit job is properly closed regardless of\n      whether conversion happens via the UI button or the auto-convert trigger\n*/\n\nCREATE OR REPLACE FUNCTION try_convert_lead_to_job(p_lead_id uuid)\nRETURNS void\nLANGUAGE plpgsql\nSECURITY DEFINER\nSET search_path = public\nAS $$\nDECLARE\n  _lead_status text;
\n  _has_accepted_estimate boolean;
\n  _has_photos boolean;
\n  _estimate_job_id uuid;
\nBEGIN\n  SELECT status, estimate_job_id INTO _lead_status, _estimate_job_id\n  FROM leads\n  WHERE id = p_lead_id;
\n\n  IF _lead_status IS NULL OR _lead_status IN ('job', 'paid') THEN\n    RETURN;
\n  END IF;
\n\n  SELECT EXISTS (\n    SELECT 1 FROM estimates\n    WHERE job_id = p_lead_id AND status = 'accepted'\n  ) INTO _has_accepted_estimate;
\n\n  SELECT EXISTS (\n    SELECT 1 FROM lead_photos\n    WHERE lead_id = p_lead_id\n  ) INTO _has_photos;
\n\n  IF _has_accepted_estimate AND _has_photos THEN\n    UPDATE leads SET status = 'job' WHERE id = p_lead_id;
\n\n    IF _estimate_job_id IS NOT NULL THEN\n      UPDATE leads SET status = 'paid' WHERE id = _estimate_job_id;
\n    END IF;
\n\n    INSERT INTO interactions (lead_id, type, direction, summary)\n    VALUES (\n      p_lead_id,\n      'status_change',\n      'na',\n      'Converted to job (estimate approved + photos uploaded)'\n    );
\n  END IF;
\nEND;
\n$$;
\n;
