/*\n  # Fix mention notification columns\n\n  1. Updates\n    - Fix the `handle_mention_notifications()` function to use correct column names\n    - Use `body` instead of `message`\n    - Use `event_type` instead of `type`\n    - Use `reference_id` and `reference_type` instead of `link` and `metadata`\n\n  2. Important Notes\n    - This ensures notifications are created with the correct schema\n*/\n\nCREATE OR REPLACE FUNCTION handle_mention_notifications()\nRETURNS trigger\nLANGUAGE plpgsql\nSECURITY DEFINER\nSET search_path = public\nAS $$\nDECLARE\n  mentioned_user_id uuid;
\n  mentioned_user_ids uuid[];
\n  lead_data record;
\n  author_name text;
\nBEGIN\n  IF NEW.type != 'note' THEN\n    RETURN NEW;
\n  END IF;
\n\n  mentioned_user_ids := extract_mentioned_users(COALESCE(NEW.body, NEW.summary, ''));
\n\n  IF array_length(mentioned_user_ids, 1) IS NULL OR array_length(mentioned_user_ids, 1) = 0 THEN\n    RETURN NEW;
\n  END IF;
\n\n  SELECT name, customer_id INTO lead_data\n  FROM leads\n  WHERE id = NEW.lead_id;
\n\n  SELECT full_name INTO author_name\n  FROM profiles\n  WHERE user_id = NEW.created_by\n  LIMIT 1;
\n\n  FOREACH mentioned_user_id IN ARRAY mentioned_user_ids\n  LOOP\n    IF mentioned_user_id != NEW.created_by THEN\n      INSERT INTO notifications (\n        user_id,\n        account_id,\n        event_type,\n        title,\n        body,\n        reference_id,\n        reference_type\n      )\n      SELECT\n        mentioned_user_id,\n        NEW.account_id,\n        'mention',\n        COALESCE(author_name, 'Someone') || ' mentioned you in a note',\n        substring(regexp_replace(COALESCE(NEW.body, NEW.summary, ''), '@\\[([^\\]]+)\\]\\([a-f0-9-]+\\)', '@\\1', 'g'), 1, 200),\n        NEW.lead_id,\n        'lead'\n      FROM profiles\n      WHERE user_id = mentioned_user_id\n        AND mention_notifications_enabled = true;
\n    END IF;
\n  END LOOP;
\n\n  RETURN NEW;
\nEND;
\n$$;
;
