/*\n  # Add mention notification trigger\n\n  1. New Functions\n    - `extract_mentioned_users(text)` - Extracts user IDs from @mentions in text\n    - `handle_mention_notifications()` - Trigger function that creates notifications for mentioned users\n\n  2. New Triggers\n    - `trigger_mention_notifications` on `interactions` - Fires when a note is created with mentions\n\n  3. Important Notes\n    - Mentions use the format @[Name](user-id)\n    - Only sends notifications to users who have mention_notifications_enabled = true\n    - Creates a notification for each mentioned user\n    - Only triggers for 'note' type interactions\n*/\n\nCREATE OR REPLACE FUNCTION extract_mentioned_users(note_text text)\nRETURNS uuid[]\nLANGUAGE plpgsql\nIMMUTABLE\nAS $$\nDECLARE\n  user_ids uuid[];
\n  match_array text[];
\nBEGIN\n  SELECT array_agg(DISTINCT m[2]::uuid)\n  INTO user_ids\n  FROM regexp_matches(note_text, '@\\[([^\\]]+)\\]\\(([a-f0-9-]+)\\)', 'g') AS m\n  WHERE m[2] ~ '^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$';
\n  \n  RETURN COALESCE(user_ids, ARRAY[]::uuid[]);
\nEND;
\n$$;
\n\nCREATE OR REPLACE FUNCTION handle_mention_notifications()\nRETURNS trigger\nLANGUAGE plpgsql\nSECURITY DEFINER\nSET search_path = public\nAS $$\nDECLARE\n  mentioned_user_id uuid;
\n  mentioned_user_ids uuid[];
\n  lead_data record;
\n  author_name text;
\nBEGIN\n  IF NEW.type != 'note' THEN\n    RETURN NEW;
\n  END IF;
\n\n  mentioned_user_ids := extract_mentioned_users(COALESCE(NEW.body, NEW.summary, ''));
\n\n  IF array_length(mentioned_user_ids, 1) IS NULL OR array_length(mentioned_user_ids, 1) = 0 THEN\n    RETURN NEW;
\n  END IF;
\n\n  SELECT name, customer_id INTO lead_data\n  FROM leads\n  WHERE id = NEW.lead_id;
\n\n  SELECT full_name INTO author_name\n  FROM profiles\n  WHERE user_id = NEW.created_by\n  LIMIT 1;
\n\n  FOREACH mentioned_user_id IN ARRAY mentioned_user_ids\n  LOOP\n    IF mentioned_user_id != NEW.created_by THEN\n      INSERT INTO notifications (\n        user_id,\n        account_id,\n        type,\n        title,\n        message,\n        link,\n        metadata\n      )\n      SELECT\n        mentioned_user_id,\n        NEW.account_id,\n        'mention',\n        COALESCE(author_name, 'Someone') || ' mentioned you in a note',\n        substring(regexp_replace(COALESCE(NEW.body, NEW.summary, ''), '@\\[([^\\]]+)\\]\\([a-f0-9-]+\\)', '@\\1', 'g'), 1, 100),\n        '/jobs/' || NEW.lead_id,\n        jsonb_build_object(\n          'lead_id', NEW.lead_id,\n          'interaction_id', NEW.id,\n          'mentioned_by', NEW.created_by\n        )\n      FROM profiles\n      WHERE user_id = mentioned_user_id\n        AND mention_notifications_enabled = true;
\n    END IF;
\n  END LOOP;
\n\n  RETURN NEW;
\nEND;
\n$$;
\n\nDO $$\nBEGIN\n  IF NOT EXISTS (\n    SELECT 1 FROM pg_trigger WHERE tgname = 'trigger_mention_notifications'\n  ) THEN\n    CREATE TRIGGER trigger_mention_notifications\n      AFTER INSERT ON interactions\n      FOR EACH ROW\n      EXECUTE FUNCTION handle_mention_notifications();
\n  END IF;
\nEND $$;
\n;
