/*\n  # Consolidate Jobs and Leads into Single Unified Table\n  \n  ## Overview\n  This migration merges the jobs and leads tables into a single unified table.\n  Records will appear in either the "Leads" or "Jobs" view based on what fields are populated.\n  \n  ## Changes Made\n  \n  ### 1. Add Job Fields to Leads Table\n  - `customer_id` - Reference to customers table (nullable for early-stage leads)\n  - `scheduled_date` - When the job is scheduled\n  - `scheduled_time_start` - Start time for the job\n  - `scheduled_time_end` - End time for the job\n  - `actual_value` - Final job value after completion\n  - `crew_lead_id` - Assigned crew leader\n  - `description` - Detailed job description (separate from notes)\n  \n  ### 2. Create Unified Status Enum\n  - Combines lead_status and job_status into single enum\n  - Covers full lifecycle: new → contacted → qualified → scheduled → in_progress → completed/won/lost\n  \n  ### 3. Data Migration\n  - Migrate all existing jobs to leads table\n  - Update foreign keys in related tables (estimates, invoices, material_lists, payments, supply_orders)\n  \n  ### 4. Update Foreign Keys and Indexes\n  - Rename job_id to lead_id in all related tables\n  - Update indexes for performance\n  - Update RLS policies\n  \n  ### 5. Clean Up\n  - Drop the jobs table\n  - Remove old enums\n*/\n\n-- Step 1: Create unified status enum\nDO $$ BEGIN\n  CREATE TYPE public.unified_status AS ENUM (\n    'new',\n    'contacted',\n    'qualified',\n    'scheduled',\n    'in_progress',\n    'completed',\n    'won',\n    'lost',\n    'cancelled',\n    'on_hold',\n    'unqualified'\n  );
\nEXCEPTION\n  WHEN duplicate_object THEN NULL;
\nEND $$;
\n\n-- Step 2: Add job-related fields to leads table\nALTER TABLE public.leads\n  ADD COLUMN IF NOT EXISTS customer_id uuid REFERENCES public.customers(id),\n  ADD COLUMN IF NOT EXISTS scheduled_date date,\n  ADD COLUMN IF NOT EXISTS scheduled_time_start time without time zone,\n  ADD COLUMN IF NOT EXISTS scheduled_time_end time without time zone,\n  ADD COLUMN IF NOT EXISTS actual_value numeric(12,2),\n  ADD COLUMN IF NOT EXISTS crew_lead_id uuid REFERENCES auth.users(id),\n  ADD COLUMN IF NOT EXISTS description text;
\n\n-- Step 3: Add estimated_value column (rename from estimated_budget later)\nALTER TABLE public.leads\n  ADD COLUMN IF NOT EXISTS estimated_value numeric(12,2);
\n\n-- Step 4: Copy estimated_budget to estimated_value\nUPDATE public.leads SET estimated_value = estimated_budget WHERE estimated_value IS NULL;
\n\n-- Step 5: Add new_status column to hold unified status\nALTER TABLE public.leads\n  ADD COLUMN IF NOT EXISTS new_status public.unified_status;
\n\n-- Step 6: Map old lead statuses to new unified status\nUPDATE public.leads\nSET new_status = CASE \n  WHEN status = 'new' THEN 'new'::public.unified_status\n  WHEN status = 'contacted' THEN 'contacted'::public.unified_status\n  WHEN status = 'qualified' THEN 'qualified'::public.unified_status\n  WHEN status = 'scheduled' THEN 'scheduled'::public.unified_status\n  WHEN status = 'in_progress' THEN 'in_progress'::public.unified_status\n  WHEN status = 'won' THEN 'won'::public.unified_status\n  WHEN status = 'lost' THEN 'lost'::public.unified_status\n  WHEN status = 'unqualified' THEN 'unqualified'::public.unified_status\n  WHEN status = 'converted' THEN 'scheduled'::public.unified_status\n  ELSE 'new'::public.unified_status\nEND\nWHERE new_status IS NULL;
\n\n-- Step 7: Migrate jobs to leads table\nINSERT INTO public.leads (\n  id,\n  name,\n  phone,\n  address,\n  service_type,\n  estimated_value,\n  source,\n  notes,\n  new_status,\n  created_by,\n  created_at,\n  updated_at,\n  customer_id,\n  scheduled_date,\n  scheduled_time_start,\n  scheduled_time_end,\n  actual_value,\n  crew_lead_id,\n  description,\n  approval_status\n)\nSELECT \n  j.id,\n  j.name,\n  c.phone,\n  j.address,\n  j.service_type,\n  j.estimated_value,\n  'migrated_from_jobs' as source,\n  j.notes,\n  CASE \n    WHEN j.status = 'scheduled' THEN 'scheduled'::public.unified_status\n    WHEN j.status = 'in-progress' THEN 'in_progress'::public.unified_status\n    WHEN j.status = 'completed' THEN 'completed'::public.unified_status\n    WHEN j.status = 'cancelled' THEN 'cancelled'::public.unified_status\n    WHEN j.status = 'on-hold' THEN 'on_hold'::public.unified_status\n    ELSE 'scheduled'::public.unified_status\n  END as new_status,\n  j.created_by,\n  j.created_at,\n  j.updated_at,\n  j.customer_id,\n  j.scheduled_date,\n  j.scheduled_time_start,\n  j.scheduled_time_end,\n  j.actual_value,\n  j.crew_lead_id,\n  j.description,\n  'approved'\nFROM public.jobs j\nLEFT JOIN public.customers c ON c.id = j.customer_id\nWHERE NOT EXISTS (SELECT 1 FROM public.leads l WHERE l.id = j.id);
\n\n-- Step 8: Update foreign keys in related tables to point to leads\n-- We'll rename job_id columns to lead_id\n\n-- Estimates table\nALTER TABLE public.estimates\n  DROP CONSTRAINT IF EXISTS estimates_job_id_fkey;
\n\nALTER TABLE public.estimates\n  RENAME COLUMN job_id TO lead_id;
\n\nALTER TABLE public.estimates\n  ADD CONSTRAINT estimates_lead_id_fkey \n  FOREIGN KEY (lead_id) REFERENCES public.leads(id);
\n\n-- Invoices table\nALTER TABLE public.invoices\n  DROP CONSTRAINT IF EXISTS invoices_job_id_fkey;
\n\nALTER TABLE public.invoices\n  RENAME COLUMN job_id TO lead_id;
\n\nALTER TABLE public.invoices\n  ADD CONSTRAINT invoices_lead_id_fkey \n  FOREIGN KEY (lead_id) REFERENCES public.leads(id);
\n\n-- Material lists table\nALTER TABLE public.material_lists\n  DROP CONSTRAINT IF EXISTS material_lists_job_id_fkey;
\n\nALTER TABLE public.material_lists\n  RENAME COLUMN job_id TO lead_id;
\n\nALTER TABLE public.material_lists\n  ADD CONSTRAINT material_lists_lead_id_fkey \n  FOREIGN KEY (lead_id) REFERENCES public.leads(id);
\n\n-- Payments table\nALTER TABLE public.payments\n  DROP CONSTRAINT IF EXISTS payments_job_id_fkey;
\n\nALTER TABLE public.payments\n  RENAME COLUMN job_id TO lead_id;
\n\nALTER TABLE public.payments\n  ADD CONSTRAINT payments_lead_id_fkey \n  FOREIGN KEY (lead_id) REFERENCES public.leads(id);
\n\n-- Supply orders table\nALTER TABLE public.supply_orders\n  DROP CONSTRAINT IF EXISTS supply_orders_job_id_fkey;
\n\nALTER TABLE public.supply_orders\n  RENAME COLUMN job_id TO lead_id;
\n\nALTER TABLE public.supply_orders\n  ADD CONSTRAINT supply_orders_lead_id_fkey \n  FOREIGN KEY (lead_id) REFERENCES public.leads(id);
\n\n-- Step 9: Update indexes\nDROP INDEX IF EXISTS public.idx_estimates_job_id;
\nCREATE INDEX IF NOT EXISTS idx_estimates_lead_id ON public.estimates(lead_id);
\n\nDROP INDEX IF EXISTS public.idx_invoices_job_id;
\nCREATE INDEX IF NOT EXISTS idx_invoices_lead_id ON public.invoices(lead_id);
\n\nDROP INDEX IF EXISTS public.idx_material_lists_job_id;
\nCREATE INDEX IF NOT EXISTS idx_material_lists_lead_id ON public.material_lists(lead_id);
\n\nDROP INDEX IF EXISTS public.idx_supply_orders_job_id;
\nCREATE INDEX IF NOT EXISTS idx_supply_orders_lead_id ON public.supply_orders(lead_id);
\n\n-- Add new indexes for job-related queries on leads\nCREATE INDEX IF NOT EXISTS idx_leads_scheduled_date ON public.leads(scheduled_date);
\nCREATE INDEX IF NOT EXISTS idx_leads_crew_lead_id ON public.leads(crew_lead_id);
\nCREATE INDEX IF NOT EXISTS idx_leads_customer_id ON public.leads(customer_id);
\nCREATE INDEX IF NOT EXISTS idx_leads_new_status ON public.leads(new_status);
\n\n-- Step 10: Drop old status column and rename new_status\nALTER TABLE public.leads\n  DROP COLUMN IF EXISTS status;
\n\nALTER TABLE public.leads\n  RENAME COLUMN new_status TO status;
\n\n-- Set default and not null constraint\nALTER TABLE public.leads\n  ALTER COLUMN status SET DEFAULT 'new'::public.unified_status,\n  ALTER COLUMN status SET NOT NULL;
\n\n-- Step 11: Drop old columns from leads\nALTER TABLE public.leads\n  DROP COLUMN IF EXISTS estimated_budget;
\n\n-- Step 12: Drop the jobs table\nDROP TABLE IF EXISTS public.jobs CASCADE;
\n\n-- Step 13: Drop old enum types\nDROP TYPE IF EXISTS public.job_status CASCADE;
\nDROP TYPE IF EXISTS public.lead_status CASCADE;
\n\n-- Step 14: Update RLS policies\n-- Drop old job-related policies\nDROP POLICY IF EXISTS "Users can view jobs they created" ON public.leads;
\nDROP POLICY IF EXISTS "Users can create jobs" ON public.leads;
\nDROP POLICY IF EXISTS "Users can update jobs they created" ON public.leads;
\nDROP POLICY IF EXISTS "Crew leads can view and update their assigned jobs" ON public.leads;
\n\n-- Create unified policies for leads (which now include jobs)\nCREATE POLICY "Users can view their leads and jobs"\n  ON public.leads\n  FOR SELECT\n  TO authenticated\n  USING (\n    created_by = auth.uid() OR\n    crew_lead_id = auth.uid() OR\n    assigned_to = auth.uid()\n  );
\n\nCREATE POLICY "Users can create leads and jobs"\n  ON public.leads\n  FOR INSERT\n  TO authenticated\n  WITH CHECK (created_by = auth.uid());
\n\nCREATE POLICY "Users can update their leads and jobs"\n  ON public.leads\n  FOR UPDATE\n  TO authenticated\n  USING (\n    created_by = auth.uid() OR\n    crew_lead_id = auth.uid() OR\n    assigned_to = auth.uid()\n  )\n  WITH CHECK (\n    created_by = auth.uid() OR\n    crew_lead_id = auth.uid() OR\n    assigned_to = auth.uid()\n  );
\n\nCREATE POLICY "Users can delete their leads and jobs"\n  ON public.leads\n  FOR DELETE\n  TO authenticated\n  USING (created_by = auth.uid());
\n;
