/*\n  # Scope crew member notifications to assigned jobs only\n\n  1. Updated Functions\n    - `create_user_notifications` - now accepts optional `p_lead_id` parameter\n      - For crew members (role = 'crew_member'): only creates notification if they\n        are assigned to the referenced job via `job_assignments`\n      - For owners/admins/crew_leads: behavior unchanged (receive all notifications)\n    - `notify_job_scheduled` - now passes lead_id for crew scoping\n    - `notify_lead_status_change` - now passes lead_id for crew scoping\n\n  2. New Triggers\n    - `notify_job_assignment_change` - fires on INSERT/DELETE on `job_assignments`\n      - Creates in-app notification for the assigned/unassigned crew member\n      - Respects user notification preferences (alert key: job_assignments)\n    - `notify_sms_job_assignment` - fires on INSERT on `job_assignments`\n      - Sends SMS via send-sms edge function to notify assigned crew member\n\n  3. Notes\n    - Crew members will only receive schedule_change and lead_update notifications\n      for jobs they are assigned to\n    - Job assignment/unassignment notifications are sent directly to the affected user\n    - Owners, admins, and crew_leads continue to receive all notifications as before\n*/\n\n-- 1. Update create_user_notifications to scope crew to assigned jobs\nCREATE OR REPLACE FUNCTION create_user_notifications(\n  p_account_id uuid,\n  p_title text,\n  p_body text,\n  p_event_type text,\n  p_alert_key text,\n  p_reference_id uuid,\n  p_reference_type text,\n  p_lead_id uuid DEFAULT NULL\n) RETURNS void\nLANGUAGE plpgsql\nSECURITY DEFINER\nSET search_path = public\nAS $$\nDECLARE\n  _member RECORD;
\n  _prefs jsonb;
\n  _alert_enabled boolean;
\n  _is_crew boolean;
\n  _is_assigned boolean;
\nBEGIN\n  FOR _member IN\n    SELECT am.user_id, am.role, p.notification_preferences\n    FROM account_members am\n    LEFT JOIN profiles p ON p.user_id = am.user_id\n    WHERE am.account_id = p_account_id\n    AND am.is_active = true\n  LOOP\n    _is_crew := (_member.role = 'crew_member');
\n\n    IF _is_crew AND p_lead_id IS NOT NULL THEN\n      SELECT EXISTS(\n        SELECT 1 FROM job_assignments ja\n        WHERE ja.lead_id = p_lead_id\n        AND ja.user_id = _member.user_id\n      ) INTO _is_assigned;
\n\n      IF NOT _is_assigned THEN\n        CONTINUE;
\n      END IF;
\n    END IF;
\n\n    _prefs := _member.notification_preferences;
\n    _alert_enabled := true;
\n\n    IF _prefs IS NOT NULL\n       AND _prefs->'alerts' IS NOT NULL\n       AND _prefs->'alerts'->p_alert_key IS NOT NULL THEN\n      _alert_enabled := (_prefs->'alerts'->>p_alert_key)::boolean;
\n    END IF;
\n\n    IF _alert_enabled THEN\n      INSERT INTO notifications (account_id, user_id, title, body, event_type, reference_id, reference_type)\n      VALUES (p_account_id, _member.user_id, p_title, p_body, p_event_type, p_reference_id, p_reference_type);
\n    END IF;
\n  END LOOP;
\nEND;
\n$$;
\n\n-- 2. Update notify_job_scheduled to pass lead_id for crew scoping\nCREATE OR REPLACE FUNCTION notify_job_scheduled()\nRETURNS trigger\nLANGUAGE plpgsql\nSECURITY DEFINER\nSET search_path = public\nAS $$\nDECLARE\n  _lead_name text;
\nBEGIN\n  SELECT name INTO _lead_name FROM leads WHERE id = NEW.lead_id;
\n\n  PERFORM create_user_notifications(\n    NEW.account_id,\n    'Job Scheduled',\n    COALESCE(_lead_name, 'Job') || ' scheduled for ' || NEW.scheduled_date::text,\n    'schedule_change',\n    'schedule_changes',\n    NEW.lead_id,\n    'job_schedule',\n    NEW.lead_id\n  );
\n  RETURN NEW;
\nEND;
\n$$;
\n\n-- 3. Update notify_lead_status_change to pass lead_id for crew scoping\nCREATE OR REPLACE FUNCTION notify_lead_status_change()\nRETURNS trigger\nLANGUAGE plpgsql\nSECURITY DEFINER\nSET search_path = public\nAS $$\nBEGIN\n  IF OLD.status IS NOT DISTINCT FROM NEW.status THEN\n    RETURN NEW;
\n  END IF;
\n\n  PERFORM create_user_notifications(\n    NEW.account_id,\n    'Lead Status Updated',\n    COALESCE(NEW.name, 'Lead') || ' moved to ' || NEW.status::text,\n    'lead_status_change',\n    'lead_updates',\n    NEW.id,\n    'lead',\n    NEW.id\n  );
\n  RETURN NEW;
\nEND;
\n$$;
\n\n-- 4. Add trigger for job assignment in-app notifications\nCREATE OR REPLACE FUNCTION notify_job_assignment_change()\nRETURNS trigger\nLANGUAGE plpgsql\nSECURITY DEFINER\nSET search_path = public\nAS $$\nDECLARE\n  _lead_name text;
\n  _prefs jsonb;
\n  _alert_enabled boolean;
\n  _target_user_id uuid;
\n  _target_account_id uuid;
\n  _target_lead_id uuid;
\nBEGIN\n  IF TG_OP = 'INSERT' THEN\n    _target_user_id := NEW.user_id;
\n    _target_account_id := NEW.account_id;
\n    _target_lead_id := NEW.lead_id;
\n  ELSIF TG_OP = 'DELETE' THEN\n    _target_user_id := OLD.user_id;
\n    _target_account_id := OLD.account_id;
\n    _target_lead_id := OLD.lead_id;
\n  END IF;
\n\n  SELECT name INTO _lead_name FROM leads WHERE id = _target_lead_id;
\n\n  SELECT notification_preferences INTO _prefs\n  FROM profiles WHERE user_id = _target_user_id;
\n\n  _alert_enabled := true;
\n  IF _prefs IS NOT NULL\n     AND _prefs->'alerts' IS NOT NULL\n     AND _prefs->'alerts'->'job_assignments' IS NOT NULL THEN\n    _alert_enabled := (_prefs->'alerts'->>'job_assignments')::boolean;
\n  END IF;
\n\n  IF _alert_enabled THEN\n    INSERT INTO notifications (account_id, user_id, title, body, event_type, reference_id, reference_type)\n    VALUES (\n      _target_account_id,\n      _target_user_id,\n      CASE WHEN TG_OP = 'INSERT' THEN 'Job Assignment' ELSE 'Job Unassigned' END,\n      CASE WHEN TG_OP = 'INSERT'\n        THEN 'You have been assigned to ' || COALESCE(_lead_name, 'a job')\n        ELSE 'You have been removed from ' || COALESCE(_lead_name, 'a job')\n      END,\n      'job_assignment',\n      _target_lead_id,\n      'lead'\n    );
\n  END IF;
\n\n  IF TG_OP = 'INSERT' THEN\n    RETURN NEW;
\n  ELSE\n    RETURN OLD;
\n  END IF;
\nEND;
\n$$;
\n\nDROP TRIGGER IF EXISTS on_job_assignment_change ON job_assignments;
\nCREATE TRIGGER on_job_assignment_change\n  AFTER INSERT OR DELETE ON job_assignments\n  FOR EACH ROW EXECUTE FUNCTION notify_job_assignment_change();
\n\n-- 5. Add SMS trigger for job assignment notifications\nCREATE OR REPLACE FUNCTION notify_sms_job_assignment()\nRETURNS trigger\nLANGUAGE plpgsql\nSECURITY DEFINER\nAS $$\nDECLARE\n  _lead_name text;
\nBEGIN\n  SELECT name INTO _lead_name FROM leads WHERE id = NEW.lead_id;
\n\n  PERFORM net.http_post(\n    url := 'https://knjbakdhjspftwqrzzcl.supabase.co/functions/v1/send-sms',\n    headers := '{"Content-Type": "application/json"}'::jsonb,\n    body := jsonb_build_object(\n      'event_type', 'job_assignments',\n      'account_id', NEW.account_id::text,\n      'data', jsonb_build_object(\n        'lead_id', NEW.lead_id::text,\n        'lead_name', COALESCE(_lead_name, 'Job'),\n        'user_id', NEW.user_id::text,\n        'action', 'assigned'\n      )\n    )\n  );
\n  RETURN NEW;
\nEND;
\n$$;
\n\nDROP TRIGGER IF EXISTS on_job_assignment_sms ON job_assignments;
\nCREATE TRIGGER on_job_assignment_sms\n  AFTER INSERT ON job_assignments\n  FOR EACH ROW EXECUTE FUNCTION notify_sms_job_assignment();
;
