/*\n  # Fix Circular RLS Dependency in account_members\n  \n  ## Problem\n  The account_members table has RLS policies that query account_members itself,\n  creating a circular dependency. When other tables (leads, estimates, jobs) try\n  to check account membership, they hit this circular dependency and fail with\n  "policy for relation account_members" errors.\n  \n  ## Solution\n  1. Create security definer functions that bypass RLS to check membership\n  2. Remove all circular policies on account_members\n  3. Create simple, non-circular policies on account_members\n  4. All other tables will use the security definer functions\n  \n  ## Changes\n  \n  ### New Functions\n  - `is_account_member(account_id, user_id)` - Check if user is member of account\n  - `get_user_account_id(user_id)` - Get the account ID for a user\n  \n  ### Security\n  - Functions are SECURITY DEFINER and bypass RLS safely\n  - account_members policies are simplified to avoid circular dependencies\n  - Users can only view their own membership records\n  - Only account owners/admins can modify memberships\n*/\n\n-- Drop existing functions if they exist\nDROP FUNCTION IF EXISTS is_account_member(UUID, UUID);
\nDROP FUNCTION IF EXISTS get_user_account_id(UUID);
\nDROP FUNCTION IF EXISTS is_account_admin(UUID, UUID);
\n\n-- Drop existing problematic policies\nDROP POLICY IF EXISTS "Users can view their own memberships" ON public.account_members;
\nDROP POLICY IF EXISTS "Users can view members of their accounts" ON public.account_members;
\nDROP POLICY IF EXISTS "Allow insert for authenticated users" ON public.account_members;
\nDROP POLICY IF EXISTS "Account owners and admins can invite members" ON public.account_members;
\nDROP POLICY IF EXISTS "Account owners and admins can update members" ON public.account_members;
\nDROP POLICY IF EXISTS "Account owners and admins can remove members" ON public.account_members;
\n\n-- Create helper functions that bypass RLS (SECURITY DEFINER)\nCREATE OR REPLACE FUNCTION is_account_member(p_account_id UUID, p_user_id UUID)\nRETURNS BOOLEAN\nLANGUAGE plpgsql\nSECURITY DEFINER\nSET search_path = public\nAS $$\nBEGIN\n  RETURN EXISTS (\n    SELECT 1\n    FROM account_members\n    WHERE account_id = p_account_id\n      AND user_id = p_user_id\n      AND is_active = true\n  );
\nEND;
\n$$;
\n\nCREATE OR REPLACE FUNCTION get_user_account_id(p_user_id UUID)\nRETURNS UUID\nLANGUAGE plpgsql\nSECURITY DEFINER\nSET search_path = public\nAS $$\nDECLARE\n  v_account_id UUID;
\nBEGIN\n  SELECT account_id INTO v_account_id\n  FROM account_members\n  WHERE user_id = p_user_id\n    AND is_active = true\n  LIMIT 1;
\n  \n  RETURN v_account_id;
\nEND;
\n$$;
\n\nCREATE OR REPLACE FUNCTION is_account_admin(p_account_id UUID, p_user_id UUID)\nRETURNS BOOLEAN\nLANGUAGE plpgsql\nSECURITY DEFINER\nSET search_path = public\nAS $$\nBEGIN\n  RETURN EXISTS (\n    SELECT 1\n    FROM account_members\n    WHERE account_id = p_account_id\n      AND user_id = p_user_id\n      AND is_active = true\n      AND role IN ('owner', 'admin')\n  );
\nEND;
\n$$;
\n\n-- Create NEW simplified policies for account_members\n-- These DO NOT query account_members in their conditions!\n\n-- SELECT: Users can only view their own membership record\nCREATE POLICY "Users can view own membership record"\n  ON public.account_members FOR SELECT\n  TO authenticated\n  USING (user_id = auth.uid());
\n\n-- INSERT: Only allow users to create their own membership\nCREATE POLICY "System can insert memberships"\n  ON public.account_members FOR INSERT\n  TO authenticated\n  WITH CHECK (user_id = auth.uid());
\n\n-- No UPDATE or DELETE policies for regular users to avoid circular dependencies\n\n-- Grant execute permissions on helper functions\nGRANT EXECUTE ON FUNCTION is_account_member(UUID, UUID) TO authenticated;
\nGRANT EXECUTE ON FUNCTION get_user_account_id(UUID) TO authenticated;
\nGRANT EXECUTE ON FUNCTION is_account_admin(UUID, UUID) TO authenticated;
;
