/*\n  # Simplify Status to Job Lifecycle\n  \n  ## Overview\n  This migration simplifies the unified_status enum to only track the business lifecycle:\n  - new: Initial lead status\n  - contacted: Lead has been contacted\n  - qualified: Lead is qualified\n  - job: Lead has become a job (scheduled work)\n  - paid: Job has been completed and payment received\n  \n  Display status (unscheduled, scheduled, in_progress, completed) is computed from schedule data.\n  \n  ## Changes Made\n  \n  ### 1. Enum Modifications\n  - Create new simplified enum with: new, contacted, qualified, job, paid\n  - Remove: scheduled, won, invoiced, lost, on_hold, unqualified\n  \n  ### 2. Status Updates\n  - Update 'scheduled', 'won', 'invoiced' jobs to 'job'\n  - Update 'lost', 'on_hold', 'unqualified' leads to 'new'\n  \n  ### 3. Important Notes\n  - Display status is now computed from job_schedules table\n  - Status only tracks business progression, not operational state\n*/\n\n-- Step 1: Create new simplified enum\nDO $$ BEGIN\n  CREATE TYPE public.unified_status_new AS ENUM (\n    'new',\n    'contacted',\n    'qualified',\n    'job',\n    'paid'\n  );
\nEXCEPTION\n  WHEN duplicate_object THEN NULL;
\nEND $$;
\n\n-- Step 2: Drop the default on the status column\nALTER TABLE public.leads ALTER COLUMN status DROP DEFAULT;
\n\n-- Step 3: Update the leads table to use the new enum with mapping\nALTER TABLE public.leads \n  ALTER COLUMN status TYPE public.unified_status_new \n  USING CASE \n    WHEN status IN ('scheduled', 'won', 'invoiced') THEN 'job'::public.unified_status_new\n    WHEN status IN ('lost', 'on_hold', 'unqualified') THEN 'new'::public.unified_status_new\n    ELSE status::text::public.unified_status_new\n  END;
\n\n-- Step 4: Drop the old enum and rename the new one\nDROP TYPE IF EXISTS public.unified_status;
\nALTER TYPE public.unified_status_new RENAME TO unified_status;
\n\n-- Step 5: Restore the default value\nALTER TABLE public.leads \n  ALTER COLUMN status SET DEFAULT 'new'::public.unified_status;
\n;
