/*\n  # Remove Role-Based Access Control\n\n  1. Changes\n    - Drops all role-based RLS policies across all tables\n    - Replaces with simple authenticated user access\n    - All authenticated users can now access all data\n\n  2. Tables Affected (22 total)\n    - jobs, customers, profiles\n    - leads, estimates, invoices, interactions, payments\n    - material_lists, material_items\n    - supply_orders, supply_order_items\n    - estimate_line_items, invoice_line_items\n    - lead_qualifications, quick_estimates\n    - user_roles, api_keys, webhook_events\n    - stripe_connect_accounts, lead_source_connections, pricing_rules\n\n  3. Security\n    - All tables remain protected by RLS\n    - Only authenticated users can access data\n    - No more role checks or created_by restrictions\n*/\n\n-- ============================================================================\n-- DROP ALL EXISTING POLICIES\n-- ============================================================================\n\n-- User Roles Policies\nDROP POLICY IF EXISTS "Admins can view all roles" ON public.user_roles;
\nDROP POLICY IF EXISTS "Owners can manage all roles" ON public.user_roles;
\nDROP POLICY IF EXISTS "Users can view their own roles" ON public.user_roles;
\n\n-- Jobs Policies\nDROP POLICY IF EXISTS "Crew leads can update assigned jobs" ON public.jobs;
\nDROP POLICY IF EXISTS "Crew leads can view assigned jobs" ON public.jobs;
\nDROP POLICY IF EXISTS "Owners and admins have full access to jobs" ON public.jobs;
\nDROP POLICY IF EXISTS "Sales can view and manage jobs" ON public.jobs;
\nDROP POLICY IF EXISTS "Users can view and manage jobs they created" ON public.jobs;
\n\n-- Customers Policies\nDROP POLICY IF EXISTS "Crew leads can view customers for their assigned jobs" ON public.customers;
\nDROP POLICY IF EXISTS "Owners and admins have full access to customers" ON public.customers;
\nDROP POLICY IF EXISTS "Sales can view and manage customers" ON public.customers;
\nDROP POLICY IF EXISTS "Users can view and manage customers they created" ON public.customers;
\n\n-- Profiles Policies\nDROP POLICY IF EXISTS "Owners and admins can view all profiles" ON public.profiles;
\nDROP POLICY IF EXISTS "Users can insert their own profile" ON public.profiles;
\nDROP POLICY IF EXISTS "Users can update their own profile" ON public.profiles;
\nDROP POLICY IF EXISTS "Users can view their own profile" ON public.profiles;
\n\n-- Leads Policies\nDROP POLICY IF EXISTS "Crew leads can view assigned leads" ON public.leads;
\nDROP POLICY IF EXISTS "Owners and admins have full access to leads" ON public.leads;
\nDROP POLICY IF EXISTS "Sales can create leads" ON public.leads;
\nDROP POLICY IF EXISTS "Sales can update leads" ON public.leads;
\nDROP POLICY IF EXISTS "Sales can view all leads" ON public.leads;
\n\n-- Estimates Policies\nDROP POLICY IF EXISTS "Crew leads can view estimates for their jobs" ON public.estimates;
\nDROP POLICY IF EXISTS "Owners and admins have full access to estimates" ON public.estimates;
\nDROP POLICY IF EXISTS "Sales can view and manage estimates" ON public.estimates;
\n\n-- Invoices Policies\nDROP POLICY IF EXISTS "Crew leads can view invoices for their jobs" ON public.invoices;
\nDROP POLICY IF EXISTS "Owners and admins have full access to invoices" ON public.invoices;
\nDROP POLICY IF EXISTS "Sales can view and manage invoices" ON public.invoices;
\n\n-- Interactions Policies\nDROP POLICY IF EXISTS "Crew leads can view interactions for assigned leads" ON public.interactions;
\nDROP POLICY IF EXISTS "Owners and admins have full access to interactions" ON public.interactions;
\nDROP POLICY IF EXISTS "Sales can view and manage interactions" ON public.interactions;
\n\n-- Payments Policies\nDROP POLICY IF EXISTS "Crew leads can view payments for their jobs" ON public.payments;
\nDROP POLICY IF EXISTS "Owners and admins have full access to payments" ON public.payments;
\nDROP POLICY IF EXISTS "Sales can view and record payments" ON public.payments;
\n\n-- Material Lists Policies\nDROP POLICY IF EXISTS "Crew leads can view and manage material lists for their jobs" ON public.material_lists;
\nDROP POLICY IF EXISTS "Owners and admins have full access to material_lists" ON public.material_lists;
\nDROP POLICY IF EXISTS "Sales can view and manage material_lists" ON public.material_lists;
\n\n-- Material Items Policies\nDROP POLICY IF EXISTS "Items inherit material list access" ON public.material_items;
\n\n-- Supply Orders Policies\nDROP POLICY IF EXISTS "Crew leads can view and manage orders for their jobs" ON public.supply_orders;
\nDROP POLICY IF EXISTS "Owners and admins have full access to supply_orders" ON public.supply_orders;
\nDROP POLICY IF EXISTS "Sales can view and manage supply_orders" ON public.supply_orders;
\n\n-- Supply Order Items Policies\nDROP POLICY IF EXISTS "Items inherit supply order access" ON public.supply_order_items;
\n\n-- Estimate Line Items Policies\nDROP POLICY IF EXISTS "Line items inherit estimate access" ON public.estimate_line_items;
\n\n-- Invoice Line Items Policies\nDROP POLICY IF EXISTS "Line items inherit invoice access" ON public.invoice_line_items;
\n\n-- Lead Qualifications Policies\nDROP POLICY IF EXISTS "Crew leads can view lead_qualifications for assigned leads" ON public.lead_qualifications;
\nDROP POLICY IF EXISTS "Owners and admins have full access to lead_qualifications" ON public.lead_qualifications;
\nDROP POLICY IF EXISTS "Sales can view and manage lead_qualifications" ON public.lead_qualifications;
\n\n-- Quick Estimates Policies\nDROP POLICY IF EXISTS "Crew leads can view quick_estimates for assigned leads" ON public.quick_estimates;
\nDROP POLICY IF EXISTS "Owners and admins have full access to quick_estimates" ON public.quick_estimates;
\nDROP POLICY IF EXISTS "Sales can view and manage quick_estimates" ON public.quick_estimates;
\n\n-- API Keys Policies\nDROP POLICY IF EXISTS "Users can manage their own API keys" ON public.api_keys;
\n\n-- Webhook Events Policies\nDROP POLICY IF EXISTS "Owners and admins can view webhook events" ON public.webhook_events;
\n\n-- Stripe Connect Accounts Policies\nDROP POLICY IF EXISTS "Users can insert their own Stripe account" ON public.stripe_connect_accounts;
\nDROP POLICY IF EXISTS "Users can update their own Stripe account" ON public.stripe_connect_accounts;
\nDROP POLICY IF EXISTS "Users can view their own Stripe account" ON public.stripe_connect_accounts;
\n\n-- Lead Source Connections Policies\nDROP POLICY IF EXISTS "Users can create their own connections" ON public.lead_source_connections;
\nDROP POLICY IF EXISTS "Users can update their own connections" ON public.lead_source_connections;
\nDROP POLICY IF EXISTS "Users can delete their own connections" ON public.lead_source_connections;
\nDROP POLICY IF EXISTS "Users can view their own connections" ON public.lead_source_connections;
\n\n-- Pricing Rules Policies\nDROP POLICY IF EXISTS "Users can create their own pricing rules" ON public.pricing_rules;
\nDROP POLICY IF EXISTS "Users can update their own pricing rules" ON public.pricing_rules;
\nDROP POLICY IF EXISTS "Users can delete their own pricing rules" ON public.pricing_rules;
\nDROP POLICY IF EXISTS "Users can view their own pricing rules" ON public.pricing_rules;
\n\n-- ============================================================================\n-- CREATE NEW SIMPLE POLICIES - AUTHENTICATED USERS HAVE FULL ACCESS\n-- ============================================================================\n\n-- Jobs Table\nCREATE POLICY "Authenticated users have full access to jobs"\n  ON public.jobs\n  TO authenticated\n  USING (true)\n  WITH CHECK (true);
\n\n-- Customers Table\nCREATE POLICY "Authenticated users have full access to customers"\n  ON public.customers\n  TO authenticated\n  USING (true)\n  WITH CHECK (true);
\n\n-- Profiles Table\nCREATE POLICY "Authenticated users can view all profiles"\n  ON public.profiles\n  FOR SELECT\n  TO authenticated\n  USING (true);
\n\nCREATE POLICY "Authenticated users can insert their own profile"\n  ON public.profiles\n  FOR INSERT\n  TO authenticated\n  WITH CHECK (auth.uid() = user_id);
\n\nCREATE POLICY "Authenticated users can update their own profile"\n  ON public.profiles\n  FOR UPDATE\n  TO authenticated\n  USING (auth.uid() = user_id)\n  WITH CHECK (auth.uid() = user_id);
\n\n-- Leads Table\nCREATE POLICY "Authenticated users have full access to leads"\n  ON public.leads\n  TO authenticated\n  USING (true)\n  WITH CHECK (true);
\n\n-- Estimates Table\nCREATE POLICY "Authenticated users have full access to estimates"\n  ON public.estimates\n  TO authenticated\n  USING (true)\n  WITH CHECK (true);
\n\n-- Invoices Table\nCREATE POLICY "Authenticated users have full access to invoices"\n  ON public.invoices\n  TO authenticated\n  USING (true)\n  WITH CHECK (true);
\n\n-- Interactions Table\nCREATE POLICY "Authenticated users have full access to interactions"\n  ON public.interactions\n  TO authenticated\n  USING (true)\n  WITH CHECK (true);
\n\n-- Payments Table\nCREATE POLICY "Authenticated users have full access to payments"\n  ON public.payments\n  TO authenticated\n  USING (true)\n  WITH CHECK (true);
\n\n-- Material Lists Table\nCREATE POLICY "Authenticated users have full access to material_lists"\n  ON public.material_lists\n  TO authenticated\n  USING (true)\n  WITH CHECK (true);
\n\n-- Material Items Table\nCREATE POLICY "Authenticated users have full access to material_items"\n  ON public.material_items\n  TO authenticated\n  USING (true)\n  WITH CHECK (true);
\n\n-- Supply Orders Table\nCREATE POLICY "Authenticated users have full access to supply_orders"\n  ON public.supply_orders\n  TO authenticated\n  USING (true)\n  WITH CHECK (true);
\n\n-- Supply Order Items Table\nCREATE POLICY "Authenticated users have full access to supply_order_items"\n  ON public.supply_order_items\n  TO authenticated\n  USING (true)\n  WITH CHECK (true);
\n\n-- Estimate Line Items Table\nCREATE POLICY "Authenticated users have full access to estimate_line_items"\n  ON public.estimate_line_items\n  TO authenticated\n  USING (true)\n  WITH CHECK (true);
\n\n-- Invoice Line Items Table\nCREATE POLICY "Authenticated users have full access to invoice_line_items"\n  ON public.invoice_line_items\n  TO authenticated\n  USING (true)\n  WITH CHECK (true);
\n\n-- Lead Qualifications Table\nCREATE POLICY "Authenticated users have full access to lead_qualifications"\n  ON public.lead_qualifications\n  TO authenticated\n  USING (true)\n  WITH CHECK (true);
\n\n-- Quick Estimates Table\nCREATE POLICY "Authenticated users have full access to quick_estimates"\n  ON public.quick_estimates\n  TO authenticated\n  USING (true)\n  WITH CHECK (true);
\n\n-- User Roles Table\nCREATE POLICY "Authenticated users have full access to user_roles"\n  ON public.user_roles\n  TO authenticated\n  USING (true)\n  WITH CHECK (true);
\n\n-- API Keys Table\nCREATE POLICY "Authenticated users have full access to api_keys"\n  ON public.api_keys\n  TO authenticated\n  USING (true)\n  WITH CHECK (true);
\n\n-- Webhook Events Table\nCREATE POLICY "Authenticated users have full access to webhook_events"\n  ON public.webhook_events\n  TO authenticated\n  USING (true)\n  WITH CHECK (true);
\n\n-- Stripe Connect Accounts Table\nCREATE POLICY "Authenticated users have full access to stripe_connect_accounts"\n  ON public.stripe_connect_accounts\n  TO authenticated\n  USING (true)\n  WITH CHECK (true);
\n\n-- Lead Source Connections Table\nCREATE POLICY "Authenticated users have full access to lead_source_connections"\n  ON public.lead_source_connections\n  TO authenticated\n  USING (true)\n  WITH CHECK (true);
\n\n-- Pricing Rules Table\nCREATE POLICY "Authenticated users have full access to pricing_rules"\n  ON public.pricing_rules\n  TO authenticated\n  USING (true)\n  WITH CHECK (true);
\n;
