/*\n  # Fix auto create estimate function - remove paid status\n\n  1. Changes\n    - Update trigger function to only check for 'job' status (not 'paid')\n    - Remove reference to invalid 'paid' enum value\n*/\n\nCREATE OR REPLACE FUNCTION auto_create_estimate_for_job()\nRETURNS trigger\nLANGUAGE plpgsql\nSECURITY DEFINER\nSET search_path TO 'public'\nAS $$\nDECLARE\n  v_tax_rate numeric(5,4);
\n  v_profit_margin numeric;
\nBEGIN\n  IF NEW.status = 'job' AND NEW.approval_status = 'approved' THEN\n    IF NOT EXISTS (SELECT 1 FROM estimates WHERE job_id = NEW.id) THEN\n      SELECT \n        COALESCE(default_tax_rate / 100, 0),\n        COALESCE(default_profit_margin, 0)\n      INTO v_tax_rate, v_profit_margin\n      FROM accounts\n      WHERE id = NEW.account_id;
\n\n      INSERT INTO estimates (\n        customer_id,\n        job_id,\n        account_id,\n        subtotal,\n        tax_rate,\n        tax,\n        discount,\n        total,\n        profit_margin,\n        status,\n        created_by,\n        notes\n      ) VALUES (\n        NEW.customer_id,\n        NEW.id,\n        NEW.account_id,\n        0,\n        v_tax_rate,\n        0,\n        0,\n        0,\n        v_profit_margin,\n        'draft',\n        NEW.created_by,\n        'Auto-generated estimate for ' || NEW.name\n      );
\n\n      RAISE NOTICE 'Auto-created estimate for job % with tax rate % and profit margin %', NEW.id, v_tax_rate, v_profit_margin;
\n    END IF;
\n  END IF;
\n\n  RETURN NEW;
\nEND;
\n$$;
;
