/*\n  # Add Change Order Tracking to Estimate Line Items\n\n  1. Changes to `estimate_line_items` table\n    - Add `is_change_order` boolean to mark items that are change orders\n    - Add `change_order_type` enum to track type of change (added, edited, deleted)\n    - Add `original_line_item_id` to reference the original item being replaced\n    - Add `change_order_notes` for additional context about the change\n    - Add `changed_at` timestamp to track when the change occurred\n    \n  2. Security\n    - No RLS changes needed, inherits from parent table policies\n*/\n\n-- Create enum for change order types\nDO $$ BEGIN\n  CREATE TYPE change_order_type AS ENUM ('added', 'edited', 'deleted');
\nEXCEPTION\n  WHEN duplicate_object THEN NULL;
\nEND $$;
\n\n-- Add change order tracking columns to estimate_line_items\nDO $$\nBEGIN\n  IF NOT EXISTS (\n    SELECT 1 FROM information_schema.columns\n    WHERE table_name = 'estimate_line_items' AND column_name = 'is_change_order'\n  ) THEN\n    ALTER TABLE estimate_line_items ADD COLUMN is_change_order boolean DEFAULT false NOT NULL;
\n  END IF;
\n\n  IF NOT EXISTS (\n    SELECT 1 FROM information_schema.columns\n    WHERE table_name = 'estimate_line_items' AND column_name = 'change_order_type'\n  ) THEN\n    ALTER TABLE estimate_line_items ADD COLUMN change_order_type change_order_type;
\n  END IF;
\n\n  IF NOT EXISTS (\n    SELECT 1 FROM information_schema.columns\n    WHERE table_name = 'estimate_line_items' AND column_name = 'original_line_item_id'\n  ) THEN\n    ALTER TABLE estimate_line_items ADD COLUMN original_line_item_id uuid;
\n  END IF;
\n\n  IF NOT EXISTS (\n    SELECT 1 FROM information_schema.columns\n    WHERE table_name = 'estimate_line_items' AND column_name = 'change_order_notes'\n  ) THEN\n    ALTER TABLE estimate_line_items ADD COLUMN change_order_notes text;
\n  END IF;
\n\n  IF NOT EXISTS (\n    SELECT 1 FROM information_schema.columns\n    WHERE table_name = 'estimate_line_items' AND column_name = 'changed_at'\n  ) THEN\n    ALTER TABLE estimate_line_items ADD COLUMN changed_at timestamptz;
\n  END IF;
\nEND $$;
\n\n-- Add foreign key for original_line_item_id\nDO $$\nBEGIN\n  IF NOT EXISTS (\n    SELECT 1 FROM information_schema.table_constraints\n    WHERE constraint_name = 'estimate_line_items_original_line_item_id_fkey'\n  ) THEN\n    ALTER TABLE estimate_line_items\n      ADD CONSTRAINT estimate_line_items_original_line_item_id_fkey\n      FOREIGN KEY (original_line_item_id)\n      REFERENCES estimate_line_items(id)\n      ON DELETE SET NULL;
\n  END IF;
\nEND $$;
;
