/*\n  # Add Cascade Delete for Customer Relations\n\n  1. Changes\n    - Add CASCADE DELETE to foreign keys referencing customers table\n    - This ensures that when a customer is deleted, all related data is automatically removed\n\n  2. Tables Affected\n    - leads (jobs) - CASCADE DELETE on customer_id\n    - estimates - CASCADE DELETE on customer_id\n    - invoices - CASCADE DELETE on customer_id\n    - payments - CASCADE DELETE on customer_id\n\n  3. Security\n    - This maintains referential integrity and prevents orphaned records\n    - Existing RLS policies still apply\n*/\n\nDO $$ BEGIN\n  IF EXISTS (\n    SELECT 1 FROM information_schema.table_constraints\n    WHERE constraint_name = 'jobs_customer_id_fkey'\n  ) THEN\n    ALTER TABLE leads DROP CONSTRAINT jobs_customer_id_fkey;
\n    ALTER TABLE leads ADD CONSTRAINT jobs_customer_id_fkey\n      FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE CASCADE;
\n  END IF;
\nEND $$;
\n\nDO $$ BEGIN\n  IF EXISTS (\n    SELECT 1 FROM information_schema.table_constraints\n    WHERE constraint_name = 'estimates_customer_id_fkey'\n  ) THEN\n    ALTER TABLE estimates DROP CONSTRAINT estimates_customer_id_fkey;
\n    ALTER TABLE estimates ADD CONSTRAINT estimates_customer_id_fkey\n      FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE CASCADE;
\n  END IF;
\nEND $$;
\n\nDO $$ BEGIN\n  IF EXISTS (\n    SELECT 1 FROM information_schema.table_constraints\n    WHERE constraint_name = 'invoices_customer_id_fkey'\n  ) THEN\n    ALTER TABLE invoices DROP CONSTRAINT invoices_customer_id_fkey;
\n    ALTER TABLE invoices ADD CONSTRAINT invoices_customer_id_fkey\n      FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE CASCADE;
\n  END IF;
\nEND $$;
\n\nDO $$ BEGIN\n  IF EXISTS (\n    SELECT 1 FROM information_schema.table_constraints\n    WHERE constraint_name = 'payments_customer_id_fkey'\n  ) THEN\n    ALTER TABLE payments DROP CONSTRAINT payments_customer_id_fkey;
\n    ALTER TABLE payments ADD CONSTRAINT payments_customer_id_fkey\n      FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE CASCADE;
\n  END IF;
\nEND $$;
\n;
