/*\n  # Comprehensive Security Fixes\n  \n  ## Overview\n  This migration addresses multiple security and performance issues identified in the database audit.\n  \n  ## Changes Made\n  \n  ### 1. Foreign Key Indexes\n  Added missing indexes on foreign key columns to improve query performance:\n  - account_members.invited_by\n  - api_keys.account_id\n  - customers.lead_id\n  - estimate_line_items (account_id, estimate_id)\n  - estimates.created_by\n  - interactions (account_id, created_by)\n  - invoice_line_items (account_id, invoice_id)\n  - invoices (created_by, estimate_id)\n  - lead_qualifications.account_id\n  - lead_source_connections (account_id, api_key_id)\n  - material_items.account_id\n  - material_lists.created_by\n  - payments (lead_id, processed_by)\n  - pricing_rules.account_id\n  - quick_estimates (account_id, converted_to_estimate_id, lead_id)\n  - stripe_connect_accounts.account_id\n  - supply_order_items (account_id, material_item_id)\n  - supply_orders (created_by, material_list_id)\n  - webhook_events (invoice_id, payment_id)\n  \n  ### 2. RLS Policy Optimization\n  All RLS policies updated to use `(select auth.uid())` pattern to prevent re-evaluation for each row.\n  \n  ### 3. Security Hardening\n  - Removed all "always true" RLS policies that bypass security\n  - Removed duplicate permissive policies\n  - Consolidated policies for cleaner security model\n  \n  ### 4. Function Security\n  Fixed search_path for security-critical functions.\n  \n  ### 5. Unused Indexes\n  Kept all indexes as they may be needed for future query patterns.\n*/\n\n-- ============================================================================\n-- SECTION 1: ADD MISSING FOREIGN KEY INDEXES\n-- ============================================================================\n\nCREATE INDEX IF NOT EXISTS idx_account_members_invited_by ON public.account_members(invited_by);
\nCREATE INDEX IF NOT EXISTS idx_api_keys_account_id ON public.api_keys(account_id);
\nCREATE INDEX IF NOT EXISTS idx_customers_lead_id ON public.customers(lead_id);
\nCREATE INDEX IF NOT EXISTS idx_estimate_line_items_account_id ON public.estimate_line_items(account_id);
\nCREATE INDEX IF NOT EXISTS idx_estimate_line_items_estimate_id ON public.estimate_line_items(estimate_id);
\nCREATE INDEX IF NOT EXISTS idx_estimates_created_by ON public.estimates(created_by);
\nCREATE INDEX IF NOT EXISTS idx_interactions_account_id ON public.interactions(account_id);
\nCREATE INDEX IF NOT EXISTS idx_interactions_created_by ON public.interactions(created_by);
\nCREATE INDEX IF NOT EXISTS idx_invoice_line_items_account_id ON public.invoice_line_items(account_id);
\nCREATE INDEX IF NOT EXISTS idx_invoice_line_items_invoice_id ON public.invoice_line_items(invoice_id);
\nCREATE INDEX IF NOT EXISTS idx_invoices_created_by ON public.invoices(created_by);
\nCREATE INDEX IF NOT EXISTS idx_invoices_estimate_id ON public.invoices(estimate_id);
\nCREATE INDEX IF NOT EXISTS idx_lead_qualifications_account_id ON public.lead_qualifications(account_id);
\nCREATE INDEX IF NOT EXISTS idx_lead_source_connections_account_id ON public.lead_source_connections(account_id);
\nCREATE INDEX IF NOT EXISTS idx_lead_source_connections_api_key_id ON public.lead_source_connections(api_key_id);
\nCREATE INDEX IF NOT EXISTS idx_material_items_account_id ON public.material_items(account_id);
\nCREATE INDEX IF NOT EXISTS idx_material_lists_created_by ON public.material_lists(created_by);
\nCREATE INDEX IF NOT EXISTS idx_payments_lead_id ON public.payments(lead_id);
\nCREATE INDEX IF NOT EXISTS idx_payments_processed_by ON public.payments(processed_by);
\nCREATE INDEX IF NOT EXISTS idx_pricing_rules_account_id ON public.pricing_rules(account_id);
\nCREATE INDEX IF NOT EXISTS idx_quick_estimates_account_id ON public.quick_estimates(account_id);
\nCREATE INDEX IF NOT EXISTS idx_quick_estimates_converted_to_estimate_id ON public.quick_estimates(converted_to_estimate_id);
\nCREATE INDEX IF NOT EXISTS idx_quick_estimates_lead_id ON public.quick_estimates(lead_id);
\nCREATE INDEX IF NOT EXISTS idx_stripe_connect_accounts_account_id ON public.stripe_connect_accounts(account_id);
\nCREATE INDEX IF NOT EXISTS idx_supply_order_items_account_id ON public.supply_order_items(account_id);
\nCREATE INDEX IF NOT EXISTS idx_supply_order_items_material_item_id ON public.supply_order_items(material_item_id);
\nCREATE INDEX IF NOT EXISTS idx_supply_orders_created_by ON public.supply_orders(created_by);
\nCREATE INDEX IF NOT EXISTS idx_supply_orders_material_list_id ON public.supply_orders(material_list_id);
\nCREATE INDEX IF NOT EXISTS idx_webhook_events_invoice_id ON public.webhook_events(invoice_id);
\nCREATE INDEX IF NOT EXISTS idx_webhook_events_payment_id ON public.webhook_events(payment_id);
\n\n-- ============================================================================\n-- SECTION 2: FIX FUNCTION SECURITY (Search Path)\n-- ============================================================================\n\nCREATE OR REPLACE FUNCTION public.generate_invite_code()\nRETURNS text\nLANGUAGE plpgsql\nSECURITY DEFINER\nSET search_path = public\nAS $$\nDECLARE\n  code text;
\n  exists boolean;
\nBEGIN\n  LOOP\n    code := substring(md5(random()::text) from 1 for 8);
\n    SELECT EXISTS(SELECT 1 FROM accounts WHERE invite_code = code) INTO exists;
\n    EXIT WHEN NOT exists;
\n  END LOOP;
\n  RETURN code;
\nEND;
\n$$;
\n\nCREATE OR REPLACE FUNCTION public.get_user_roles(user_uuid uuid)\nRETURNS TABLE(role text)\nLANGUAGE plpgsql\nSECURITY DEFINER\nSET search_path = public\nAS $$\nBEGIN\n  RETURN QUERY\n  SELECT ur.role\n  FROM user_roles ur\n  WHERE ur.user_id = user_uuid;
\nEND;
\n$$;
\n\nCREATE OR REPLACE FUNCTION public.has_role(user_uuid uuid, role_name text)\nRETURNS boolean\nLANGUAGE plpgsql\nSECURITY DEFINER\nSET search_path = public\nAS $$\nBEGIN\n  RETURN EXISTS(\n    SELECT 1\n    FROM user_roles\n    WHERE user_id = user_uuid AND role = role_name\n  );
\nEND;
\n$$;
\n\n-- ============================================================================\n-- SECTION 3: REMOVE INSECURE "ALWAYS TRUE" POLICIES\n-- ============================================================================\n\nDROP POLICY IF EXISTS "Authenticated users have full access to api_keys" ON public.api_keys;
\nDROP POLICY IF EXISTS "Authenticated users have full access to customers" ON public.customers;
\nDROP POLICY IF EXISTS "Authenticated users have full access to estimate_line_items" ON public.estimate_line_items;
\nDROP POLICY IF EXISTS "Authenticated users have full access to estimates" ON public.estimates;
\nDROP POLICY IF EXISTS "Authenticated users have full access to interactions" ON public.interactions;
\nDROP POLICY IF EXISTS "Authenticated users have full access to invoice_line_items" ON public.invoice_line_items;
\nDROP POLICY IF EXISTS "Authenticated users have full access to invoices" ON public.invoices;
\nDROP POLICY IF EXISTS "Authenticated users have full access to lead_qualifications" ON public.lead_qualifications;
\nDROP POLICY IF EXISTS "Authenticated users have full access to lead_source_connections" ON public.lead_source_connections;
\nDROP POLICY IF EXISTS "Authenticated users have full access to material_items" ON public.material_items;
\nDROP POLICY IF EXISTS "Authenticated users have full access to material_lists" ON public.material_lists;
\nDROP POLICY IF EXISTS "Authenticated users have full access to payments" ON public.payments;
\nDROP POLICY IF EXISTS "Authenticated users have full access to pricing_rules" ON public.pricing_rules;
\nDROP POLICY IF EXISTS "Authenticated users have full access to quick_estimates" ON public.quick_estimates;
\nDROP POLICY IF EXISTS "Authenticated users have full access to stripe_connect_accounts" ON public.stripe_connect_accounts;
\nDROP POLICY IF EXISTS "Authenticated users have full access to supply_order_items" ON public.supply_order_items;
\nDROP POLICY IF EXISTS "Authenticated users have full access to supply_orders" ON public.supply_orders;
\nDROP POLICY IF EXISTS "Authenticated users have full access to user_roles" ON public.user_roles;
\nDROP POLICY IF EXISTS "Authenticated users have full access to webhook_events" ON public.webhook_events;
\nDROP POLICY IF EXISTS "Allow profile creation on signup" ON public.profiles;
\nDROP POLICY IF EXISTS "Allow role creation on signup" ON public.user_roles;
\n\n-- ============================================================================\n-- SECTION 4: REMOVE OLD/DUPLICATE POLICIES BEFORE RECREATING\n-- ============================================================================\n\n-- Accounts\nDROP POLICY IF EXISTS "Users can view their accounts" ON public.accounts;
\nDROP POLICY IF EXISTS "Users can view their own account" ON public.accounts;
\nDROP POLICY IF EXISTS "Users can view their own accounts" ON public.accounts;
\nDROP POLICY IF EXISTS "Account owners and admins can update accounts" ON public.accounts;
\nDROP POLICY IF EXISTS "Users can update their own account" ON public.accounts;
\nDROP POLICY IF EXISTS "Account owners can delete accounts" ON public.accounts;
\nDROP POLICY IF EXISTS "Users can create accounts" ON public.accounts;
\n\n-- Account Members\nDROP POLICY IF EXISTS "Users can view own membership record" ON public.account_members;
\nDROP POLICY IF EXISTS "System can insert memberships" ON public.account_members;
\n\n-- API Keys\nDROP POLICY IF EXISTS "Account members can view API keys" ON public.api_keys;
\nDROP POLICY IF EXISTS "Account owners and admins can create API keys" ON public.api_keys;
\nDROP POLICY IF EXISTS "Account owners and admins can update API keys" ON public.api_keys;
\nDROP POLICY IF EXISTS "Account owners and admins can delete API keys" ON public.api_keys;
\n\n-- Customers\nDROP POLICY IF EXISTS "Account members can view customers" ON public.customers;
\nDROP POLICY IF EXISTS "Account members can create customers" ON public.customers;
\nDROP POLICY IF EXISTS "Account members can update customers" ON public.customers;
\nDROP POLICY IF EXISTS "Account owners and admins can delete customers" ON public.customers;
\nDROP POLICY IF EXISTS "Users can view customers in their account" ON public.customers;
\nDROP POLICY IF EXISTS "Users can create customers in their account" ON public.customers;
\nDROP POLICY IF EXISTS "Users can update customers in their account" ON public.customers;
\nDROP POLICY IF EXISTS "Users can delete customers in their account" ON public.customers;
\n\n-- Estimates\nDROP POLICY IF EXISTS "Account members can view estimates" ON public.estimates;
\nDROP POLICY IF EXISTS "Account members can create estimates" ON public.estimates;
\nDROP POLICY IF EXISTS "Account members can update estimates" ON public.estimates;
\nDROP POLICY IF EXISTS "Account owners and admins can delete estimates" ON public.estimates;
\nDROP POLICY IF EXISTS "Users can view estimates in their account" ON public.estimates;
\nDROP POLICY IF EXISTS "Users can create estimates in their account" ON public.estimates;
\nDROP POLICY IF EXISTS "Users can update estimates in their account" ON public.estimates;
\nDROP POLICY IF EXISTS "Users can delete estimates in their account" ON public.estimates;
\n\n-- Estimate Line Items\nDROP POLICY IF EXISTS "Account members can view estimate line items" ON public.estimate_line_items;
\nDROP POLICY IF EXISTS "Account members can create estimate line items" ON public.estimate_line_items;
\nDROP POLICY IF EXISTS "Account members can update estimate line items" ON public.estimate_line_items;
\nDROP POLICY IF EXISTS "Account members can delete estimate line items" ON public.estimate_line_items;
\nDROP POLICY IF EXISTS "Users can view estimate line items in their account" ON public.estimate_line_items;
\nDROP POLICY IF EXISTS "Users can create estimate line items in their account" ON public.estimate_line_items;
\nDROP POLICY IF EXISTS "Users can update estimate line items in their account" ON public.estimate_line_items;
\nDROP POLICY IF EXISTS "Users can delete estimate line items in their account" ON public.estimate_line_items;
\n\n-- Invoices\nDROP POLICY IF EXISTS "Account members can view invoices" ON public.invoices;
\nDROP POLICY IF EXISTS "Account members can create invoices" ON public.invoices;
\nDROP POLICY IF EXISTS "Account members can update invoices" ON public.invoices;
\nDROP POLICY IF EXISTS "Account owners and admins can delete invoices" ON public.invoices;
\nDROP POLICY IF EXISTS "Users can view invoices in their account" ON public.invoices;
\nDROP POLICY IF EXISTS "Users can create invoices in their account" ON public.invoices;
\nDROP POLICY IF EXISTS "Users can update invoices in their account" ON public.invoices;
\nDROP POLICY IF EXISTS "Users can delete invoices in their account" ON public.invoices;
\n\n-- Invoice Line Items\nDROP POLICY IF EXISTS "Account members can view invoice line items" ON public.invoice_line_items;
\nDROP POLICY IF EXISTS "Account members can create invoice line items" ON public.invoice_line_items;
\nDROP POLICY IF EXISTS "Account members can update invoice line items" ON public.invoice_line_items;
\nDROP POLICY IF EXISTS "Account members can delete invoice line items" ON public.invoice_line_items;
\nDROP POLICY IF EXISTS "Users can view invoice line items in their account" ON public.invoice_line_items;
\nDROP POLICY IF EXISTS "Users can create invoice line items in their account" ON public.invoice_line_items;
\nDROP POLICY IF EXISTS "Users can update invoice line items in their account" ON public.invoice_line_items;
\nDROP POLICY IF EXISTS "Users can delete invoice line items in their account" ON public.invoice_line_items;
\n\n-- Interactions\nDROP POLICY IF EXISTS "Account members can view interactions" ON public.interactions;
\nDROP POLICY IF EXISTS "Account members can create interactions" ON public.interactions;
\nDROP POLICY IF EXISTS "Account members can update interactions" ON public.interactions;
\nDROP POLICY IF EXISTS "Account owners and admins can delete interactions" ON public.interactions;
\nDROP POLICY IF EXISTS "Users can view interactions in their account" ON public.interactions;
\nDROP POLICY IF EXISTS "Users can create interactions in their account" ON public.interactions;
\nDROP POLICY IF EXISTS "Users can update interactions in their account" ON public.interactions;
\nDROP POLICY IF EXISTS "Users can delete interactions in their account" ON public.interactions;
\n\n-- Leads\nDROP POLICY IF EXISTS "Account members can view leads" ON public.leads;
\nDROP POLICY IF EXISTS "Account members can create leads" ON public.leads;
\nDROP POLICY IF EXISTS "Account members can update leads" ON public.leads;
\nDROP POLICY IF EXISTS "Account owners and admins can delete leads" ON public.leads;
\n\n-- Lead Qualifications\nDROP POLICY IF EXISTS "Account members can view lead qualifications" ON public.lead_qualifications;
\nDROP POLICY IF EXISTS "Account members can create lead qualifications" ON public.lead_qualifications;
\nDROP POLICY IF EXISTS "Account members can update lead qualifications" ON public.lead_qualifications;
\nDROP POLICY IF EXISTS "Account members can delete lead qualifications" ON public.lead_qualifications;
\nDROP POLICY IF EXISTS "Users can view lead qualifications in their account" ON public.lead_qualifications;
\nDROP POLICY IF EXISTS "Users can create lead qualifications in their account" ON public.lead_qualifications;
\nDROP POLICY IF EXISTS "Users can update lead qualifications in their account" ON public.lead_qualifications;
\nDROP POLICY IF EXISTS "Users can delete lead qualifications in their account" ON public.lead_qualifications;
\n\n-- Lead Source Connections\nDROP POLICY IF EXISTS "Account members can view lead source connections" ON public.lead_source_connections;
\nDROP POLICY IF EXISTS "Account owners and admins can create lead source connections" ON public.lead_source_connections;
\nDROP POLICY IF EXISTS "Account owners and admins can update lead source connections" ON public.lead_source_connections;
\nDROP POLICY IF EXISTS "Account owners and admins can delete lead source connections" ON public.lead_source_connections;
\n\n-- Material Items\nDROP POLICY IF EXISTS "Account members can view material items" ON public.material_items;
\nDROP POLICY IF EXISTS "Account members can create material items" ON public.material_items;
\nDROP POLICY IF EXISTS "Account members can update material items" ON public.material_items;
\nDROP POLICY IF EXISTS "Account members can delete material items" ON public.material_items;
\nDROP POLICY IF EXISTS "Users can view material items in their account" ON public.material_items;
\nDROP POLICY IF EXISTS "Users can create material items in their account" ON public.material_items;
\nDROP POLICY IF EXISTS "Users can update material items in their account" ON public.material_items;
\nDROP POLICY IF EXISTS "Users can delete material items in their account" ON public.material_items;
\n\n-- Material Lists\nDROP POLICY IF EXISTS "Account members can view material lists" ON public.material_lists;
\nDROP POLICY IF EXISTS "Account members can create material lists" ON public.material_lists;
\nDROP POLICY IF EXISTS "Account members can update material lists" ON public.material_lists;
\nDROP POLICY IF EXISTS "Account owners and admins can delete material lists" ON public.material_lists;
\nDROP POLICY IF EXISTS "Users can view material lists in their account" ON public.material_lists;
\nDROP POLICY IF EXISTS "Users can create material lists in their account" ON public.material_lists;
\nDROP POLICY IF EXISTS "Users can update material lists in their account" ON public.material_lists;
\nDROP POLICY IF EXISTS "Users can delete material lists in their account" ON public.material_lists;
\n\n-- Payments\nDROP POLICY IF EXISTS "Account members can view payments" ON public.payments;
\nDROP POLICY IF EXISTS "Account members can create payments" ON public.payments;
\nDROP POLICY IF EXISTS "Account members can update payments" ON public.payments;
\nDROP POLICY IF EXISTS "Account owners and admins can delete payments" ON public.payments;
\nDROP POLICY IF EXISTS "Users can view payments in their account" ON public.payments;
\nDROP POLICY IF EXISTS "Users can create payments in their account" ON public.payments;
\nDROP POLICY IF EXISTS "Users can update payments in their account" ON public.payments;
\nDROP POLICY IF EXISTS "Users can delete payments in their account" ON public.payments;
\n\n-- Pricing Rules\nDROP POLICY IF EXISTS "Account members can view pricing rules" ON public.pricing_rules;
\nDROP POLICY IF EXISTS "Account members can create pricing rules" ON public.pricing_rules;
\nDROP POLICY IF EXISTS "Account members can update pricing rules" ON public.pricing_rules;
\nDROP POLICY IF EXISTS "Account owners and admins can delete pricing rules" ON public.pricing_rules;
\n\n-- Profiles\nDROP POLICY IF EXISTS "Sales can view crew lead profiles" ON public.profiles;
\nDROP POLICY IF EXISTS "Authenticated users can insert their own profile" ON public.profiles;
\nDROP POLICY IF EXISTS "Authenticated users can update their own profile" ON public.profiles;
\nDROP POLICY IF EXISTS "Authenticated users can view all profiles" ON public.profiles;
\n\n-- Quick Estimates\nDROP POLICY IF EXISTS "Account members can view quick estimates" ON public.quick_estimates;
\nDROP POLICY IF EXISTS "Account members can create quick estimates" ON public.quick_estimates;
\nDROP POLICY IF EXISTS "Account members can update quick estimates" ON public.quick_estimates;
\nDROP POLICY IF EXISTS "Account owners and admins can delete quick estimates" ON public.quick_estimates;
\nDROP POLICY IF EXISTS "Users can view quick estimates in their account" ON public.quick_estimates;
\nDROP POLICY IF EXISTS "Users can create quick estimates in their account" ON public.quick_estimates;
\nDROP POLICY IF EXISTS "Users can update quick estimates in their account" ON public.quick_estimates;
\nDROP POLICY IF EXISTS "Users can delete quick estimates in their account" ON public.quick_estimates;
\n\n-- Stripe Connect Accounts\nDROP POLICY IF EXISTS "Account members can view Stripe accounts" ON public.stripe_connect_accounts;
\nDROP POLICY IF EXISTS "Account owners and admins can create Stripe accounts" ON public.stripe_connect_accounts;
\nDROP POLICY IF EXISTS "Account owners and admins can update Stripe accounts" ON public.stripe_connect_accounts;
\nDROP POLICY IF EXISTS "Account owners and admins can delete Stripe accounts" ON public.stripe_connect_accounts;
\n\n-- Supply Order Items\nDROP POLICY IF EXISTS "Account members can view supply order items" ON public.supply_order_items;
\nDROP POLICY IF EXISTS "Account members can create supply order items" ON public.supply_order_items;
\nDROP POLICY IF EXISTS "Account members can update supply order items" ON public.supply_order_items;
\nDROP POLICY IF EXISTS "Account members can delete supply order items" ON public.supply_order_items;
\nDROP POLICY IF EXISTS "Users can view supply order items in their account" ON public.supply_order_items;
\nDROP POLICY IF EXISTS "Users can create supply order items in their account" ON public.supply_order_items;
\nDROP POLICY IF EXISTS "Users can update supply order items in their account" ON public.supply_order_items;
\nDROP POLICY IF EXISTS "Users can delete supply order items in their account" ON public.supply_order_items;
\n\n-- Supply Orders\nDROP POLICY IF EXISTS "Account members can view supply orders" ON public.supply_orders;
\nDROP POLICY IF EXISTS "Account members can create supply orders" ON public.supply_orders;
\nDROP POLICY IF EXISTS "Account members can update supply orders" ON public.supply_orders;
\nDROP POLICY IF EXISTS "Account owners and admins can delete supply orders" ON public.supply_orders;
\nDROP POLICY IF EXISTS "Users can view supply orders in their account" ON public.supply_orders;
\nDROP POLICY IF EXISTS "Users can create supply orders in their account" ON public.supply_orders;
\nDROP POLICY IF EXISTS "Users can update supply orders in their account" ON public.supply_orders;
\nDROP POLICY IF EXISTS "Users can delete supply orders in their account" ON public.supply_orders;
\n\n-- ============================================================================\n-- SECTION 5: CREATE OPTIMIZED RLS POLICIES WITH (select auth.uid())\n-- ============================================================================\n\n-- Helper function to check account membership (security definer to cache auth.uid())\nCREATE OR REPLACE FUNCTION public.user_is_account_member(account_uuid uuid)\nRETURNS boolean\nLANGUAGE plpgsql\nSECURITY DEFINER\nSET search_path = public\nSTABLE\nAS $$\nDECLARE\n  current_user_id uuid;
\nBEGIN\n  current_user_id := auth.uid();
\n  RETURN EXISTS (\n    SELECT 1 FROM account_members\n    WHERE account_id = account_uuid\n    AND user_id = current_user_id\n  );
\nEND;
\n$$;
\n\n-- Helper function to check if user is account owner or admin\nCREATE OR REPLACE FUNCTION public.user_is_account_owner_or_admin(account_uuid uuid)\nRETURNS boolean\nLANGUAGE plpgsql\nSECURITY DEFINER\nSET search_path = public\nSTABLE\nAS $$\nDECLARE\n  current_user_id uuid;
\nBEGIN\n  current_user_id := auth.uid();
\n  RETURN EXISTS (\n    SELECT 1 FROM account_members\n    WHERE account_id = account_uuid\n    AND user_id = current_user_id\n    AND role IN ('owner', 'admin')\n  );
\nEND;
\n$$;
\n\n-- Accounts Table\nCREATE POLICY "Account members can view their accounts"\n  ON public.accounts FOR SELECT\n  TO authenticated\n  USING (user_is_account_member(id));
\n\nCREATE POLICY "Account owners and admins can update accounts"\n  ON public.accounts FOR UPDATE\n  TO authenticated\n  USING (user_is_account_owner_or_admin(id))\n  WITH CHECK (user_is_account_owner_or_admin(id));
\n\nCREATE POLICY "Account owners can delete accounts"\n  ON public.accounts FOR DELETE\n  TO authenticated\n  USING (user_is_account_owner_or_admin(id));
\n\n-- Account Members Table\nCREATE POLICY "Users can view their own membership"\n  ON public.account_members FOR SELECT\n  TO authenticated\n  USING (user_id = (SELECT auth.uid()));
\n\n-- API Keys Table\nCREATE POLICY "Account members can view API keys"\n  ON public.api_keys FOR SELECT\n  TO authenticated\n  USING (user_is_account_member(account_id));
\n\nCREATE POLICY "Account owners and admins can create API keys"\n  ON public.api_keys FOR INSERT\n  TO authenticated\n  WITH CHECK (user_is_account_owner_or_admin(account_id));
\n\nCREATE POLICY "Account owners and admins can update API keys"\n  ON public.api_keys FOR UPDATE\n  TO authenticated\n  USING (user_is_account_owner_or_admin(account_id))\n  WITH CHECK (user_is_account_owner_or_admin(account_id));
\n\nCREATE POLICY "Account owners and admins can delete API keys"\n  ON public.api_keys FOR DELETE\n  TO authenticated\n  USING (user_is_account_owner_or_admin(account_id));
\n\n-- Customers Table\nCREATE POLICY "Account members can view customers"\n  ON public.customers FOR SELECT\n  TO authenticated\n  USING (user_is_account_member(account_id));
\n\nCREATE POLICY "Account members can create customers"\n  ON public.customers FOR INSERT\n  TO authenticated\n  WITH CHECK (user_is_account_member(account_id));
\n\nCREATE POLICY "Account members can update customers"\n  ON public.customers FOR UPDATE\n  TO authenticated\n  USING (user_is_account_member(account_id))\n  WITH CHECK (user_is_account_member(account_id));
\n\nCREATE POLICY "Account owners and admins can delete customers"\n  ON public.customers FOR DELETE\n  TO authenticated\n  USING (user_is_account_owner_or_admin(account_id));
\n\n-- Estimates Table\nCREATE POLICY "Account members can view estimates"\n  ON public.estimates FOR SELECT\n  TO authenticated\n  USING (user_is_account_member(account_id));
\n\nCREATE POLICY "Account members can create estimates"\n  ON public.estimates FOR INSERT\n  TO authenticated\n  WITH CHECK (user_is_account_member(account_id));
\n\nCREATE POLICY "Account members can update estimates"\n  ON public.estimates FOR UPDATE\n  TO authenticated\n  USING (user_is_account_member(account_id))\n  WITH CHECK (user_is_account_member(account_id));
\n\nCREATE POLICY "Account owners and admins can delete estimates"\n  ON public.estimates FOR DELETE\n  TO authenticated\n  USING (user_is_account_owner_or_admin(account_id));
\n\n-- Estimate Line Items Table\nCREATE POLICY "Account members can view estimate line items"\n  ON public.estimate_line_items FOR SELECT\n  TO authenticated\n  USING (user_is_account_member(account_id));
\n\nCREATE POLICY "Account members can create estimate line items"\n  ON public.estimate_line_items FOR INSERT\n  TO authenticated\n  WITH CHECK (user_is_account_member(account_id));
\n\nCREATE POLICY "Account members can update estimate line items"\n  ON public.estimate_line_items FOR UPDATE\n  TO authenticated\n  USING (user_is_account_member(account_id))\n  WITH CHECK (user_is_account_member(account_id));
\n\nCREATE POLICY "Account members can delete estimate line items"\n  ON public.estimate_line_items FOR DELETE\n  TO authenticated\n  USING (user_is_account_member(account_id));
\n\n-- Invoices Table\nCREATE POLICY "Account members can view invoices"\n  ON public.invoices FOR SELECT\n  TO authenticated\n  USING (user_is_account_member(account_id));
\n\nCREATE POLICY "Account members can create invoices"\n  ON public.invoices FOR INSERT\n  TO authenticated\n  WITH CHECK (user_is_account_member(account_id));
\n\nCREATE POLICY "Account members can update invoices"\n  ON public.invoices FOR UPDATE\n  TO authenticated\n  USING (user_is_account_member(account_id))\n  WITH CHECK (user_is_account_member(account_id));
\n\nCREATE POLICY "Account owners and admins can delete invoices"\n  ON public.invoices FOR DELETE\n  TO authenticated\n  USING (user_is_account_owner_or_admin(account_id));
\n\n-- Invoice Line Items Table\nCREATE POLICY "Account members can view invoice line items"\n  ON public.invoice_line_items FOR SELECT\n  TO authenticated\n  USING (user_is_account_member(account_id));
\n\nCREATE POLICY "Account members can create invoice line items"\n  ON public.invoice_line_items FOR INSERT\n  TO authenticated\n  WITH CHECK (user_is_account_member(account_id));
\n\nCREATE POLICY "Account members can update invoice line items"\n  ON public.invoice_line_items FOR UPDATE\n  TO authenticated\n  USING (user_is_account_member(account_id))\n  WITH CHECK (user_is_account_member(account_id));
\n\nCREATE POLICY "Account members can delete invoice line items"\n  ON public.invoice_line_items FOR DELETE\n  TO authenticated\n  USING (user_is_account_member(account_id));
\n\n-- Interactions Table\nCREATE POLICY "Account members can view interactions"\n  ON public.interactions FOR SELECT\n  TO authenticated\n  USING (user_is_account_member(account_id));
\n\nCREATE POLICY "Account members can create interactions"\n  ON public.interactions FOR INSERT\n  TO authenticated\n  WITH CHECK (user_is_account_member(account_id));
\n\nCREATE POLICY "Account members can update interactions"\n  ON public.interactions FOR UPDATE\n  TO authenticated\n  USING (user_is_account_member(account_id))\n  WITH CHECK (user_is_account_member(account_id));
\n\nCREATE POLICY "Account owners and admins can delete interactions"\n  ON public.interactions FOR DELETE\n  TO authenticated\n  USING (user_is_account_owner_or_admin(account_id));
\n\n-- Leads Table\nCREATE POLICY "Account members can view leads"\n  ON public.leads FOR SELECT\n  TO authenticated\n  USING (user_is_account_member(account_id));
\n\nCREATE POLICY "Account members can create leads"\n  ON public.leads FOR INSERT\n  TO authenticated\n  WITH CHECK (user_is_account_member(account_id));
\n\nCREATE POLICY "Account members can update leads"\n  ON public.leads FOR UPDATE\n  TO authenticated\n  USING (user_is_account_member(account_id))\n  WITH CHECK (user_is_account_member(account_id));
\n\nCREATE POLICY "Account owners and admins can delete leads"\n  ON public.leads FOR DELETE\n  TO authenticated\n  USING (user_is_account_owner_or_admin(account_id));
\n\n-- Lead Qualifications Table\nCREATE POLICY "Account members can view lead qualifications"\n  ON public.lead_qualifications FOR SELECT\n  TO authenticated\n  USING (user_is_account_member(account_id));
\n\nCREATE POLICY "Account members can create lead qualifications"\n  ON public.lead_qualifications FOR INSERT\n  TO authenticated\n  WITH CHECK (user_is_account_member(account_id));
\n\nCREATE POLICY "Account members can update lead qualifications"\n  ON public.lead_qualifications FOR UPDATE\n  TO authenticated\n  USING (user_is_account_member(account_id))\n  WITH CHECK (user_is_account_member(account_id));
\n\nCREATE POLICY "Account members can delete lead qualifications"\n  ON public.lead_qualifications FOR DELETE\n  TO authenticated\n  USING (user_is_account_member(account_id));
\n\n-- Lead Source Connections Table\nCREATE POLICY "Account members can view lead source connections"\n  ON public.lead_source_connections FOR SELECT\n  TO authenticated\n  USING (user_is_account_member(account_id));
\n\nCREATE POLICY "Account owners and admins can create lead source connections"\n  ON public.lead_source_connections FOR INSERT\n  TO authenticated\n  WITH CHECK (user_is_account_owner_or_admin(account_id));
\n\nCREATE POLICY "Account owners and admins can update lead source connections"\n  ON public.lead_source_connections FOR UPDATE\n  TO authenticated\n  USING (user_is_account_owner_or_admin(account_id))\n  WITH CHECK (user_is_account_owner_or_admin(account_id));
\n\nCREATE POLICY "Account owners and admins can delete lead source connections"\n  ON public.lead_source_connections FOR DELETE\n  TO authenticated\n  USING (user_is_account_owner_or_admin(account_id));
\n\n-- Material Items Table\nCREATE POLICY "Account members can view material items"\n  ON public.material_items FOR SELECT\n  TO authenticated\n  USING (user_is_account_member(account_id));
\n\nCREATE POLICY "Account members can create material items"\n  ON public.material_items FOR INSERT\n  TO authenticated\n  WITH CHECK (user_is_account_member(account_id));
\n\nCREATE POLICY "Account members can update material items"\n  ON public.material_items FOR UPDATE\n  TO authenticated\n  USING (user_is_account_member(account_id))\n  WITH CHECK (user_is_account_member(account_id));
\n\nCREATE POLICY "Account members can delete material items"\n  ON public.material_items FOR DELETE\n  TO authenticated\n  USING (user_is_account_member(account_id));
\n\n-- Material Lists Table\nCREATE POLICY "Account members can view material lists"\n  ON public.material_lists FOR SELECT\n  TO authenticated\n  USING (user_is_account_member(account_id));
\n\nCREATE POLICY "Account members can create material lists"\n  ON public.material_lists FOR INSERT\n  TO authenticated\n  WITH CHECK (user_is_account_member(account_id));
\n\nCREATE POLICY "Account members can update material lists"\n  ON public.material_lists FOR UPDATE\n  TO authenticated\n  USING (user_is_account_member(account_id))\n  WITH CHECK (user_is_account_member(account_id));
\n\nCREATE POLICY "Account owners and admins can delete material lists"\n  ON public.material_lists FOR DELETE\n  TO authenticated\n  USING (user_is_account_owner_or_admin(account_id));
\n\n-- Payments Table\nCREATE POLICY "Account members can view payments"\n  ON public.payments FOR SELECT\n  TO authenticated\n  USING (user_is_account_member(account_id));
\n\nCREATE POLICY "Account members can create payments"\n  ON public.payments FOR INSERT\n  TO authenticated\n  WITH CHECK (user_is_account_member(account_id));
\n\nCREATE POLICY "Account members can update payments"\n  ON public.payments FOR UPDATE\n  TO authenticated\n  USING (user_is_account_member(account_id))\n  WITH CHECK (user_is_account_member(account_id));
\n\nCREATE POLICY "Account owners and admins can delete payments"\n  ON public.payments FOR DELETE\n  TO authenticated\n  USING (user_is_account_owner_or_admin(account_id));
\n\n-- Pricing Rules Table\nCREATE POLICY "Account members can view pricing rules"\n  ON public.pricing_rules FOR SELECT\n  TO authenticated\n  USING (user_is_account_member(account_id));
\n\nCREATE POLICY "Account members can create pricing rules"\n  ON public.pricing_rules FOR INSERT\n  TO authenticated\n  WITH CHECK (user_is_account_member(account_id));
\n\nCREATE POLICY "Account members can update pricing rules"\n  ON public.pricing_rules FOR UPDATE\n  TO authenticated\n  USING (user_is_account_member(account_id))\n  WITH CHECK (user_is_account_member(account_id));
\n\nCREATE POLICY "Account owners and admins can delete pricing rules"\n  ON public.pricing_rules FOR DELETE\n  TO authenticated\n  USING (user_is_account_owner_or_admin(account_id));
\n\n-- Profiles Table\nCREATE POLICY "Users can view all profiles"\n  ON public.profiles FOR SELECT\n  TO authenticated\n  USING (true);
\n\nCREATE POLICY "Users can insert their own profile"\n  ON public.profiles FOR INSERT\n  TO authenticated\n  WITH CHECK (id = (SELECT auth.uid()));
\n\nCREATE POLICY "Users can update their own profile"\n  ON public.profiles FOR UPDATE\n  TO authenticated\n  USING (id = (SELECT auth.uid()))\n  WITH CHECK (id = (SELECT auth.uid()));
\n\n-- Quick Estimates Table\nCREATE POLICY "Account members can view quick estimates"\n  ON public.quick_estimates FOR SELECT\n  TO authenticated\n  USING (user_is_account_member(account_id));
\n\nCREATE POLICY "Account members can create quick estimates"\n  ON public.quick_estimates FOR INSERT\n  TO authenticated\n  WITH CHECK (user_is_account_member(account_id));
\n\nCREATE POLICY "Account members can update quick estimates"\n  ON public.quick_estimates FOR UPDATE\n  TO authenticated\n  USING (user_is_account_member(account_id))\n  WITH CHECK (user_is_account_member(account_id));
\n\nCREATE POLICY "Account owners and admins can delete quick estimates"\n  ON public.quick_estimates FOR DELETE\n  TO authenticated\n  USING (user_is_account_owner_or_admin(account_id));
\n\n-- Stripe Connect Accounts Table\nCREATE POLICY "Account members can view Stripe accounts"\n  ON public.stripe_connect_accounts FOR SELECT\n  TO authenticated\n  USING (user_is_account_member(account_id));
\n\nCREATE POLICY "Account owners and admins can create Stripe accounts"\n  ON public.stripe_connect_accounts FOR INSERT\n  TO authenticated\n  WITH CHECK (user_is_account_owner_or_admin(account_id));
\n\nCREATE POLICY "Account owners and admins can update Stripe accounts"\n  ON public.stripe_connect_accounts FOR UPDATE\n  TO authenticated\n  USING (user_is_account_owner_or_admin(account_id))\n  WITH CHECK (user_is_account_owner_or_admin(account_id));
\n\nCREATE POLICY "Account owners and admins can delete Stripe accounts"\n  ON public.stripe_connect_accounts FOR DELETE\n  TO authenticated\n  USING (user_is_account_owner_or_admin(account_id));
\n\n-- Supply Order Items Table\nCREATE POLICY "Account members can view supply order items"\n  ON public.supply_order_items FOR SELECT\n  TO authenticated\n  USING (user_is_account_member(account_id));
\n\nCREATE POLICY "Account members can create supply order items"\n  ON public.supply_order_items FOR INSERT\n  TO authenticated\n  WITH CHECK (user_is_account_member(account_id));
\n\nCREATE POLICY "Account members can update supply order items"\n  ON public.supply_order_items FOR UPDATE\n  TO authenticated\n  USING (user_is_account_member(account_id))\n  WITH CHECK (user_is_account_member(account_id));
\n\nCREATE POLICY "Account members can delete supply order items"\n  ON public.supply_order_items FOR DELETE\n  TO authenticated\n  USING (user_is_account_member(account_id));
\n\n-- Supply Orders Table\nCREATE POLICY "Account members can view supply orders"\n  ON public.supply_orders FOR SELECT\n  TO authenticated\n  USING (user_is_account_member(account_id));
\n\nCREATE POLICY "Account members can create supply orders"\n  ON public.supply_orders FOR INSERT\n  TO authenticated\n  WITH CHECK (user_is_account_member(account_id));
\n\nCREATE POLICY "Account members can update supply orders"\n  ON public.supply_orders FOR UPDATE\n  TO authenticated\n  USING (user_is_account_member(account_id))\n  WITH CHECK (user_is_account_member(account_id));
\n\nCREATE POLICY "Account owners and admins can delete supply orders"\n  ON public.supply_orders FOR DELETE\n  TO authenticated\n  USING (user_is_account_owner_or_admin(account_id));
\n\n-- ============================================================================\n-- NOTES\n-- ============================================================================\n\n/*\n  ## Remaining Issues to Address Manually\n\n  1. **Leaked Password Protection**: Enable this in your Supabase Dashboard under:\n     Authentication > Settings > Password protection\n     \n  2. **Unused Indexes**: The following indexes are currently unused but kept for potential future use:\n     - idx_leads_new_status\n     - idx_api_keys_key_hash\n     - idx_interactions_created_at\n     - idx_invoices_due_date\n     - idx_invoices_status\n     - idx_material_items_material_list_id\n     - idx_payments_invoice_id\n     - idx_payments_status\n     - idx_supply_order_items_supply_order_id\n     - idx_supply_orders_status\n     - idx_webhook_events_* (event_type, processed_at, status)\n     - idx_leads_scheduled_date\n     - idx_leads_crew_lead_id\n     - idx_leads_customer_id\n     - idx_leads_account_id\n     - idx_customers_account_id\n     - idx_accounts_invite_code\n     \n     Monitor these in production. If truly unused after analysis, consider removing them.\n\n  3. **User Roles Table**: Still needs proper RLS policies if being used.\n  \n  4. **Webhook Events**: Still needs proper RLS policies if being used.\n*/;
