/*\n  # Add is_estimate_visit column to leads table\n\n  1. Modified Tables\n    - `leads`\n      - `is_estimate_visit` (boolean, default false) - Indicates whether a job is an estimate visit\n        rather than a regular job. Replaces the previous convention of appending ", Estimate" to the job name.\n\n  2. Trigger Updates\n    - `auto_create_estimate_for_job` - Updated to check `is_estimate_visit` column instead of\n      name pattern matching. Estimate visits should not auto-generate estimate records.\n\n  3. Important Notes\n    - Existing estimate visit jobs (identified by name ending in ", Estimate") are backfilled\n      to have is_estimate_visit = true.\n    - This ensures the flag cannot be manipulated by users editing the job name.\n*/\n\nDO $$\nBEGIN\n  IF NOT EXISTS (\n    SELECT 1 FROM information_schema.columns\n    WHERE table_name = 'leads' AND column_name = 'is_estimate_visit'\n  ) THEN\n    ALTER TABLE leads ADD COLUMN is_estimate_visit boolean NOT NULL DEFAULT false;
\n  END IF;
\nEND $$;
\n\nUPDATE leads\nSET is_estimate_visit = true\nWHERE name LIKE '%, Estimate'\n  AND status IN ('job', 'paid')\n  AND is_estimate_visit = false;
\n\nCREATE OR REPLACE FUNCTION public.auto_create_estimate_for_job()\nRETURNS trigger\nLANGUAGE plpgsql\nSECURITY DEFINER\nSET search_path = public\nAS $function$\nBEGIN\n  IF NEW.status IN ('job', 'paid')\n  AND NEW.approval_status = 'approved'\n  AND NEW.is_estimate_visit = false THEN\n\n    IF NOT EXISTS (SELECT 1 FROM public.estimates WHERE job_id = NEW.id) THEN\n      INSERT INTO public.estimates (job_id, account_id, status, total_amount)\n      VALUES (NEW.id, NEW.account_id, 'draft', 0);
\n    END IF;
\n  END IF;
\n\n  RETURN NEW;
\nEND;
\n$function$;
\n;
