/*\n  # Rework Invoices as Separate from Estimates\n\n  1. Changes to Tables\n    - `estimates`\n      - Drop `is_finalized` column (no longer needed since estimates don't convert to invoices)\n\n    - `invoices`\n      - Make `estimate_id` NOT NULL (all invoices must be tied to an estimate)\n      - Add `invoice_number` column for tracking invoice numbering\n      - Add index on `estimate_id` for better query performance\n\n  2. New Functions\n    - `validate_invoice_total()` - Ensures sum of invoices for an estimate doesn't exceed estimate total\n\n  3. New Triggers\n    - Trigger to validate invoice total before insert/update\n\n  4. Important Notes\n    - Estimates remain editable and never get "finalized"\n    - Multiple invoices can be created for a single estimate\n    - Invoice totals cannot exceed the estimate total\n    - Invoice numbering is sequential per account\n*/\n\n-- Drop the is_finalized column from estimates\nDO $$\nBEGIN\n  IF EXISTS (\n    SELECT 1 FROM information_schema.columns\n    WHERE table_name = 'estimates' AND column_name = 'is_finalized'\n  ) THEN\n    ALTER TABLE estimates DROP COLUMN is_finalized;
\n  END IF;
\nEND $$;
\n\n-- Make estimate_id NOT NULL on invoices (all invoices must reference an estimate)\nDO $$\nBEGIN\n  -- First update any NULL values to a valid estimate_id if they exist\n  -- We'll skip this as invoices without estimates should not exist in the new flow\n\n  -- Make the column NOT NULL\n  IF EXISTS (\n    SELECT 1 FROM information_schema.columns\n    WHERE table_name = 'invoices' AND column_name = 'estimate_id'\n  ) THEN\n    ALTER TABLE invoices ALTER COLUMN estimate_id SET NOT NULL;
\n  END IF;
\nEND $$;
\n\n-- Add invoice_number column for tracking\nDO $$\nBEGIN\n  IF NOT EXISTS (\n    SELECT 1 FROM information_schema.columns\n    WHERE table_name = 'invoices' AND column_name = 'invoice_number'\n  ) THEN\n    ALTER TABLE invoices ADD COLUMN invoice_number integer;
\n  END IF;
\nEND $$;
\n\n-- Add index on estimate_id for better query performance\nCREATE INDEX IF NOT EXISTS idx_invoices_estimate_id ON invoices(estimate_id);
\n\n-- Function to validate that invoice totals don't exceed estimate total\nCREATE OR REPLACE FUNCTION validate_invoice_total()\nRETURNS TRIGGER\nSECURITY DEFINER\nSET search_path = public\nLANGUAGE plpgsql\nAS $$\nDECLARE\n  v_estimate_total numeric(12,2);
\n  v_existing_invoices_total numeric(12,2);
\n  v_new_total numeric(12,2);
\nBEGIN\n  -- Get the estimate total\n  SELECT total INTO v_estimate_total\n  FROM estimates\n  WHERE id = NEW.estimate_id;
\n\n  IF v_estimate_total IS NULL THEN\n    RAISE EXCEPTION 'Estimate not found';
\n  END IF;
\n\n  -- Get the sum of existing invoices for this estimate (excluding current invoice if updating)\n  SELECT COALESCE(SUM(total), 0) INTO v_existing_invoices_total\n  FROM invoices\n  WHERE estimate_id = NEW.estimate_id\n    AND (TG_OP = 'INSERT' OR id != NEW.id);
\n\n  -- Calculate new total\n  v_new_total := v_existing_invoices_total + NEW.total;
\n\n  -- Check if new total exceeds estimate total\n  IF v_new_total > v_estimate_total THEN\n    RAISE EXCEPTION 'Invoice total ($%) would exceed estimate total ($%). Remaining: $%',\n      v_new_total,\n      v_estimate_total,\n      v_estimate_total - v_existing_invoices_total;
\n  END IF;
\n\n  RETURN NEW;
\nEND;
\n$$;
\n\n-- Create trigger to validate invoice totals\nDROP TRIGGER IF EXISTS validate_invoice_total_trigger ON invoices;
\nCREATE TRIGGER validate_invoice_total_trigger\n  BEFORE INSERT OR UPDATE OF total ON invoices\n  FOR EACH ROW\n  EXECUTE FUNCTION validate_invoice_total();
\n\n-- Function to generate next invoice number for an account\nCREATE OR REPLACE FUNCTION get_next_invoice_number(p_account_id uuid)\nRETURNS integer\nSECURITY DEFINER\nSET search_path = public\nLANGUAGE plpgsql\nAS $$\nDECLARE\n  v_next_number integer;
\nBEGIN\n  SELECT COALESCE(MAX(invoice_number), 0) + 1 INTO v_next_number\n  FROM invoices\n  WHERE account_id = p_account_id;
\n\n  RETURN v_next_number;
\nEND;
\n$$;
\n\n-- Add comment explaining the new workflow\nCOMMENT ON TABLE invoices IS 'Invoices are separate from estimates. Multiple invoices can be created for a single estimate, but their total cannot exceed the estimate total.';
\nCOMMENT ON COLUMN invoices.estimate_id IS 'Required reference to the estimate this invoice is based on';
\nCOMMENT ON COLUMN invoices.invoice_number IS 'Sequential invoice number per account for tracking';
\n;
