/*\n  # Set Status to Won When All Schedules Removed\n\n  ## Summary\n  Updates the job status function to set status to 'won' when all schedules\n  are removed from a job.\n\n  ## Changes\n  - When no schedules exist, set status to 'won' instead of keeping current status\n  - This allows jobs to return to 'won' status after all schedule dates are deleted\n*/\n\n-- Drop and recreate the function with won status logic\nDROP TRIGGER IF EXISTS trigger_update_job_completion ON job_schedules;
\nDROP FUNCTION IF EXISTS update_job_completion_status();
\n\nCREATE OR REPLACE FUNCTION update_job_completion_status()\nRETURNS trigger AS $$\nDECLARE\n  first_schedule_datetime timestamptz;
\n  last_schedule_datetime timestamptz;
\n  current_status unified_status;
\n  new_status unified_status;
\n  schedule_count int;
\nBEGIN\n  -- Count how many schedules exist for this job\n  SELECT COUNT(*) INTO schedule_count\n  FROM job_schedules\n  WHERE lead_id = COALESCE(NEW.lead_id, OLD.lead_id);
\n\n  -- Get current job status\n  SELECT status INTO current_status\n  FROM leads\n  WHERE id = COALESCE(NEW.lead_id, OLD.lead_id);
\n\n  -- If no schedules exist, set status to 'won'\n  IF schedule_count = 0 THEN\n    -- Only update if not already in a final state\n    IF current_status NOT IN ('won', 'lost', 'invoiced', 'paid') THEN\n      UPDATE leads\n      SET status = 'won'::unified_status, updated_at = now()\n      WHERE id = COALESCE(NEW.lead_id, OLD.lead_id);
\n    END IF;
\n    RETURN COALESCE(NEW, OLD);
\n  END IF;
\n\n  -- Get the first scheduled datetime for this job\n  SELECT \n    CASE \n      WHEN scheduled_time_start IS NOT NULL THEN\n        (scheduled_date || ' ' || scheduled_time_start)::timestamptz\n      ELSE\n        (scheduled_date || ' 00:00:00')::timestamptz\n    END INTO first_schedule_datetime\n  FROM job_schedules\n  WHERE lead_id = COALESCE(NEW.lead_id, OLD.lead_id)\n  ORDER BY scheduled_date ASC, scheduled_time_start ASC NULLS FIRST\n  LIMIT 1;
\n\n  -- Get the last scheduled datetime for this job\n  SELECT \n    CASE \n      WHEN scheduled_time_end IS NOT NULL THEN\n        (scheduled_date || ' ' || scheduled_time_end)::timestamptz\n      ELSE\n        (scheduled_date || ' 23:59:59')::timestamptz\n    END INTO last_schedule_datetime\n  FROM job_schedules\n  WHERE lead_id = COALESCE(NEW.lead_id, OLD.lead_id)\n  ORDER BY scheduled_date DESC, scheduled_time_end DESC NULLS LAST\n  LIMIT 1;
\n\n  -- Determine new status based on schedule\n  IF now() > last_schedule_datetime THEN\n    -- Current time is after the last scheduled datetime\n    new_status := 'completed'::unified_status;
\n  ELSIF now() >= first_schedule_datetime AND now() <= last_schedule_datetime THEN\n    -- Current time is within the scheduled range (including all of today if it's a scheduled day)\n    new_status := 'in_progress'::unified_status;
\n  ELSIF now() < first_schedule_datetime THEN\n    -- Current time is before the first scheduled datetime\n    new_status := 'scheduled'::unified_status;
\n  END IF;
\n\n  -- Update status if it needs to change\n  -- Allow updating from 'completed' back to 'in_progress' or 'scheduled' if schedule changed\n  -- But never override manually set final statuses like 'won', 'lost', 'invoiced', 'paid'\n  IF new_status IS NOT NULL \n     AND new_status != current_status \n     AND current_status NOT IN ('won', 'lost', 'invoiced', 'paid') THEN\n    UPDATE leads\n    SET status = new_status, updated_at = now()\n    WHERE id = COALESCE(NEW.lead_id, OLD.lead_id);
\n  END IF;
\n\n  RETURN COALESCE(NEW, OLD);
\nEND;
\n$$ LANGUAGE plpgsql SECURITY DEFINER;
\n\n-- Recreate trigger\nCREATE TRIGGER trigger_update_job_completion\n  AFTER INSERT OR UPDATE OR DELETE ON job_schedules\n  FOR EACH ROW\n  EXECUTE FUNCTION update_job_completion_status();
\n;
