/*\n  # Preserve invoices when estimate is deleted\n\n  ## Problem\n  When deleting a customer:\n  1. Customer deletion cascades to estimates (ON DELETE CASCADE)\n  2. Estimates have invoices referencing them via estimate_id (NOT NULL, ON DELETE NO ACTION)\n  3. The foreign key constraint blocks the deletion with error:\n     "update or delete on table "estimates" violates foreign key constraint "invoices_estimate_id_fkey""\n\n  ## Solution\n  Make invoices.estimate_id nullable and change the foreign key constraint to SET NULL on delete.\n  This preserves invoices as historical records even when estimates or customers are deleted.\n\n  ## Changes\n  1. Make invoices.estimate_id nullable (remove NOT NULL constraint)\n  2. Change foreign key constraint from ON DELETE NO ACTION to ON DELETE SET NULL\n  3. Update the validate_invoice_total trigger to handle NULL estimate_id gracefully\n\n  ## Important Notes\n  - Invoices are historical/accounting records that should be preserved\n  - Even if the estimate or customer is deleted, the invoice data remains for auditing\n  - The invoice still maintains its total, line items, and payment information\n*/\n\n-- Make estimate_id nullable in invoices table\nALTER TABLE invoices \nALTER COLUMN estimate_id DROP NOT NULL;
\n\n-- Drop the existing foreign key constraint\nALTER TABLE invoices \nDROP CONSTRAINT IF EXISTS invoices_estimate_id_fkey;
\n\n-- Add the new foreign key constraint with SET NULL\nALTER TABLE invoices \nADD CONSTRAINT invoices_estimate_id_fkey \nFOREIGN KEY (estimate_id) \nREFERENCES estimates(id) \nON DELETE SET NULL;
\n\n-- Update the validate_invoice_total function to handle NULL estimate_id\nCREATE OR REPLACE FUNCTION validate_invoice_total()\nRETURNS TRIGGER\nSECURITY DEFINER\nSET search_path = public\nLANGUAGE plpgsql\nAS $$\nDECLARE\n  v_estimate_total numeric(12,2);
\n  v_existing_invoices_total numeric(12,2);
\n  v_new_total numeric(12,2);
\nBEGIN\n  -- Skip validation if estimate_id is NULL (estimate was deleted)\n  IF NEW.estimate_id IS NULL THEN\n    RETURN NEW;
\n  END IF;
\n\n  -- Get the estimate total\n  SELECT total INTO v_estimate_total\n  FROM estimates\n  WHERE id = NEW.estimate_id;
\n\n  IF v_estimate_total IS NULL THEN\n    RAISE EXCEPTION 'Estimate not found';
\n  END IF;
\n\n  -- Get the sum of existing invoices for this estimate (excluding current invoice if updating)\n  SELECT COALESCE(SUM(total), 0) INTO v_existing_invoices_total\n  FROM invoices\n  WHERE estimate_id = NEW.estimate_id\n    AND (TG_OP = 'INSERT' OR id != NEW.id);
\n\n  -- Calculate new total\n  v_new_total := v_existing_invoices_total + NEW.total;
\n\n  -- Check if new total exceeds estimate total\n  IF v_new_total > v_estimate_total THEN\n    RAISE EXCEPTION 'Invoice total ($%) would exceed estimate total ($%). Remaining: $%',\n      v_new_total,\n      v_estimate_total,\n      v_estimate_total - v_existing_invoices_total;
\n  END IF;
\n\n  RETURN NEW;
\nEND;
\n$$;
\n\n-- Update table comment\nCOMMENT ON COLUMN invoices.estimate_id IS 'Reference to the estimate this invoice is based on. Can be NULL if the estimate was deleted (invoice is preserved as historical record).';
\n;
