/*\n  # Fix conversion function - remove paid status\n\n  1. Changes\n    - Remove references to 'paid' status in try_convert_lead_to_job function\n    - Update status checks to only use 'job' and 'completed'\n    - Change estimate job status update from 'paid' to 'completed'\n*/\n\nCREATE OR REPLACE FUNCTION try_convert_lead_to_job(p_lead_id uuid)\nRETURNS void\nLANGUAGE plpgsql\nSECURITY DEFINER\nSET search_path = public\nAS $$\nDECLARE\n  _lead record;
\n  _has_accepted_estimate boolean;
\n  _has_before_photos boolean;
\n  _all_checklist_complete boolean;
\n  _new_job_id uuid;
\n  _estimate record;
\nBEGIN\n  SELECT * INTO _lead FROM leads WHERE id = p_lead_id;
\n\n  IF _lead IS NULL THEN\n    RETURN;
\n  END IF;
\n\n  SELECT EXISTS (\n    SELECT 1 FROM estimates WHERE job_id = p_lead_id AND status = 'accepted'\n  ) INTO _has_accepted_estimate;
\n\n  SELECT EXISTS (\n    SELECT 1 FROM lead_photos WHERE lead_id = p_lead_id AND photo_type = 'before'\n  ) INTO _has_before_photos;
\n\n  IF NOT (_has_accepted_estimate AND _has_before_photos) THEN\n    RETURN;
\n  END IF;
\n\n  -- For estimate visit jobs, also check that all checklist items are complete\n  IF _lead.is_estimate_visit = true AND _lead.status = 'job' THEN\n    -- Check if all checklist items are completed\n    SELECT CASE \n      WHEN count(*) = 0 THEN false\n      WHEN count(*) FILTER (WHERE is_completed = false) > 0 THEN false\n      ELSE true\n    END INTO _all_checklist_complete\n    FROM job_checklist_items\n    WHERE job_id = p_lead_id;
\n\n    -- Only proceed if all checklist items are complete\n    IF NOT _all_checklist_complete THEN\n      RETURN;
\n    END IF;
\n\n    -- Get the estimate data\n    SELECT id, account_id\n    INTO _estimate\n    FROM estimates\n    WHERE job_id = p_lead_id AND status = 'accepted'\n    LIMIT 1;
\n\n    -- Create new regular job from estimate visit\n    INSERT INTO leads (\n      name, status, service_type, address, city, state,\n      customer_id, account_id, created_by,\n      approval_status, is_estimate_visit, estimate_job_id,\n      estimated_value, phone, email, source\n    )\n    VALUES (\n      REPLACE(_lead.name, ', Estimate', ''),\n      'job',\n      _lead.service_type,\n      _lead.address,\n      _lead.city,\n      _lead.state,\n      _lead.customer_id,\n      _lead.account_id,\n      _lead.created_by,\n      'pending',\n      false,\n      p_lead_id,\n      _lead.estimated_value,\n      _lead.phone,\n      _lead.email,\n      _lead.source\n    )\n    RETURNING id INTO _new_job_id;
\n\n    -- Copy job line items from estimate to new job\n    IF _estimate.id IS NOT NULL THEN\n      INSERT INTO job_line_items (\n        lead_id,\n        name,\n        description,\n        quantity,\n        unit,\n        unit_price,\n        total,\n        sort_order,\n        account_id,\n        estimate_line_item_id,\n        category\n      )\n      SELECT\n        _new_job_id,\n        name,\n        description,\n        quantity,\n        unit,\n        unit_price,\n        total,\n        sort_order,\n        _estimate.account_id,\n        id,\n        category\n      FROM estimate_line_items\n      WHERE estimate_id = _estimate.id\n      AND is_change_order = false\n      ORDER BY sort_order;
\n    END IF;
\n\n    -- Update estimate to point to new job\n    UPDATE estimates SET job_id = _new_job_id WHERE job_id = p_lead_id;
\n\n    -- Transfer photos to new job\n    UPDATE lead_photos SET lead_id = _new_job_id WHERE lead_id = p_lead_id;
\n\n    -- Approve the new job\n    UPDATE leads SET approval_status = 'approved' WHERE id = _new_job_id;
\n\n    -- Mark old estimate visit schedules as complete\n    UPDATE job_schedules\n    SET is_completed = true, completed_at = now()\n    WHERE lead_id = p_lead_id;
\n\n    -- Mark estimate visit as completed\n    UPDATE leads SET status = 'completed' WHERE id = p_lead_id;
\n\n    -- Add interaction log\n    INSERT INTO interactions (lead_id, type, direction, summary)\n    VALUES (\n      _new_job_id,\n      'status_change',\n      'na',\n      'Job created from completed estimate visit'\n    );
\n\n    RETURN;
\n  END IF;
\n\n  -- Regular lead conversion (non-estimate visit)\n  IF _lead.status IN ('job', 'completed') THEN\n    RETURN;
\n  END IF;
\n\n  UPDATE leads SET status = 'job' WHERE id = p_lead_id;
\n\n  IF _lead.estimate_job_id IS NOT NULL THEN\n    UPDATE leads SET status = 'completed' WHERE id = _lead.estimate_job_id;
\n  END IF;
\n\n  INSERT INTO interactions (lead_id, type, direction, summary)\n  VALUES (\n    p_lead_id,\n    'status_change',\n    'na',\n    'Converted to job (estimate approved + photos uploaded)'\n  );
\nEND;
\n$$;
;
