/*\n  # Fix Job Costs to Copy to Regular Job\n\n  ## Overview\n  Updates the trigger logic to ensure job costs are copied to the regular job, not the estimate job.\n  \n  When an estimate is approved:\n  - If the estimate's job_id points to an estimate visit job (is_estimate_visit = true)\n  - Find the parent/regular job (the one with estimate_job_id pointing to this estimate job)\n  - Copy line items to the regular job instead\n  \n  ## Changes\n  - Update `copy_estimate_line_items_to_job()` function to correctly identify the target job\n  - Handle both estimate visit scenario and direct job scenario\n*/\n\n-- Replace the function to copy estimate line items to the correct job\nCREATE OR REPLACE FUNCTION copy_estimate_line_items_to_job()\nRETURNS TRIGGER\nLANGUAGE plpgsql\nSECURITY DEFINER\nSET search_path = public\nAS $$\nDECLARE\n  v_estimate_job_id uuid;
\n  v_target_job_id uuid;
\n  v_account_id uuid;
\n  v_is_estimate_visit boolean;
\nBEGIN\n  -- Check if estimate status changed to 'accepted'\n  IF NEW.status = 'accepted' AND (OLD.status IS NULL OR OLD.status != 'accepted') THEN\n    v_estimate_job_id := NEW.job_id;
\n    v_account_id := NEW.account_id;
\n    \n    -- Only proceed if estimate has a linked job\n    IF v_estimate_job_id IS NOT NULL THEN\n      -- Check if this is an estimate visit job\n      SELECT is_estimate_visit INTO v_is_estimate_visit\n      FROM leads\n      WHERE id = v_estimate_job_id;
\n      \n      IF v_is_estimate_visit THEN\n        -- This is an estimate visit, find the parent/regular job\n        SELECT id INTO v_target_job_id\n        FROM leads\n        WHERE estimate_job_id = v_estimate_job_id\n        LIMIT 1;
\n        \n        -- If no parent job found, something is wrong, skip\n        IF v_target_job_id IS NULL THEN\n          RETURN NEW;
\n        END IF;
\n      ELSE\n        -- This is a direct job, use it as target\n        v_target_job_id := v_estimate_job_id;
\n      END IF;
\n      \n      -- Check if job line items already exist for this job\n      -- (to avoid duplicates if estimate is re-approved)\n      IF NOT EXISTS (\n        SELECT 1 FROM job_line_items \n        WHERE lead_id = v_target_job_id\n      ) THEN\n        -- Copy all estimate line items to job line items\n        INSERT INTO job_line_items (\n          lead_id,\n          name,\n          description,\n          quantity,\n          unit,\n          unit_price,\n          total,\n          sort_order,\n          account_id,\n          estimate_line_item_id\n        )\n        SELECT\n          v_target_job_id,\n          name,\n          description,\n          quantity,\n          unit,\n          unit_price,\n          total,\n          sort_order,\n          v_account_id,\n          id\n        FROM estimate_line_items\n        WHERE estimate_id = NEW.id\n        AND is_change_order = false\n        ORDER BY sort_order;
\n      END IF;
\n    END IF;
\n  END IF;
\n  \n  RETURN NEW;
\nEND;
\n$$;
\n\n-- The trigger is already created, no need to recreate it\n\n-- Also update the function for job creation to use the same logic\nCREATE OR REPLACE FUNCTION copy_estimate_items_on_job_creation()\nRETURNS TRIGGER\nLANGUAGE plpgsql\nSECURITY DEFINER\nSET search_path = public\nAS $$\nDECLARE\n  v_estimate_id uuid;
\n  v_estimate_status text;
\n  v_account_id uuid;
\n  v_estimate_job_id uuid;
\n  v_target_job_id uuid;
\n  v_is_estimate_visit boolean;
\nBEGIN\n  -- Check if this is an estimate visit job being created\n  IF NEW.is_estimate_visit THEN\n    -- Don't copy anything for estimate visit jobs\n    RETURN NEW;
\n  END IF;
\n  \n  -- Get the estimate for this job (if any)\n  SELECT id, status, account_id, job_id\n  INTO v_estimate_id, v_estimate_status, v_account_id, v_estimate_job_id\n  FROM estimates\n  WHERE job_id = NEW.id\n  LIMIT 1;
\n  \n  -- If there's an approved estimate, copy its line items\n  IF v_estimate_id IS NOT NULL AND v_estimate_status = 'accepted' THEN\n    -- The target is this newly created job\n    v_target_job_id := NEW.id;
\n    \n    -- Check if line items don't already exist\n    IF NOT EXISTS (\n      SELECT 1 FROM job_line_items \n      WHERE lead_id = v_target_job_id\n    ) THEN\n      -- Copy line items\n      INSERT INTO job_line_items (\n        lead_id,\n        name,\n        description,\n        quantity,\n        unit,\n        unit_price,\n        total,\n        sort_order,\n        account_id,\n        estimate_line_item_id\n      )\n      SELECT\n        v_target_job_id,\n        name,\n        description,\n        quantity,\n        unit,\n        unit_price,\n        total,\n        sort_order,\n        v_account_id,\n        id\n      FROM estimate_line_items\n      WHERE estimate_id = v_estimate_id\n      AND is_change_order = false\n      ORDER BY sort_order;
\n    END IF;
\n  END IF;
\n  \n  RETURN NEW;
\nEND;
\n$$;
;
