/*\n  # Fix estimate job status when lead converts to job\n\n  ## Overview\n  Previously, when a lead auto-converted to a job (estimate approved + photos uploaded),\n  the linked estimate visit job was set to status 'paid'. This was incorrect - the\n  estimate visit should show as 'completed', not 'paid'.\n\n  ## Changes\n  - Modified `try_convert_lead_to_job` function\n  - Instead of setting estimate job status to 'paid', mark its schedules as completed\n  - The estimate job stays at status 'job' so its display status computes to 'completed'\n    based on schedule dates\n\n  ## Important Notes\n  - 'completed' is a computed display status, not an enum value\n  - A job with status 'job' whose schedule dates are in the past displays as 'completed'\n  - Marking schedules as is_completed=true ensures they're tracked as done\n*/\n\nCREATE OR REPLACE FUNCTION try_convert_lead_to_job(p_lead_id uuid)\nRETURNS void\nLANGUAGE plpgsql\nSECURITY DEFINER\nSET search_path = public\nAS $$\nDECLARE\n  _lead record;
\n  _has_accepted_estimate boolean;
\n  _has_photos boolean;
\nBEGIN\n  SELECT status, estimate_job_id INTO _lead\n  FROM leads\n  WHERE id = p_lead_id;
\n\n  IF _lead.status IS NULL OR _lead.status IN ('job', 'paid') THEN\n    RETURN;
\n  END IF;
\n\n  SELECT EXISTS (\n    SELECT 1 FROM estimates\n    WHERE job_id = p_lead_id AND status = 'accepted'\n  ) INTO _has_accepted_estimate;
\n\n  SELECT EXISTS (\n    SELECT 1 FROM lead_photos\n    WHERE lead_id = p_lead_id\n  ) INTO _has_photos;
\n\n  IF _has_accepted_estimate AND _has_photos THEN\n    UPDATE leads SET status = 'job' WHERE id = p_lead_id;
\n\n    IF _lead.estimate_job_id IS NOT NULL THEN\n      UPDATE job_schedules\n      SET is_completed = true, completed_at = now()\n      WHERE lead_id = _lead.estimate_job_id;
\n    END IF;
\n\n    INSERT INTO interactions (lead_id, type, direction, summary)\n    VALUES (\n      p_lead_id,\n      'status_change',\n      'na',\n      'Converted to job (estimate approved + photos uploaded)'\n    );
\n  END IF;
\nEND;
\n$$;
\n;
