/*\n  # Add pg_cron schedule for email digest\n\n  1. Changes\n    - Enables the pg_cron and pg_net extensions\n    - Creates a cron job that runs daily at 8:00 AM UTC\n    - The job calls the send-email-digest edge function via pg_net\n    - Daily digests are sent every day;
 weekly digests are sent on Mondays only\n      (the edge function handles this logic internally)\n\n  2. Notes\n    - The cron job uses the service role key to authenticate\n    - pg_net makes the HTTP call asynchronously so it won't block the scheduler\n*/\n\nCREATE EXTENSION IF NOT EXISTS pg_cron WITH SCHEMA pg_catalog;
\n\nDO $$\nDECLARE\n  _supabase_url text;
\n  _service_role_key text;
\nBEGIN\n  SELECT decrypted_secret INTO _supabase_url\n  FROM vault.decrypted_secrets\n  WHERE name = 'supabase_url'\n  LIMIT 1;
\n\n  IF _supabase_url IS NULL THEN\n    SELECT current_setting('app.settings.supabase_url', true) INTO _supabase_url;
\n  END IF;
\n\n  SELECT decrypted_secret INTO _service_role_key\n  FROM vault.decrypted_secrets\n  WHERE name = 'service_role_key'\n  LIMIT 1;
\n\n  IF _service_role_key IS NULL THEN\n    SELECT current_setting('app.settings.service_role_key', true) INTO _service_role_key;
\n  END IF;
\n\n  IF _supabase_url IS NOT NULL AND _service_role_key IS NOT NULL THEN\n    PERFORM cron.unschedule('send-email-digest-daily');
\n\n    PERFORM cron.schedule(\n      'send-email-digest-daily',\n      '0 8 * * *',\n      format(\n        $cron$\n        SELECT extensions.http_post(\n          '%s/functions/v1/send-email-digest',\n          '{}',\n          'application/json',\n          ARRAY[\n            extensions.http_header('Authorization', 'Bearer %s'),\n            extensions.http_header('Content-Type', 'application/json')\n          ]\n        );
\n        $cron$,\n        _supabase_url,\n        _service_role_key\n      )\n    );
\n  END IF;
\nEND $$;
\n;
