/*\n  # Optimize RLS Performance for Jobs Queries\n\n  1. Performance Improvements\n    - Add session-level caching for role checks to reduce repeated queries to user_roles table\n    - Create helper function to get current user's roles once per query\n    - Modify RLS policies to use cached role information\n    - This significantly reduces database load when querying jobs with joined tables\n\n  2. Changes\n    - Create `get_user_roles()` function that caches roles for the session\n    - Optimize `has_role()` function to use the cached roles\n    - Add composite index on jobs foreign keys for better join performance\n\n  3. Technical Details\n    - Uses PostgreSQL's session-level settings to cache role data\n    - Reduces queries to user_roles from N per row to 1 per session\n    - Maintains security while improving performance\n*/\n\n-- Create a function to get all roles for the current user (cached per session)\nCREATE OR REPLACE FUNCTION get_user_roles()\nRETURNS TEXT[] AS $$\nDECLARE\n  roles TEXT[];
\nBEGIN\n  -- Try to get cached roles from session\n  BEGIN\n    roles := current_setting('app.user_roles', true)::TEXT[];
\n    IF roles IS NOT NULL THEN\n      RETURN roles;
\n    END IF;
\n  EXCEPTION WHEN OTHERS THEN\n    -- Setting doesn't exist yet, will create it below\n  END;
\n\n  -- Fetch and cache roles\n  SELECT ARRAY_AGG(role::TEXT)\n  INTO roles\n  FROM user_roles\n  WHERE user_id = auth.uid();
\n\n  -- Cache in session (only if we have a valid auth.uid())\n  IF auth.uid() IS NOT NULL THEN\n    PERFORM set_config('app.user_roles', COALESCE(roles::TEXT, '{}'), true);
\n  END IF;
\n\n  RETURN COALESCE(roles, ARRAY[]::TEXT[]);
\nEND;
\n$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;
\n\n-- Optimize the has_role function to use cached roles\nCREATE OR REPLACE FUNCTION has_role(_user_id UUID, _role app_role)\nRETURNS BOOLEAN AS $$\nBEGIN\n  -- Only use cache for current user\n  IF _user_id = auth.uid() THEN\n    RETURN _role::TEXT = ANY(get_user_roles());
\n  END IF;
\n  \n  -- For other users, do direct lookup\n  RETURN EXISTS (\n    SELECT 1\n    FROM user_roles\n    WHERE user_id = _user_id\n      AND role = _role\n  );
\nEND;
\n$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;
\n\n-- Add policy for crew leads to view profiles of other crew members\n-- This allows sales to see crew lead names when viewing jobs\nDROP POLICY IF EXISTS "Sales can view crew lead profiles" ON profiles;
\nCREATE POLICY "Sales can view crew lead profiles"\n  ON profiles\n  FOR SELECT\n  TO authenticated\n  USING (\n    has_role(auth.uid(), 'sales'::app_role) \n    AND EXISTS (\n      SELECT 1 FROM user_roles \n      WHERE user_id = profiles.user_id \n      AND role = 'crew_lead'::app_role\n    )\n  );
\n;
